<?php
$BOOKS = array(
'1'=>array(
'1',
'Azərbaycanlı',
'تفسير العشر الأخير من القرآن الكريم ويليه أحكام تهم المسلم',
'كتاب مختصر يحوي أهم ما يحتاجه المسلم في حياته من قرآن وتفسير وأحكام فقهية وعقدية وفضائل وغيرها، والكتاب ينقسم إلى جزئين: فأما الجزء الأول فيشتمل على الأجزاء الثلاثة الأخيرة من القرآن الكريم مع تفسيرها من كتاب زبدة التفسير للشيخ محمد الأشقر. وأما الجزء الثاني فيحتوي على أحكام تهم المسلم، وهي: أحكام التجويد، 62 سؤالا في العقيدة، حوار هادئ عن التوحيد، أحكام الاسلام [ الشهادتان، الطهارة، الصلاة، الزكاة، الحج ]، فوائد متفرقة، الرقية، الدعاء، الأذكار، 100 فضيلة و 70 منهيًا، صفة الوضوء والصلاة مصورة، رحلة الخلود.',
'Qurani kərimin son üç cüzünün təfsiri',
'-',
'http://www.islamhouse.com/p/384048',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Quran_oxumagin_savabi.pdf',
'',
'',
'',
''),

'2'=>array(
'2',
'Azərbaycanlı',
'ما قاله الثقلان في أولياء الرحمن',
'ما قاله الثقلان في أولياء الرحمن: هذه الورقات فيها بيان شافٍ - بإذن الله - و إظهار لمكانة أولئك النفر من الرجال والنساء من الصحابة، لأن من أحب إنساناً أحب أحبابه وتقبلهم بقبول حسن وأبغض أعداءهم ومبغضيهم، وهذه سنة ماضية في الخلق.',
'Allahın kitabı ilə Əhli Beytin ər-Rəhmanın dostları haqqında dedikləri',
'-',
'http://www.islamhouse.com/p/336323',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Ma_qalahu_saqalan.pdf',
'',
'',
'',
''),

'3'=>array(
'3',
'Azərbaycanlı',
'فضل أهل البيت',
'رسالة مختصرة تبين بعض فضائل أهل البيت رضي الله عنهم.',
'Əhli Beytin fəzilət',
'"Ey Əhli-beyt! Allah sizdən çirkinliyi yox etmək və sizi tərtəmiz (pak) etmək istər" (əl-Əhzab, 33)',
'http://www.islamhouse.com/p/329745',
'http://d1.islamhouse.com/data/az/ih_books/single/az_ahli_Beytin_fazilati.pdf,http://d1.islamhouse.com/data/az/ih_books/single/az_ahli_Beytin_fazilati.doc',
'Yaşar Qurbanov',
'',
'',
''),

'4'=>array(
'4',
'Azərbaycanlı',
'فضل الخلفاء الراشدين',
'الصحابة - رضوان الله عليهم - أبر هذه الأمة قلوباً، وأعمقها علماً، وأقلها تكلفاً، وأقومها هدياً، وأحسنها حالاً، ولا يعرف قدر لأمة إلا بمعرفة قدر عظمائها، وعظماء هذه الأمة بعد رسول الله - صلى الله عليه وسلم - هم أصحابه، ومنهم الخلفاء - أبو بكر الصديق، وعمر بن الخطاب، وعثمان بن عفان، وعلي بن أبي طالب - رضي الله عنهم - وفي هذه المادة بيان لصفحات من حياة هؤلاء العظماء؛ حتى نقتدي بهم، ونسير على دربهم.',
'Raşidi xəlifələrin fəziləti',
'Allahım, sən bizləri peyğəmbərimizin raşidi xəlifələri ilə bərabər həşr et. Allahım, biz peyğəmbərimiz (sav) raşidi xəlifələrini sevirik və bizə onlarla eyni cənnət nəsib et. Amin.',
'http://www.islamhouse.com/p/329743',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Rasidi_xalifalarin_fazilati.pdf,http://d1.islamhouse.com/data/az/ih_books/single/az_Rasidi_xalifalarin_fazilati.doc',
'Yaşar Qurbanov',
'',
'',
''),

'5'=>array(
'5',
'Azərbaycanlı',
'أريد أن أتوب .. ولكن!',
'أريد أن أتوب ولكن!: تحتوي هذه الرسالة على مقدمة عن خطورة الاستهانة بالذنوب فشرحاً لشروط التوبة، ثم علاجات نفسية، وفتاوى للتائبين مدعمة بالأدلة من القرآن الكريم والسنة، وكلام أهل العلم وخاتمة.',
'Tövbə etmək istəyirəm, lakin...',
'Kitabda tövbə etmək istəyənlər, amma bunda çətinlik çəkənlər haqqında söz açılır. Kitabda həmçinin günahlardan tövbə etmək istəyənlərə çıxış yolları göstərilir.',
'http://www.islamhouse.com/p/329739',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Tovba_etmak_istayiram_lakin.pdf',
'',
'Yaşar Qurbanov',
'',
''),

'6'=>array(
'6',
'Azərbaycanlı',
'التصفية والتربية وحاجة المسلمين إليهما',
'التصفية والتربية وحاجة المسلمين إليها: هذه الرسالة أصلها محاضرة ألقاها المحدث العلامة الشيخ محمد ناصر الدين الألباني - رحمه الله - في المعهد الشرعي في عمان بالأردن.',
'TƏMİZLƏNMƏ VƏ TƏRBİYƏ',
'“Təmizlənmə və tərbiyə, və müsəlmanların buna ehtiyacı” adlı bu risalə öz əsasında, otuz il bundan öncə (1390 il) Amman şəhərinin (İordaniya) şəriət elmləri institutunda, böyük alim-muhəddis şeyx Muhəmməd Nasıruddin əl-Albaninin, Allah ona rəhmət etsin, oxuduğu muhazirədir. Bu muhazirədə şeyx hər bir müsəlmanın tutması vacib olan yolu açıqlamışdır. Bu mühazirənin əsli iki sözdən ibarətdir – “təmizlənmə” və “tərbiyə”. Şeyx öz həyatını məhz islam əqidəsinin, ona əsrlər boyu daxil edilmiş müxtəlif zəlalətlərin çirkinliyindən, bidətlərdən, xurafatlardan və şirkdən təmizlənməsi yoluna həsr etmişdir. O həmçinin Sünnənin təmizlənməsilə də məşğul olmuşdur. O rəvayətlərin səhih, zəif və ya uydurma olduqunu tədqiq etmiş və bununla Sünnəyə aid olmayan rəvayətləri ayırmışdır. Həmçinin o fikh elmini də nəzərdən keçirmiş və Quran və Sünnəyə müxalif olan fikxi rəyləri və bidətləri təmizləmişdir. Bundan sonra şeyx tərbiyəyə keçmişdir. Əvvəl özünü, sonra ətrafını və bundan sonra da bu haqq yoluna dəvət edərək bütün insanları tərbiyələndirməyə başlamışdır. Onun dəvətinə dünyanın hər tərəfindən ümmətin ən xeyrli insanları olan alim və tələbələr dəstək vermişdir. Bundan sonra bütün dünyada elm əsasında dinin dirçəlməsi başlamışdır. Ümumi xeyr üçün Ammandaki “Əl-Maktaba əl-İslamiyya” nəşriyyatı bu risaləni yaymaq qərarına gəlmişdir. Bu risalə şeyxin elm xəzinələrindəndir və dünyanın hər bir yerində yaşayan müsəlmanlar üçün böyük bir faydadır. Biz ümid edirik ki bu risaləyə görə şeyx ölümündən sonra Allah tərəfindən və Allahın izni ilə mükafatlandıralacaqdır.',
'http://www.islamhouse.com/p/329670',
'http://d1.islamhouse.com/data/az/ih_books/single/az_tamizlanma_va_tarbiya.pdf,http://d1.islamhouse.com/data/az/ih_books/single/az_tamizlanma_va_tarbiya.doc',
'',
'',
'',
''),

'7'=>array(
'7',
'Azərbaycanlı',
'آفات اللسان في ضوء الكتاب والسنة',
'آفات اللسان في ضوء الكتاب والسنة: رسالة في بيان خطر آفات اللسان على الفرد والمجتمع، والأمة الإسلامية.',
'Dilin Törətdiyi Bəlalar',
'Ey iman gətirənlər! Çox zənnə-gümana qapılmaqdan çəkinin. Şübhəsiz ki, zənnin bəzisi (heç bir əsası olmayan zənn) günahdır. (Bir-birinizin eyibini, sirrini) arayıb axtarmayın, bir-birinizin qeybətini qırmayın! Sizdən biriniz ölmüş qardaşının ətini yeməyə razı olarmı?! Bu sizdə ikrah hissi oyadar (qeybət də belədir). Allahdan qorxun. Həqiqətən, Allah tövbələri qəbul edəndir, rəhmlidir! (əl-Hücurat,12)',
'http://www.islamhouse.com/p/328862',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Dilin_Toratdiyi_Balalar.pdf',
'',
'',
'',
''),

'8'=>array(
'8',
'Azərbaycanlı',
'الدعاء ويليه العلاج بالرقى من الكتاب والسنة',
'الدعاء ويليه العلاج بالرقى من الكتاب والسنة: تحتوي هذه الرسالة على بيان فَضْلُ الدُّعَاءِ، آدَابُ الدُّعَاءِ وَأسْبَابُ الإِجَابَةِ، أَوْقَاتُ وَأَحْوَالُ وَأمَاكِنُ يُسْتَجَابُ فِيهَا الدُّعَاءُ، الدُّعَاءُ مِنَ الكِتَابِ وَالسُّنَّةِ، مع بيان أهميَّةُ العِلاجِ بِالقُرْآنِ وَالسُّنَّةِ، وكيفية عِلاَجُ السِّحْرِ، والعين، والْتِبَاسِ الْجِنِّيِّ بِالإِنْسِيِّ، والأمراض النفسية، وبعض الأمراض الأخرى.',
'Şəfa Duaları və Ovsunlar',
'Kitabçada Allahın nazil etdiyi, peyğəmbərlərin dilədiyi , həmçinin Məhəmməd peyğəmbərin etdiyi dua və zikrlər verilmişdir.',
'http://www.islamhouse.com/p/328860',
'http://d1.islamhouse.com/data/az/ih_books/single/az_safa_Dualar_va_Ovsunlar.pdf',
'',
'',
'',
''),

'9'=>array(
'9',
'Azərbaycanlı',
'العقيدة الواسطية',
'العقيدة الواسطية: رسالة نفيسة لشيخ الإسلام ابن تيمية - رحمه الله - ذكر فيها جمهور مسائل أصول الدين، ومنهج أهل السنة والجماعة في مصادر التلقي التي يعتمدون عليها في العقائد؛ لذا احتلت مكانة كبيرة بين علماء أهل السنة وطلبة العلم، لما لها من مميزات عدة من حيث اختصار ألفاظها ودقة معانيها وسهولة أسلوبها، وأيضاً ما تميزت به من جمع أدلة أصول الدين العقلية والنقلية.',
'Vasitiyyə əqidəsi',
'Müsəlman bacı və qardaşlarım! Hər bir müsəlmana Allahın adları və sifətləri barəsində düzgün etiqad sahibi olması olduqca zəruridir. Çünku burada Allahın gözəl adları və sifətlərindən söz gedir. Elə müsəlmanlar var ki, bu mövzuda batil etiqadlara uyaraq Allah barəsində pis zənnə qapılırlar. Sizə təqdim edilən "Vasitiyyə Əqidəsi" bu mövzuda yazılıan ən mühim əsərlərdən birisidir. Hamıya bu kitabı oxumağı tövsiyə edirəm. İlahiyyatçı: Yaşar Qurbanov',
'http://www.islamhouse.com/p/328823',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Vasitiyya_aqidasi.pdf',
'',
'',
'',
''),

'10'=>array(
'10',
'Azərbaycanlı',
'التوحيد أولا يا دعاة الإسلام',
'التوحيد أولا يا دعاة الإسلام : رسالة عظيمة النفع والفائدة للعامة والخاصة؛ يُجيب فيها عالم من علماء هذا العصر وهو فضيلة الشيخ محمد ناصر الدين الألباني - رحمه الله تعالى -، على سؤال يدور على ألسنة الغيورين على هذا الدين الذي يحملونه في قلوبهم ويشغلون فكرهم به ليلًا ونهارًا ومجمل السؤال هو: ما هو السبيل إلى النهوض بالمسلمين وما هو الطريق الذي يتخذونه حتى يمكن الله لهم ويضعهم في المكان اللائق بهم بين الأمم؟ فأجاب - رحمه الله - على هذا السؤال إجابة مفصلة واضحة. ولما لهذه الإجابة من حاجة، رأينا نشرها. فأسأل الله تعالى أن ينفع بها وأن يهدي المسلمين إلى ما يحب ويرضى؛ إنه جواد كريم.',
'Ey İslam Təbliğatçıları, Tövhid Hər Şeydən Öncədir',
'Hörmətli müsəlman qardaşım! Bu risalə, əsrimizin dahi alimi, yüzlərlə elmi fitvanın və möhtəşəm əsərlərin müəllifi, on minlərlə hədisin üzərində misilsiz elmi tədqiqatlar aparmış hədis mütəxəssisi, sünnəyə sarılmağı ilə zəmanəsinin sələfinə sarsılmaz arxa olmuş hörmətli şeyx Məhəmməd Nasiruddin Əl-Əlbaninin (Allah onun qəbrini nurla doldursun) İslam ümmətinə verdiyi dəyərli nəsihətlərdən bəhs edir. Kitabda Hər bir müsəlmanın bilməsi vacib olan önəmli məsələlərdən söz açılır',
'http://www.islamhouse.com/p/328821',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Tovhid_Har_Şeydan_oncadir.pdf',
'',
'',
'',
''),

'11'=>array(
'11',
'Azərbaycanlı',
'وسائل الثبات على دين الله',
'وسائل الثبات على دين الله : فإن الثبات على دين الله - عز وجل - مطلب أساسي لكل مسلم صادق يريد سلوك الصراط المستقيم بعزيمة ورشد، ومن رحمة الله - عز وجل - بنا أن بين لنا في كتابه وعلى لسان نبيه - صلى الله عليه وسلم - وفي سيرته وسائل كثيرة للثبات، وفي هذه الرسالة بيان لبعض هذه الوسائل.',
'Allahın Dinində Möhkəm və Sabitqədəm Olmağın Yolları',
'Şübhəsiz ki, Allahın dinində möhkəm və sabitqədəm olmaq , əzm və rəşadətlə doğru getmək istəyən hər bir müsəlmanın əsas məqsədi olmalıdır. Əsasəndə fitnə -fəsadların çoxaldığı bir dövrdə buna daha çox önəm verilməlidir. Hər bir müsəlman qardaş və bacımızın bu kitabcanı oxuyub, əməl etməsi çox zəruridir. Uca Allah bütün müsəlmanalrı qorusun Amin.',
'http://www.islamhouse.com/p/328819',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Allahin_Dininda_Mohkam_va_Sabitqadam_Olmagın_Yollar.pdf',
'',
'',
'',
''),

'12'=>array(
'12',
'Azərbaycanlı',
'محرمات استهان بها كثير من الناس',
'محرمات استهان بها كثير من الناس : في هذه الرسالة يجد القارئ الكريم عدداً من المحرمات التي ثبت تحريمها في الشريعة مع بيان أدلة التحريم من الكتاب والسنة، وهذه المحظورات مما شاع فعلها وعم ارتكابها بين كثير من المسلمين، والله المستعان.',
'İnsanların əhəmiyyət vermədiyi haramlar və onlardan çəkinmə',
'Bu kitabda İslam əxlaqı və əqidəsinin ən mühüm məsələlərindən olan insanların çoxunun əhəmiyyət vermədiyi haramlar və onlardan çəkinmə haqqında geniş məlumat yer almaqdadır. Hər bir müsəlman Allah və rəsulunun haram buyurduğu əməllərdən çəkinməlidir. Bu kitabı tərcümə edərək oxucularımıza təqdim edəm Fərahim qardaşımızdan Allah razı olsun.',
'http://www.islamhouse.com/p/328767',
'http://d1.islamhouse.com/data/az/ih_books/single/az_insanların_ahamiyyat_vermadiyi_haramlar_va_onlardan_cakinma.pdf',
'',
'',
'',
''),

'13'=>array(
'13',
'Azərbaycanlı',
'أربعون نصيحة لإصلاح البيوت',
'أربعون نصيحة لإصلاح البيوت : الاهتمام بالبيت هو الوسيلة الكبيرة لبناء المجتمع المسلم، فإن المجتمع يتكون من بيوت هي لبناته ، والبيوت أحياء، والأحياء مجتمع، فلو صلحت اللبنة لكان مجتمعا قويا بأحكام الله، صامدا في وجه أعداء الله، يشع الخير ولا ينفذ إليه شر. فيخرج من البيت المسلم إلى المجتمع أركان الإصلاح فيه؛ من الداعية القدوة، وطالب العلم، والمجاهد الصادق، والزوجة الصالحة، والأم المربية، وبقية المصلحين. فإذا كان الموضوع بهذه الأهمية، وبيوتنا فيها منكرات كثيرة، وتقصير كبير، وإهمال وتفريط؛ فهنا يأتي السؤال الكبير: ما هي وسائل إصلاح البيوت؟ وإليك أيها القارئ الكريم الجواب ، نصائح في هذا المجال عسى الله أن ينفع بها، وأن يوجه جهود أبناء الإسلام لبعث رسالة البيت المسلم من جديد، وهذه النصائح تدور على أمرين : إما تحصيل مصالح، وهو قيام بالمعروف، أو درء مفاسد وهو إزالة للمنكر.',
'Ailə Tərbiyəsinə Dair 40 Nəsihət',
'Dəyərli bacı və qardaşlarım! Bu kitabda müsəlmanı ailəsinin düzgün tərbiyələndirilməsinə sövq edən amillərdən söz açılır. Allah və onun rəsulunun buyurduğu üzərinə kim ailəsini tərbiyə etmək istəyirsə bu kitabda yazılanlara əməl etsin.',
'http://www.islamhouse.com/p/328765',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Aila_Tarbiyasina_Dair_40_Nasihat.pdf',
'',
'',
'',
''),

'14'=>array(
'14',
'Azərbaycanlı',
'صفة صلاة النبي صلى الله عليه وسلم من التكبير إلى التسليم كأنك تراها',
'صفة صلاة النبي صلى الله عليه و سلم, من التكبير إلى التسليم كأنك تراها: ما من عبادة إلا ولها صفة وكيفية، قد تكفل الله سبحانه ببيانها، و بينها رسوله - صلى الله عليه وسلم -، وفي هذه الرسالة بيان لصفة صلاة النبي - صلى الله عليه وسلم.',
'Sanki Onu Görürmüşsən Kimi Peyğəmbərin Namazı təkbirdən təslimədək',
'Peyğəmbərimiz (sav) buyurmuşdur: "Mənim necə namaz qıldığımı gördünüzmü, o cür də namaz qılın" Bu kitabda peyğəmbərimiz (sav)-ın namazı necə qıldığı səhih hədsilərlə açıqlanmışdır.',
'http://www.islamhouse.com/p/328763',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Peygambarin_Namaz.pdf',
'',
'',
'',
''),

'15'=>array(
'15',
'Azərbaycanlı',
'33 سبباً للخشوع في الصلاة',
'الخشوع لب الصلاة وروحها، فلا يعرف عظمة الصلاة من لم يذق الخشوع فيها، وعلى قدر الخشوع يكون الأجر، وفي هذه الرسالة بيان بعض الأسباب التي تعين على الخشوع.',
'Namazda Mütiliyə Aparan 33 Amil',
'Hər şeyi unudaraq ruhən və cismən Allaha müti olmaq dinin qanuni tələblərindən biri hesab olunur. Bu kitabda namazda müti olmağın əsaslarından bəhs edilir.',
'http://www.islamhouse.com/p/328760',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Namazda_Mutiliya_Aparan_33_Amil.pdf',
'',
'',
'',
''),

'16'=>array(
'16',
'Azərbaycanlı',
'مفهوم أهل السنة والجماعة',
'-',
'Sünnə və Cəməa anlayışı',
'Yaşar Qurbanovun tərcümə etdiyi "Sünnə və Cəməa anlayışı" adlı kitabı oxucularımıza təqdim edirik. Müasir dünyamızda özlərinin Əhli-Sünnə və Cəməa olduğunu iddia edən, fəqət bu anlayışdan çox kənar olan inam və etiqada sahib olan insanlar mövcuddur. Bu kitabda əhli-sünnə və cəməa anlayışının əsas prinsipləri ilə tanış olacaqsınız.',
'http://www.islamhouse.com/p/328758',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Sunna_va_Camaa_anlays.pdf,http://d1.islamhouse.com/data/az/ih_books/single/az_Sunna_va_Camaa_anlays.doc',
'',
'Yaşar Qurbanov',
'',
''),

'17'=>array(
'17',
'Azərbaycanlı',
'قاعدة في الصبر',
'قاعدة في الصبر : بدأ المؤلف - رحمه الله - هذه الرسالة ببيان أن الدين كله يرجع بجملته إلى أمرين هما: الصبر والشكر، واستدل لذلك بقوله تعالى: { إِنَّ فِي ذَلِكَ لآياتٍ لِكُلِّ صَبَّارٍ شَكُورٍ } وبقوله - صلـى الله عليه وسلم -: { عجباً لأمر المؤمن إن أمره كله عجب، لا يقضي الله لمؤمن قضاءً إلا كان خيراً له، إن أصابته سراء شكر فكان خيراً له،وإن أصابته ضراء صبر فكان خيراً له }. ثم بين أن الصبر عموماً ينقسم إلى ثلاثة أقسام هي: أولاً: صبر على الطاعة حتى يفعلها. ثانياً: صبر عن المنهي عنه حتى لا يفعله. ثالثاً: الصبر على ما يصيبه بغير اختياره من المصائب. ثم بين أن المصائب نوعان: النوع الأول: نوع لا اختيار للخلق فيه، كالأمراض وغيرها من المصائب السماوية، وهذا النوع يسهل الصبر فيه لأن العبد يشهد فيه قضاء الله وقدره،وأنه لا مدخل للناس فيه فيصبر إما اضطراراً وإما اختياراً. والنوع الثاني: المصائب التي تحصل للعبد بفعل الناس، في ماله أو عرضه أو نفسه، وهذا النوع يصعب الصبر عليه جداً لأن النفس تستشعر المؤذي لها وهي تكره الغلبة فتطلب الانتقام، ولا يصبر على هذا النوع إلا النبيون والصديقون. وقد اقتصر كلام المصنف - رحمه الله - في بقية الرسالة على الأسباب التي تعين العبد على الصبر على المصائب التي تصيبه بفعل الناس، وذكر ذلك من عشرين وجهاً. وختم المصنف كلامه بالإشارة إلى الأصل الثاني وهو: الشكر وفسره بأنه العمل بطاعة الله واقتصر على ذلك وخلت الرسالة من تفصيل القول في ذلك، ولعل السبب في ذلك هو تصرف من أفرد الرسالة بالذكر وفصلها عن باقي التصنيف وإلا فالرسالة لها تتمة، ويشهد لذلك ما ذكره ابن رشيق في تعداده لمؤلفات ابن تيمية حيث قال: "قاعدة في الصبر والشكر. نحو ستين ورقة" فقد تصرف المختصر في العنوان واقتصر كذلك على ما كتب في موضوع الصبر فقط، ولم يكمل بقية الرسالة، والله أعلم.',
'Səbr Etməyin Qaydası',
'Uca Allah öz peyğəmbərinə səbrli olmağı əmr etmiş və buyurmuşdur: "Ya Rəsulum! Allah yolunda olan bütün əzab-əziyyətə) səbr et. Sənin səbr etməyin yalnız Allahın köməyilədir." (ən-Nəhl,127)',
'http://www.islamhouse.com/p/328731',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Sabr_Etmayin_Qaydas.pdf',
'',
'Muxtar Əli',
'Ramil Həsən',
''),

'18'=>array(
'18',
'Azərbaycanlı',
'سر النجاح ومفتاح الخير والبركة والفلاح [ كيف تكون ناجحاً في أعمالك ]',
'سر النجاح ومفتاح الخير والبركة والفلاح [ كيف تكون ناجحًا في أعمالك ]: رسالة مفيدة تبين المراد بصلاة الاستخارة، فضلها وأهميتها، صفتها، هل تجزئ صلاة الاستخارة عن تحية المسجد والسنة الراتبة، وقتها، الأمور التي تشرع لها الاستخارة، هل يشترط التردد، هل يشرع تكرار الاستخارة؟ ... إلخ.',
'İSTİXARƏ (Uğurun sirri, xeyir-bərəkət açarı)',
'Nə qədər ağıllı, elmli və müdrik olur olsun, hər bir insan öz Rəbbinə, onu yaradana istənilən an möhtacdır və əbədi olan bu yeganə varlıq hər bir göz qırpımında belə mütləq ona lazımdır.',
'http://www.islamhouse.com/p/328718',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Ugurun_sirri_xeyir_barakat_acarı.pdf',
'',
'',
'',
''),

'19'=>array(
'19',
'Azərbaycanlı',
'أصول السنة للإمام أحمد بن حنبل',
'يعد كتاب أصول السنة من الكتب المهمة؛ لعدة أسباب: 1- أن مؤلفه الإمام أحمد، وهو إمام أهل السنة والجماعة. 2- تقريره للضوابط العامة والقواعد الأساسية التي تضبط مذهب السلف والتي تخالف أهل البدع. 3- كونه يحرر أصول عقيدة الفرقة الناجية أهل السنة والجماعة التي كان عليها رسول الله - صلى الله عليه وسلم - وأصحابه. وقد اهتم العلماء بها حتى قال القاضي أبو يعلى - رحمه الله تعالى -: « لو رُحِلَ إلى الصين فـي طلبها لكان قليلاً ».',
'SÜNNƏNİN ƏSASLARI',
'İmam Əhməd İbn Hənbəlin “Sünnənin əsasları” adlı əsərinin özündə əks etdirən qaydalar, onun haqqında eşitmiş hər bir müsəlmanın tutması vacib olan qaydalardır. Bu əsaslar, doğru yol göstərən, dünya və axirətdə nəcat və firavanlıq əldə etmək üçün gözəl bir vasitədir, çünki burada bu ümmətin sələflərinin etiqadı toplanmışdır. İmam Malik, Allah ona rəhmət etsin, demişdir: “Bu ümmətin axırıncıları, ümmətin birincilərinin müvəffəqiyyət qazandıqları vasitələrdən fərqli bir vasitə ilə müvəffəqiyyət qazana bilməzlər”.',
'http://www.islamhouse.com/p/328714',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Sunnanin_asasları.pdf,http://d1.islamhouse.com/data/az/ih_books/single/az_Sunnanin_asasları.doc',
'',
'',
'',
''),

'20'=>array(
'20',
'Azərbaycanlı',
'كيف نفهم القرآن : أنواع التفسير وشرح بعض آيات القرآن',
'رسالة تبين أنواع تفسير القرآن مع تفسير بعض آيات القرآن.',
'Quranı Necə Anlamalı(Təfsirin Növləri və Bəzi Ayələrin Şərhi)',
'Bu dəyərli kitabda Quranı anlamağın yollarından söz açılır. Mövzusuna görə Azərbaycanda nəşr edilən ilk kitabdır. Qurani Kərimi anlamaq istəyən hər bir müsəlman qardaş və bacılarımıza bu kitabı oxumağı tövsiyə edirik. İbn Abbas (r) buyurmuşdur: Quranı öyrənib əməl edən insanın dünyada haqq yolundan azmaması və axirətdədə ziyana uğramamasına Uca Allah zəmanət vermişdir. Bu kitabı Azərbaycan dilinə tərcumə edən Fərahim qardaşımızdan Allah razı olsun və bu xeyr əməlini onun axirət dəftərinə yazsın. Amin',
'http://www.islamhouse.com/p/328708',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Quran_Neca_Anlamal.pdf',
'',
'',
'',
''),

'21'=>array(
'21',
'Azərbaycanlı',
'الأربعون النووية',
'الأربعون النووية هو : هو متن مشهور، اشتمل على اثنين وأربعين حديثاً محذوفة الإسناد في فنون مختلفة من العلم، كل حديث منها قاعدة عظيمة من قواعد الدين، وينبغي لكل راغب في الآخرة أن يعرف هذه الأحاديث؛ لما اشتملت عليه من المهمات، واحتوت عليه من التنبيه على جميع الطاعات؛ وقد سميت بالأربعين في مباني الإسلام وقواعد الأحكام.',
'İmam Nəvavinin 40 hədis kitabı',
'İmam Nəvavi adlı məşhur islam alimi müsəlmanın gündəlik həyatında əsas məsələləri əhatə edən 40 hədisi toplamışdır. Buna görə də kitab İmam Nəvavinin 40 hədis kitabı adı ilə tanınmışdır. Bu dəyərli əsəri sizin üçün təqdim edirik. Tərcümə edən Kamal Hüseyn qardaşımızdan da Allah razı olsun.',
'http://www.islamhouse.com/p/328705',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Imam_Navavinin_40_hadis_kitab.pdf',
'',
'',
'',
''),

'22'=>array(
'22',
'Azərbaycanlı',
'شرح العقيدة الطحاوية الميسر',
'شرح العقيدة الطحاوية الميسر : كتابٌ في شرح « العقيدة الطحاوية » التي ألَّفها الإمام أبو جعفر الطحاوي - رحمه الله -، وهو شرحٌ مُيسَّر يتحدَّث عن عقيدة أهل السنة والجماعة, ويتعرَّض إلى جميع أبواب العقيدة من الإيمان بالله, وأنواع التوحيد, وبيان الفرق المخالفة لمنهج أهل السنة والجماعة، واعتقاد أهل السنة في أصحاب النبي - صلى الله عليه وسلم -، وغير ذلك من أبواب العقيدة.',
'Tahavi Əqidəsinin Asanlaşdırılmış Şərhi',
'Tanınmış Hənəfi alimlərindən olmuş Əbu CəfərTahavinin bu dəyərli kitabını szin istifadəniz üçün təqdim edirik. Kitabda Allahın adları və sifətləri, iman, axirət və sairə mühim məsələlərdən söz açılır.',
'http://www.islamhouse.com/p/328697',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Tahavi_eqidasinin_Asanlasdırılmıs_sarhi.pdf',
'',
'',
'',
''),

'23'=>array(
'23',
'Azərbaycanlı',
'صلاة الجماعة',
'كتيب باللغة الأذرية بين فيه الكاتب أهمية صلاة الجماعة وحكمها.',
'Camaat namazı',
'-',
'http://www.islamhouse.com/p/307770',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Camaat_namazi.pdf,http://d1.islamhouse.com/data/az/ih_books/single/az_Camaat_namazi.doc',
'Ramil Soltanov',
'',
'',
''),

'24'=>array(
'24',
'Azərbaycanlı',
'منزلة الصلاة في الإسلام',
'كتيب باللغة الأذرية بين فيه الكاتب منزلة الصلاة في الإسلام.',
'Namazın İslamda yeri',
'-',
'http://www.islamhouse.com/p/307767',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Namazın_islamda_yeri.pdf,http://d1.islamhouse.com/data/az/ih_books/single/az_Namazın_islamda_yeri.doc',
'Ramil Soltanov',
'',
'',
''),

'25'=>array(
'25',
'Azərbaycanlı',
'الموت',
'-',
'Ölüm',
'-',
'http://www.islamhouse.com/p/307765',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Olume_qeder.doc',
'Ramil Soltanov',
'',
'',
''),

'26'=>array(
'26',
'Azərbaycanlı',
'محاسن الإسلام',
'هذا المجلد يحتوي على بيان بعض محاسن الدين الإسلامي.',
'İslamın Gözəllikləri',
'-',
'http://www.islamhouse.com/p/265460',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Islamin_gozalliklari.pdf',
'',
'',
'',
''),

'27'=>array(
'27',
'Azərbaycanlı',
'60 سؤالاً في أحكام الحيض والنفاس',
'ستون سؤالاً في أحكام الحيض : قال المصنف - رحمه الله - « الحمد لله، والصلاة والسلام على رسول الله محمد بن عبدالله وآله وصحبه ومن سار على دربه إلى يوم الدين ‏.‏‏.‏ وبعد أختي المسلمة‏:‏ نظرًا لكثرة التساؤلات التي ترد على العلماء بشأن أحكام الحيض في العبادات رأينا أن نجمع الأسئلة التي تتكرر دائمًا وكثيرًا ما تقع دون التوسع وذلك رغبة في الاختصار‏.‏ أختي المسلمة‏:‏ حرصنا على جمعها لتكون في متناول يدك دائمًا وذلك لأهمية الفقه في شرع الله ولكي تعبدين الله على علم وبصيرة‏.‏ تنبيه‏:‏ قد يبدو لمن يتصفح الكتاب لأول مرة أن بعض الأسئلة متكررة ولكن بعد التأمل سوف يجد أن هناك زيادة علم في إجابة دون الأخرى‏.‏ رأينا عدم إغفالها‏.‏ هذا وصلى الله وسلم على نبينا محمد وآله وصحبه أجمعين‏ ».',
'Qadınlarla əlaqəli 60 sual [ Heyz və nifasa dair 60 sual ]',
'-',
'http://www.islamhouse.com/p/265457',
'http://d1.islamhouse.com/data/az/ih_books/single/az_qustaion_about_natural_blood_of_woman.pdf,http://d1.islamhouse.com/data/az/ih_books/single/az_qustaion_about_natural_blood_of_woman.doc',
'',
'',
'',
''),

'28'=>array(
'28',
'Azərbaycanlı',
'حصن المسلم من أذكار الكتاب والسنة',
'حصن المسلم : كتيب مبارك احتوى على جل ما يحتاجه المسلم من الأدعية والأذكار في يومه وليله، وما يحزبه له من أمور عارضة في شؤون حياته؛ وتم ترجمته إلى أكثر من ثلاثين لغة عالمية، وفي هذه الصفحة ترجمته إلى اللغة الأذرية.',
'Müsəlmanın qalası',
'Qur’an və Peyğəmbərimizin şəriətində müsəlmanların sığınacağı DUA VƏ ZIKRLƏR Bu mənim «Zikr, dua və Qurandan və Sünnədən istifadə etməklə ovsunla müalicə» adlı kitabı¬mın müxtəsəridir. Həmin kitabın «Zikrlər» his¬səsi ilə kifayətlənməyib qalanını ixtisar etdim ki, səfər zamanı özü ilə gəzdirmək asan olsun. Səid ibn Əli ibn Vəhf əl-Qahtani',
'http://www.islamhouse.com/p/43365',
'http://d1.islamhouse.com/data/az/ih_books/parts/Musalmanin_qalas/az_Musalmanin_qalas1.pdf,http://d1.islamhouse.com/data/az/ih_books/parts/Musalmanin_qalas/az_Musalmanin_qalas2.doc,http://d1.islamhouse.com/data/az/ih_books/parts/Musalmanin_qalas/az_Musalmanin_qalas2.pdf',
'',
'',
'',
''),

'29'=>array(
'29',
'Azərbaycanlı',
'الفاتحة وجزء عم وترجمة معانيهما إلى اللغة الأذرية',
'',
'əl-Fatihə surəsi və cüz Əmmənin Azərbaycan dilinə tərcüməsi',
'əl-Fatihə surəsi və cüz Əmmənin Azərbaycan dilinə tərcüməsi',
'http://www.islamhouse.com/p/15',
'http://d1.islamhouse.com/data/az/ih_books/single/az_Fatiha_va_amma_cuzun_manaca_tarcumasi.pdf',
'',
'',
'',
'Məlik Fəhd adınaQuran çapı mərkəzi')

);
?>