<?php
$BOOKS = array(
'1'=>array(
'1',
'Hausa',
'نواقض الإسلام',
'في هذه الصفحة رسالة نواقض الإسلام للإمام المجدد محمد بن عبد الوهاب - رحمه الله -. وهي بعض النواقض التي عدها الشيخ ونص على إجماع أهل العلم عن اعتبارها هادمة للإسلام وناقضة له.',
'ABUBUWAN DA SUKE WARW ARE MUSULUNCI',
'-',
'http://www.islamhouse.com/p/339832',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Contradictions_To_Islam.pdf',
'محمد بن عبد الوهاب',
'',
'',
''),

'2'=>array(
'2',
'Hausa',
'عقيدة أهل السنة والجماعة',
'تشتمل هذه الرسالة على بيان عقيدة أهل السنة والجماعة في باب توحيد الله وأسمائه وصفاته، وفي أبواب الإِيمان بالملائكة، والكتب، والرسل، واليوم الآخر، والقدَر خيره وشره.',
'Akidar Ahlus~Sunna',
'-',
'http://www.islamhouse.com/p/339830',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Akidar_Ahlus_Sunna.pdf',
'',
'',
'',
''),

'3'=>array(
'3',
'Hausa',
'كشف الشبهات في التوحيد',
'رسالة نفيسة كتبها الإمام المجدد محمد بن عبد الوهاب - رحمه الله - وهي عبارة عن سلسلة شبهات للمشركين وتفنيدها وإبطالها، وفيها بيان توحيد العبادة وتوحيد الألوهية الذي هو حق الله على العباد، وفيها بيان الفرق بين توحيد الربوبية وتوحيد الإلهية والعبادة، وفي هذه الصفحة ترجمة لها بلغة الهوسا.',
'Kawar Da Shubha',
'-',
'http://www.islamhouse.com/p/339828',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Kawar_Da_Shubha.pdf',
'محمد بن عبد الوهاب',
'',
'',
''),

'4'=>array(
'4',
'Hausa',
'من عقائد الشيعة',
'من عقائد الشيعة : هذه الرسالة تبين بعض معتقدات الشيعة على طريقة السؤال والجواب بصورة مختصرة.',
'Aqidun Shi\'a a Sauqaqe',
'-',
'http://www.islamhouse.com/p/322553',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Aqidun_Shia_Sauqaqe.pdf',
'',
'',
'',
''),

'5'=>array(
'5',
'Hausa',
'صفة الحج والعمرة مع أدعية مختارة',
'ما من عبادة إلا ولها صفة وكيفية، قد تكفل الله سبحانه ببيانها، أو بينها رسوله - صلى الله عليه وسلم -، وقد حج النبي - صلى الله عليه وسلم - بعد هجرته إلى المدينة حجة واحدة، وهي التي سميت بـحجة الوداع؛ لأنه ودع فيها الناس، وفي هذه الحجة بين النبي صلى الله عليه وسلم للأمة مناسك الحج، فقال - صلى الله عليه وسلم - { خذوا عنّي مناسككم }، وفي هذا الكتاب بيان لصفة الحج، وقد طبع من طرف الرئاسة العامة لشؤون المسجد الحرام والمسجد النبوي.',
'SIFAR HAJJI DA UMRA',
'-',
'http://www.islamhouse.com/p/315025',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Description_of_Hajj_and_Umrah_and_d3a.pdf',
'',
'',
'',
''),

'6'=>array(
'6',
'Hausa',
'أين الله؟',
'هذا الكتاب بلغة الهوسا يجيب عن سؤال أين الله عز وجل؟ فقد وجدنا كثيراً من الناس بل من طلاب العلم وطلاب المعاهد يتناقشون في هذا الأمر وهو أين الله عز وجل؟ فمنهم من ينكر هذا السؤال برمته ويقول لك لا يجوز أن تسأل هذا السؤال، ومنهم من يقول لا أعرف أوقد حرت فيه وتهت فيه, ومنهم من يجيبك بأن الله في كل مكان - وهذا ما سمعه من مشايخه -، ومنهم من يقول لك أن الله في السماء تبارك وتعالى. وإليك الجواب الشافي في هذه القضية الذي يبعدك عن الشك والحيرة والوقوع في الغلط متمثلاً ذلك بكتاب الله وسنة نبيه محمد - صلى الله عليه وسلم - ونهج السلف الصالح.',
'INA ALLAH YA KE?',
'INA ALLAH YA KE? (Nazari Akan Daukakar Allah Bisa Al’arshi A Ra’ayin Magabata Da Na Bayansu)',
'http://www.islamhouse.com/p/259886',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_ina_Allah_ya_ke.pdf,http://d1.islamhouse.com/data/ha/ih_books/single/ha_ina_Allah_ya_ke.doc',
'',
'',
'',
''),

'7'=>array(
'7',
'Hausa',
'تفسير العشر الأخير من القرآن الكريم ويليه أحكام تهم المسلم',
'تفسير العشر الأخير من القرآن الكريم ويليه أحكام تهم المسلم : كتاب مختصر يحوي أهم ما يحتاجه المسلم في حياته من قرآن وتفسير وأحكام فقهية وعقدية وفضائل و غيرها، والكتاب ينقسم إلى جزئين: فأما الجزء الأول فيشتمل على الأجزاء الثلاثة الأخيرة من القرآن الكريم مع تفسيرها من كتاب زبدة التفسير للشيخ محمد الأشقر. وأما الجزء الثاني فيحتوي على أحكام تهم المسلم، وهي: أحكام التجويد، 62 سؤالا في العقيدة، حوار هادئ عن التوحيد، أحكام الاسلام [ الشهادتان، الطهارة، الصلاة، الزكاة، الحج ]، فوائد متفرقة، الرقية، الدعاء، الأذكار، 100 فضيلة و 70 منهيًا، صفة الوضوء والصلاة مصورة، رحلة الخلود.',
'TAFSIRIN USHURIN KARSHE NA AL KURANI MAI GIRMA',
'-',
'http://www.islamhouse.com/p/250950',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Explanation_of_the_Last_Tenth_of_the_Quran.pdf',
'',
'',
'',
''),

'8'=>array(
'8',
'Hausa',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة : التحليل العادل والجواب الشافي عن الأسئلة التالية: هل اليهودية والمسيحية والإسلام يشتركون في نفس العقائد الخاصة بالمرأة؟ هل حقاً اليهودية والمسيحية أكرموا المرأة أكثر من الإسلام؟ ما الحقيقة؟',
'Matsayin Mata A Musulunci, Yahudanci da Nasaranci',
'-',
'http://www.islamhouse.com/p/191549',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Matsayin_Mata_A_Musulunci_Yahudanci_da_Nasaranci.pdf',
'',
'',
'',
''),

'9'=>array(
'9',
'Hausa',
'مختصر منهاج السنة لشيخ الإسلام ابن تيمية',
'مختصر منهاج السنة لشيخ الإسلام ابن تيمية : هذا الكتاب - منهاج السنة النبوية في نقض دعاوى الرافضة والقدرية - من أعظم كتب الإمام المجاهد شيخ الإسلام أحمد بن عبد الحليم بن تيمية - رحمه الله -، قد رد فيه على شبه الرافضة، وبين فيه بطلان مذهبهم، وشباب الاسلام اليوم بأمس الحاجة إلى قراءة هذا الكتاب، ومعرفة محتواه؛ حيث أطل الرفض على كل بلد من بلاد الإسلام، وغيرها بوجهه الكريه، وكشر عن أنيابه الكالحة، وألقى حبائله أمام من لا يعرف حقيقته، مظهرا غير مبطن ديدن كل منافق مفسد ختال؛ فاغتر به من يجهل حقيقته، ممن لم يقرأ مثل هذا الكتاب. ولما كان كتاب منهاج السنة مشتملا على مباحث مطولة، وغير مطولة في الرد على القدرية والمتكلمين وغيرهم من سائر الطوائف، قام الشيخ عبد الله الغنيمان - حفظه الله - باختصاره والاقتصار على ما يخص الرافضة من الرد عليهم فيما يتعلق بالخلافة والصحابة وأمهات المؤمنين وغير ذلك؛ حتى يسهل على عموم المسلمين الانتفاع به.',
'TAFARKIN SUNNAH',
'TAFARKIN SUNNAH tattaunawa ta ruwan sanyi tsakanin ibnu taimiyyah da ‘yan shi’ar zamaninsa',
'http://www.islamhouse.com/p/172222',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Tafarkin_Sunnah.pdf,http://d1.islamhouse.com/data/ha/ih_books/single/ha_Tafarkin_Sunnah.doc',
'',
'',
'',
''),

'10'=>array(
'10',
'Hausa',
'رسائل للحجاج والمعتمرين',
'رسائل للحجاج والمعتمرين: تحتوي هذه الرسالة على بعض الوصايا المهمة والتي ينبغي على كل حاج معرفتها.',
'SAKO ZUWA GA ALHAZAI DA \'YAN UMRA',
'-',
'http://www.islamhouse.com/p/156358',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Messages_to_The_Performers_of_Hajj_and_Umra.pdf,http://d1.islamhouse.com/data/ha/ih_books/single/ha_Messages_to_The_Performers_of_Hajj_and_Umra.doc',
'',
'',
'',
''),

'11'=>array(
'11',
'Hausa',
'دراسة تحليلية لأحداث ما بعد الرسول صلى الله عليه وسلم إلى موقعة كربلاء',
'-',
'QADDARA TA RIGA FATA',
'-',
'http://www.islamhouse.com/p/156356',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Kaddara_Tariga_Fata.pdf,http://d1.islamhouse.com/data/ha/ih_books/single/ha_Kaddara_Tariga_Fata.doc',
'',
'',
'',
''),

'12'=>array(
'12',
'Hausa',
'سبعون سؤالا لا جواب عليها [ أسئلة موجهة للشيعة ]',
'-',
'Qalubale Ga ‘Yan Shi’ah: TAMBAYOYI 70 Waxanda Ba Su Da Amsa',
'-',
'http://www.islamhouse.com/p/156354',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Questions_addressed_to_the_Shiites.pdf,http://d1.islamhouse.com/data/ha/ih_books/single/ha_Questions_addressed_to_the_Shiites.doc',
'',
'',
'',
''),

'13'=>array(
'13',
'Hausa',
'من هم أحباب أهل البيت؟',
'-',
'SU WANE NE MASOYAN AHLUL BAITI ?',
'SU WANE NE MASOYAN AHLUL BAITI ?',
'http://www.islamhouse.com/p/156352',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Su_Wane_Ne_Masoyan_Ahlulbaiti.pdf,http://d1.islamhouse.com/data/ha/ih_books/single/ha_Su_Wane_Ne_Masoyan_Ahlulbaiti.doc',
'',
'',
'',
''),

'14'=>array(
'14',
'Hausa',
'صحبة رسول الله صلى الله عليه وسلم',
'-',
'KYAKKYAWAR SAFIYA',
'-',
'http://www.islamhouse.com/p/156350',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Kyakkyawar_Safiya.pdf,http://d1.islamhouse.com/data/ha/ih_books/single/ha_Kyakkyawar_Safiya.doc',
'',
'',
'',
''),

'15'=>array(
'15',
'Hausa',
'نَجِيُّ كربلاء',
'يقول الشيخ: ولما كانت فاطمة - عليها السلام - بنت رسول الله - صلى الله عليه وسلم - أحب بناته إليه، وكان ولداها الحسن والحسين - عليهما السلام - ريحانتيه في الدنيا؛ أحببت أن أقدم أنموذجاً من ذريتها ومن صلب ابنها الحسين - عليه السلام - ليكون نوراً نستضيء بسيرته في زمن التبس فيه الحق بالباطل، وأصبح الكل يدعي الوصال بالحق والحق منه بريء وعن مناله بعيد. فوقع الاختيار على سيدنا الإمام العابد الجواد القانت الأواب زين العابدين علي الأصغر بن الحسين بن علي - عليهم السلام -. وإنني إذ أقدم للإخوة القراء ترجمة لهذا الإمام لما رأيت في سيرته من النسب الجليل، والفكر الأصليل، والنظر الثاقب، والعلم النافع، والعبادة الصالحة، والروح الرائعة، وهذه أوصاف متولدة في شخصه عن حقائق عارية عن كل تزويغ أو تلميع، والواقع أقوى برهان وأدق ميزان، وقد سميت هذه الترجمة "نَجِيُّ كربلاء").',
'Mai Rabon Ganin Baxi',
'Mai Rabon Ganin Baxi',
'http://www.islamhouse.com/p/156345',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Mai_Rabon_Ganin_Badi.pdf,http://d1.islamhouse.com/data/ha/ih_books/single/ha_Mai_Rabon_Ganin_Badi.doc',
'',
'',
'',
''),

'16'=>array(
'16',
'Hausa',
'محرمات استهان بها كثير من الناس',
'محرمات استهان بها كثير من الناس : في هذه الرسالة يجد القارئ الكريم عدداً من المحرمات التي ثبت تحريمها في الشريعة مع بيان أدلة التحريم من الكتاب والسنة، وهذه المحظورات مما شاع فعلها وعم ارتكابها بين كثير من المسلمين، والله المستعان.',
'GYARA KAYANKA YI HATTARA DA',
'-',
'http://www.islamhouse.com/p/156338',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Gyara_kayanka_yi_hattara_da.pdf,http://d1.islamhouse.com/data/ha/ih_books/single/ha_Gyara_kayanka_yi_hattara_da.doc',
'',
'',
'',
''),

'17'=>array(
'17',
'Hausa',
'أحوال النبي صلى الله عليه وسلم في الحج',
'هذا الكتاب عبارة عن دراسة تحاول إعطاء توصيف شامل وصورة أوضح عن أحواله - صلى الله عليه وسلم - في الحج، وقد تكونت من ثلاثة فصول: الأول: أحوال النبي صلى الله عليه وسلم في الحج مع ربه. الثاني: أحوال النبي صلى الله عليه وسلم في الحج مع أمته. الثالث: أحوال النبي صلى الله عليه وسلم في الحج مع أهله.',
'Rayuwar Annabi Sallallahu Alaihi Wasallama A Lokacin Aikin Hajji',
'-',
'http://www.islamhouse.com/p/156193',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Rayuwar_Annabi_Sallallahu_Alaihi_Wasallama_A_Lokacin_Aikin_Hajji.pdf,http://d1.islamhouse.com/data/ha/ih_books/single/ha_Rayuwar_Annabi_Sallallahu_Alaihi_Wasallama_A_Lokacin_Aikin_Hajji.doc',
'',
'',
'',
''),

'18'=>array(
'18',
'Hausa',
'رحماء بينهم [ التراحم بين آل بيت النبي صلى الله عليه وسلم والصحابة رضي الله عنهم ]',
'رحماء بينهم التراحم بين آل بيت النبي صلى الله عليه وسلم والصحابة رضي الله عنهم: إن البحث عن أسباب الافتراق في الأمة وعلاجها مطلبٌ شرعي، و هي قضية كُبرى، ولها آثارها التي عصفت بالأمة، و سيقتصر البحث عن الرحمة بين أصحاب النبي - صلى الله عليه وآله وسلم - من آل البيت - عليهم السلام - وسائر الناس، فمع ما جرى بينهم من حروب إلا أنهم رحماء بينهم، و هذه حقيقة وإن تجاهلها القصاصون، وسكت عنها رواة الأخبار، فستبقى تلك الحقيقة ناصعة بيضاء تردّ على أكثر أصحاب الأخبار أساطيرهم وخيالاتهم، التي استغلها أصحاب الأهواء والأطماع السياسية، والأعداءُ لتحقيق مصالحهم وتأصيل الافتراق والاختلاف في هذه الأمة.',
'ALAKA TSAKANIN AHLUL - BAITI DA SAHABBAI',
'-',
'http://www.islamhouse.com/p/104600',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_alaka_tsakanin_Ahlul_Baiti.pdf,http://d1.islamhouse.com/data/ha/ih_books/single/ha_alaka_tsakanin_Ahlul_Baiti.doc',
'',
'',
'',
''),

'19'=>array(
'19',
'Hausa',
'القرآن الكريم وترجمة معانيه إلى لغة الهوسا',
'',
'ALKUR\'ANI MAI GIRMA Da Kuma Tarjaman Ma\'anõninsa Zuwa Ga Harshen HAUSA',
'-',
'http://www.islamhouse.com/p/597',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Translation_of_the_Meaning_of_the_Holy_Quran_in_Hausa.pdf',
'',
'Abubakar Mahmud Gummi',
'Malam Inuwa Diko',
'Wuri Da Aka Tanada Musamman Don Buga AlRur\'ani Mai Girma Na Mai Kula Da Masallatai Biyu Masu Tsarki Sarki Fahad'),

'20'=>array(
'20',
'Hausa',
'أركان الإيمان',
'أركان الإيمان: هذه الدراسة عن أركان الإيمان هي أحد برامج العمادة العلمية، حيث وجّهت بعض أعضاء هيئة التدريس بالجامعة للكتابة في الموضوع ثمّ كلّفت اللجنة العلمية بالعمادة بدراسة ما كتبوه واستكمال النقص وإخراجه بالصورة المناسبة، مع الحرص على ربط القضايا العلمية بأدلّتها من الكتاب والسنّة. وتحرص العمادة - من خلال هذه الدراسة - إلى تمكين أبناء العالم الإسلامي من الحصول على العلوم الدينية النافعة؛ لذلك قامت بترجمتها إلى اللغات العالمية ونشرها وتضمينها شبكة المعلومات الدولية - الإنترنت -.',
'RUKUNAN IMANI',
'-',
'http://www.islamhouse.com/p/593',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_Rukun_Iman.pdf,http://d1.islamhouse.com/data/ha/ih_books/single/ha_Rukun_Iman.doc',
'عمادة البحث العلمي بالجامعة الإسلامية',
'',
'',
'موقع الجامعة الإسلامية بالمدينة المنورة'),

'21'=>array(
'21',
'Hausa',
'أركان الإسلام',
'أركان الإسلام: هذه الدراسة عن أركان الإسلام هي أحد برامج العمادة العلمية، حيث وجّهت بعض أعضاء هيئة التدريس بالجامعة للكتابة في الموضوع ثمّ كلّفت اللجنة العلمية بالعمادة بدراسة ما كتبوه واستكمال النقص وإخراجه بالصورة المناسبة، مع الحرص على ربط القضايا العلمية بأدلّتها من الكتاب والسنّة. وتحرص العمادة - من خلال هذه الدراسة - إلى تمكين أبناء العالم الإسلامي من الحصول على العلوم الدينية النافعة؛ لذلك قامت بترجمتها إلى اللغات العالمية ونشرها وتضمينها شبكة المعلومات الدولية - الإنترنت -.',
'RUKUNAN MUSULUNCI',
'-',
'http://www.islamhouse.com/p/591',
'http://d1.islamhouse.com/data/ha/ih_books/single/ha_rukunan_musulunci.pdf,http://d1.islamhouse.com/data/ha/ih_books/single/ha_rukunan_musulunci.doc',
'عمادة البحث العلمي بالجامعة الإسلامية',
'',
'',
'موقع الجامعة الإسلامية بالمدينة المنورة'),

'22'=>array(
'22',
'Hausa',
'ثلاثة الأصول وأدلتها',
'ثلاثة الأصول : رسالة مختصرة ونفيسة تحتوي على الأصول الواجب على الإنسان معرفتها من معرفة العبد ربه, وأنواع العبادة التي أمر الله بها، ومعرفة العبد دينه، ومراتب الدين، وأركان كل مرتبة، ومعرفة النبي - صلى الله عليه وسلم - في نبذة من حياته، والحكمة من بعثته، والإيمان بالبعث والنشور، وركنا التوحيد وهما الكفر بالطاغوت,والإيمان بالله.',
'TUSHE UKU NA MUSULUNCI',
'-',
'http://www.islamhouse.com/p/589',
'http://d1.islamhouse.com/data/ha/ih_books/parts/Tushe_Uku_Na_Musulunci/ha_01_Tushe_Uku_Na_Musulunci.pdf,http://d1.islamhouse.com/data/ha/ih_books/parts/Tushe_Uku_Na_Musulunci/ha_02_Tushe_Uku_Na_Musulunci.pdf,http://d1.islamhouse.com/data/ha/ih_books/parts/Tushe_Uku_Na_Musulunci/ha_02_Tushe_Uku_Na_Musulunci.doc',
'محمد بن عبد الوهاب',
'',
'',
'')

);
?>