<?php
$BOOKS = array(
'1'=>array(
'1',
'Italiano',
'عقيدة أهل السنة والجماعة',
'عقيدة أهل السنة والجماعة: تشتمل هذه الرسالة على بيان عقيدة أهل السنة والجماعة في باب توحيد الله وأسمائه وصفاته، وفي أبواب الإِيمان بالملائكة، والكتب، والرسل، واليوم الآخر، والقدَر خيره وشره، وفي هذه الصفحة ترجمة إيطالية للرسالة.',
'La Dottrina della Gente che segue la Sunnah e il Consenso [ Aqidatu Ahlu-s-Sunnah wa-l-Jama’ah ]',
'-',
'http://www.islamhouse.com/p/337501',
'http://d1.islamhouse.com/data/it/ih_books/single/it_aqidatu_ahlu_s_sunnah_wa_l_jamaah.pdf',
'',
'',
'',
''),

'2'=>array(
'2',
'Italiano',
'العقيدة الواسطية',
'العقيدة الواسطية: رسالة نفيسة لشيخ الإسلام ابن تيمية - رحمه الله - ذكر فيها جمهور مسائل أصول الدين، ومنهج أهل السنة والجماعة في مصادر التلقي التي يعتمدون عليها في العقائد؛ لذا احتلت مكانة كبيرة بين علماء أهل السنة وطلبة العلم، لما لها من مميزات عدة من حيث اختصار ألفاظها ودقة معانيها وسهولة أسلوبها، وأيضاً ما تميزت به من جمع أدلة أصول الدين العقلية والنقلية، وفي هذه الصفحة ترجمة إيطالية لها.',
'Al-’Aqidah al-Wasitiyyah',
'-',
'http://www.islamhouse.com/p/337493',
'http://d1.islamhouse.com/data/it/ih_books/single/it_aqidah_wasitiyyah.pdf',
'',
'',
'',
''),

'3'=>array(
'3',
'Italiano',
'ثلاثة الأصول وأدلتها',
'ثلاثة الأصول وأدلتها: رسالة مختصرة ونفيسة صنفها الإمام المجدد محمد بن عبد الوهاب - رحمه الله - تحتوي على الأصول الواجب على الإنسان معرفتها من معرفة العبد ربه, وأنواع العبادة التي أمر الله بها، ومعرفة العبد دينه، ومراتب الدين، وأركان كل مرتبة، ومعرفة النبي - صلى الله عليه وسلم - في نبذة من حياته، والحكمة من بعثته، والإيمان بالبعث والنشور، وركنا التوحيد وهما الكفر بالطاغوت,والإيمان بالله.',
'I tre principi e le loro prove',
'-',
'http://www.islamhouse.com/p/334273',
'http://d1.islamhouse.com/data/it/ih_books/single/it_I_tre_principi_e_le_loro_prove.pdf',
'',
'',
'',
''),

'4'=>array(
'4',
'Italiano',
'معنى الشهادتين - للأطفال',
'معنى الشهادتين: رسالةٌ مُصورةٌ تُوضِّح معنى شهادة التوحيد: لا إله إلا الله، محمد رسول الله - صلى الله عليه وسلم - للأطفال بطريقة سهلة مُبسَّطة.',
'le due testimonianze della fede',
'-',
'http://www.islamhouse.com/p/319860',
'http://d1.islamhouse.com/data/it/ih_books/single/it_le_due_testimonianze_della_fede.pdf',
'',
'',
'',
''),

'5'=>array(
'5',
'Italiano',
'هذا هو محمد صلى الله عليه وسلم',
'هذا الكتاب يحتوي على تعريف بالنبي صلى الله عليه وسلم.',
'Questo e Mohammad Pace e benedizioni su di lui',
'-',
'http://www.islamhouse.com/p/312016',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Questo_e_Mohammad.pdf',
'',
'',
'',
''),

'6'=>array(
'6',
'Italiano',
'محمد الخليفة الطبيعي للمسيح',
'محمد الخليفة الطبيعي للمسيح: { وَإِذْ قَالَ عِيسَى ابْنُ مَرْيَمَ يَا بَنِي إِسْرَائِيلَ إِنِّي رَسُولُ اللَّهِ إِلَيْكُمْ مُصَدِّقًا لِمَا بَيْنَ يَدَيَّ مِنَ التَّوْرَاةِ وَمُبَشِّرًا بِرَسُولٍ يَأْتِي مِنْ بَعْدِي اسْمُهُ أَحْمَدُ } [سورة الصف: 6] هذه الآية الكريمة تؤيدها شواهد كثيرة من الكتب المقدسة عند النصارى، لكن أين من يتدبر ويبحث؟',
'Muhammad il naturale successore di Cristo',
'-',
'http://www.islamhouse.com/p/312014',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Muhammad_il_naturale_successore_di_Cristo.pdf',
'',
'',
'',
''),

'7'=>array(
'7',
'Italiano',
'ماذا قالوا عن الإسلام؟',
'رسالة مختصرة تحتوي على أقوال بعض المشاهير حول دين الإسلام.',
'Cosa Dicono Dell Islam',
'-',
'http://www.islamhouse.com/p/312012',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Cosa_Dicono_Dell_Islam.pdf',
'',
'',
'',
''),

'8'=>array(
'8',
'Italiano',
'حوار بين مسلم ونصراني',
'حوار بين مسلم ونصراني: يشتمل هذا الكتاب على خلاصة حوارات متتالية دارت بين المؤلّف وعدد من رجال الدين المسيحي، اتسمت بالموضوعية والأدب الجم، والحرص على تجنب المساس بالمشاعر الدينية، والالتزام بالمنهج العلمي للحوار، على هيئة سؤال وجواب، ليعالج ثمانية قضايا أساسية هي: • هل كان أبراهيم يهوديا أو نصرانيا؟ • كلام الله أم كلام البشر؟ • توحيد أم تثليث؟ • هل المسيح بشر أم إله؟ • هل المسيح ابن الله؟ • هل صُلب المسيح ثم قام؟ • دعوى الخطيئة الأولى والفداء. • محمد صلى الله عليه وسلم رسول الله في الكتاب المقدس.',
'Dialogo tra un musulmano e un cristiano',
'-',
'http://www.islamhouse.com/p/312010',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Dialogo_tra_un_musulmano_e_un_cristiano.pdf',
'',
'',
'',
''),

'9'=>array(
'9',
'Italiano',
'القرآن والعلم الحديث.. توافق أم تعارض؟',
'-',
'Il Corano e la scienza moderna compatibile o incompatibile?',
'-',
'http://www.islamhouse.com/p/312006',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Corano_e_la_Scienza_Moderna.pdf',
'',
'',
'',
''),

'10'=>array(
'10',
'Italiano',
'رسالة واحدة فقط!',
'رسالة واحدة فقط! : يتكلم هذا الكتاب عن رسالة التوحيد الواحدة التي حملها جميع الأنبياء والرسل من لدن آدم - عليه السلام - إلى نبينا محمد - صلى الله عليه وسلم -. ويمتاز .. بإثبات توحيد ( وحدانية ) الله من كتب اليهود والنصارى ( العهد القديم والعهد الجديد ) التي بين أيديهم في وقتنا المعاصر.',
'Un Solo Messaggio!',
'-',
'http://www.islamhouse.com/p/292778',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Un_Solo_Messaggio.pdf,http://d1.islamhouse.com/data/it/ih_books/single/it_Un_Solo_Messaggio.doc',
'',
'',
'',
''),

'11'=>array(
'11',
'Italiano',
'رياض الصالحين [ الجزء الأول ]',
'كتاب رياض الصالحين للإمام المحدث الفقيه أبي زكريا يحيى بن شرف النووي المتوفى سنة 676هـ - رحمه الله - من الكتب المهمة، وهو من أكثر الكتب انتشاراً في العالم؛ وذلك لاشتماله على أهم ما يحتاجه المسلم في عباداته وحياته اليومية مع صحة أحاديثه - إلا نزراً يسيراً - واختصاره وسهولته وتذليل المصنف لمادته، وهو كتاب ينتفع به المبتديء والمنتهي.',
'Riyâd as-Sâlihîn [ Parte I ]',
'-',
'http://www.islamhouse.com/p/259971',
'http://d1.islamhouse.com/data/it/ih_books/parts/Riyad_AlSaliheen/it_01_Riyad_AlSaliheen.pdf',
'',
'',
'',
''),

'12'=>array(
'12',
'Italiano',
'أنت تسأل والقرآن يجيب',
'أنت تسأل والقرآن يجيب : رسالة لطيفة تحتوي على 32 سؤال أجاب عنها الكاتب من خلال آيات القرآن الكريم. 1- من هو الخالق؟ 2- من هو الله؟ 3- هل تعتقد أن الله خلقنا عبثاً بدون أي هدف؟ 4- لماذا خلق الله الخلق؟ 5- ماذا أمرنا الله أن نفعل؟ 6- من أين نطلب الرشد؟ 7- لمن نلجأ في وقت المحن والمصائب؟ 8- هل حفظ الله القرآن من التحريف؟ 9- ماذا حصل للأمم السابقة عندما عصوا الله؟ 10- لمن تجب العبادة؟ 11- ماهو دين الله؟ 12- ماهو الدين الذي ارتضاه الله لنا وابتغاه؟ 13- من أين أتى (أنزل) القرآن؟ 14- لماذا أرسل الله الرسل؟ 15- هل يجب علينا الإيمان بالرسل؟ 16- ماذا حصل للكتب السابقة؟ 17- من هو آخر الرسل؟ 18- لمن أرسل الله آخر الرسل(محمد صلى الله عليه وسلم)؟ 19- ماذا أعد الله للمؤمنين من اليهود والنصارى؟ 20- ماهو مثل عيسى عند الله؟ 21- ماذا قال الله عن مريم؟ 22- هل صلب عيسى عليه السلام؟ 23- هل عيسى ابن الله؟ 24- كيف يتحقق لنا الأمن؟ 25- ماهي الحياة الدنيا؟ 26- هل النعم التي ننعم بها من الله؟ 27- ما الذي يزيد لنا النعمه من الله؟ 28- كيف تقي نفسك من العذاب الأليم؟ 29- ماهو جزاء من اتقى بالله؟ 30- ما هو مصير المكذبين؟ 31- ماهو مصير المؤمنين؟ 32- كيف تتحقق لنا السعادة؟.',
'Tu chiedi e il Corano risponde',
'-',
'http://www.islamhouse.com/p/259967',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Tu_chiedi_e_il_Corano_risponde.pdf,http://d1.islamhouse.com/data/it/ih_books/single/it_Tu_chiedi_e_il_Corano_risponde.doc',
'',
'',
'',
''),

'13'=>array(
'13',
'Italiano',
'كيف تدخل الإسلام؟',
'كتاب يبين معنى الإسلام، وأن التوحيد دين الرسل، ويبين كيفية الدخول فيه، وفيه تفسير لسورة الفاتحة وسوة العصر وسورة الفلق وسورة الناس، وآية الكرسي.',
'Come diventi musulmano ?',
'-',
'http://www.islamhouse.com/p/257582',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Come_diventi_musulmano.pdf',
'',
'',
'',
''),

'14'=>array(
'14',
'Italiano',
'رسالة الإسلام',
'هذا الكتاب يوضح عقيدة الإسلام التي دعا إليها جميع الرسل عليهم السلام، ويبين لغير المسلمين كيفية الدخول في الإسلام...',
'Il messaggio dell\'islam',
'Il messaggio dell\'islam',
'http://www.islamhouse.com/p/255860',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Il_messaggio_dell_islam.pdf,http://d1.islamhouse.com/data/it/ih_books/single/it_Il_messaggio_dell_islam.doc',
'',
'',
'',
''),

'15'=>array(
'15',
'Italiano',
'الهدف من الحياة',
'محاضرة رائعة وممتعة ألقاها الشيخ خالد ياسين في المملكة العربية السعودية عام 1994 م، وأسفرت عن إسلام 43 شخصا في تلك الليلة، وقد تم تفريغها وترجمتها إلى اللغة الإيطالية.',
'Qual è il fine della nostra vita?',
'• Perché siamo stati creati? • Perché dobbiamo morire? • Dove andremo dopo la morte? • Che cosa ci accaderà? • Perché Dio ha creato la terra e tutto ciò che è sotto il dominio dell\'uomo? • Perché sono stati creati il giorno e la notte, il sole e la luna? • Cosa dobbiamo fare in questa vita? • Siamo stati creati solo per mangiare, bere e divertirci? Attraverso questo libro potremmo scoprire una nuova dimensione di noi, esseri umani, all\'interno di questo universo!',
'http://www.islamhouse.com/p/255858',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Qual_e_il_fine_della_nostra_vita.pdf,http://d1.islamhouse.com/data/it/ih_books/single/it_Qual_e_il_fine_della_nostra_vita.doc',
'',
'',
'',
''),

'16'=>array(
'16',
'Italiano',
'مبادئ الإسلام',
'مبادئ الإسلام : في هذه الرسالة قام المؤلف بشرح ماهية الأديان وما ترمي إليه من خدمة للبشر، متحدثا عن النبوة التي ختمت بمحمد - صلى الله عليه وسلم - مثبتاً أن الدين عند الله الإسلام وأنه الشريعة العالمية الصالحة لبني آدم على مد الدهور.',
'Conoscere l’islàm',
'-',
'http://www.islamhouse.com/p/228864',
'http://d1.islamhouse.com/data/it/ih_books/single/it_principles_of_islam.pdf,http://d1.islamhouse.com/data/it/ih_books/single/it_principles_of_islam.doc',
'',
'',
'',
''),

'17'=>array(
'17',
'Italiano',
'حقوق الإنسان في الإسلام والتصورات الخاطئة الشائعة',
'حقوق الإنسان في الإسلام والتصورات الخاطئة الشائعة : في هذا الكتاب ناقش المؤلف موضوع حقوق الإنسان في ضوء المصدرين الأساسيين للمسلمين و هما القرآن و السنة.',
'Pregiudizi correnti sui diritti dell\'uomo nell\'Islam',
'-',
'http://www.islamhouse.com/p/196566',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Pregiudizi_correnti_sui_diritti_delluomo_nellIslam.pdf,http://d1.islamhouse.com/data/it/ih_books/single/it_Pregiudizi_correnti_sui_diritti_delluomo_nellIslam.doc',
'',
'',
'',
''),

'18'=>array(
'18',
'Italiano',
'حبي العظيم للمسيح قادني إلى الإسلام',
'حبي العظيم للمسيح - عليه السلام - قادني إلى الإسلام: تبين هذه الرسالة كيف أثر المسيح - عليه السلام - في اعتناق الكاتب لدين الإسلام، وكيف أثر الإسلام في حياته، وكيف تأثرت حياة الأخرين نتيجة اسلامه، وفي النهاية عقد مقارنة بين نصوص من القرآن الكريم والكتاب المقدس.',
'Il mio grande amore per Gesù mi ha portato all\'Islam',
'Il mio grande amore per Gesù (su di lui la pace) mi ha portato all\'Islam',
'http://www.islamhouse.com/p/196564',
'http://d1.islamhouse.com/data/it/ih_books/single/it_my_love_for_jesus.pdf',
'',
'',
'',
''),

'19'=>array(
'19',
'Italiano',
'المرأة في ظلال الإسلام',
'هذا الكتاب يبين كيف كرم الإسلام المرأة، وجعلها جوهرة مصونة.',
'La dignità della donna nell\'islam',
'La dignità della donna nell\'islam',
'http://www.islamhouse.com/p/193734',
'http://d1.islamhouse.com/data/it/ih_books/single/it_La_dignita_della_donna_nellislam.pdf,http://d1.islamhouse.com/data/it/ih_books/single/it_La_dignita_della_donna_nellislam.doc',
'',
'',
'',
''),

'20'=>array(
'20',
'Italiano',
'محمد رسول الله صلى الله عليه وسلم',
'محمد رسول الله صلى الله عليه وسلم : تعريف مختصر بالنبي - صلى الله عليه وسلم - من حيث التعريف بنسبه ومولده وبعض صفاته وآدابه وأخلاقه، مع ذكر بعض أقوال المستشرقين في سيدنا محمد - صلى الله عليه وسلم -. ترجمه إلى الإيطالية: محمد حسن.',
'Muhammad, il messaggero di Allah, pace e benedizione su di lui',
'Muhammad, il messaggero di Allah, pace e benedizione su di lui',
'http://www.islamhouse.com/p/192678',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Muhammad_il_messagger_o_di_Allah.pdf,http://d1.islamhouse.com/data/it/ih_books/single/it_Muhammad_il_messagger_o_di_Allah.doc',
'',
'',
'',
''),

'21'=>array(
'21',
'Italiano',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة : التحليل العادل والجواب الشافي عن الأسئلة التالية: هل اليهودية والمسيحية والإسلام يشتركون في نفس العقائد الخاصة بالمرأة؟ هل حقاً اليهودية والمسيحية أكرموا المرأة أكثر من الإسلام؟ ما الحقيقة؟',
'Le Donne nell\'Islam e le Donne nella Tradizione Giudeo-Cristiana Mito & Realta\'',
'-',
'http://www.islamhouse.com/p/191529',
'http://d1.islamhouse.com/data/it/ih_books/single/it_women_in_islam_and_women_in_the_jewish_and_christian_faith.pdf',
'',
'',
'',
''),

'22'=>array(
'22',
'Italiano',
'عقيدة أهل السنة والجماعة',
'عقيدة أهل السنة والجماعة: تشتمل هذه الرسالة على بيان عقيدة أهل السنة والجماعة في باب توحيد الله وأسمائه وصفاته، وفي أبواب الإِيمان بالملائكة، والكتب، والرسل، واليوم الآخر، والقدَر خيره وشره.',
'La Dottrina della Gente che segue la Sunnah e il Consenso (\'Aqidatu Ahlu-s-Sunnah wa-l\'Jama\'ah)',
'La Lode spetta [solo] ad Allàh. Che la Pace e le Benedizioni siano sull\'ultimo dei Messaggeri, Muhammad, sulla sua Famiglia e sui suoi Compagni. Sono venuto a conoscenza di questa professione di fede del Musulmano sotto forma di riassunto, composto dal nostro fratello, l\'eminente Sapiente, shaykh Muhammad ibn Salih al-\'Uthaymin. L\'ho ascoltato per intero e l\'ho trovato completo e chiaro per ciò che concerne la Dottrina della gente che segue la Sunnah e il Consenso (\'Aqidatu Ahlu-s-Sunnah wa-l\'Jama\'ah) , in particolare nei capitoli dell\'Unicità di Allàh -SubhanaHu waTa\'âla, dei Suoi Nomi e dei Suoi Attributi, della Fede in Allàh (SWT), nei Suoi Libri rivelati, nei Suoi Messaggeri, negli Angeli, nel Giorno del Giudizio e nel destino buono o cattivo. [Lo shaykh] ha anche aggiunto dei punti importanti che si ritrovano soltanto in poche opere su questo argomento. Che Allàh -l\'Altissimo- gli accordi dunque la Sua retribuzione, aumenti la sua conoscenza, lo guidi e faccia sì che questa sua opera sia utile a tutti, così come gli altri suoi libri. Che Allàh -l\'Altissimo- lo ponga, insieme a noi e ai nostri fratelli, nel numero delle guide e di coloro che sono guidati, e tra coloro che chiamano verso Allàh -SubhanaHu waTa\'âla- con prove evidenti. Egli è Colui Che ascolta, Colui che è Vicino. Che la Pace e le Benedizioni di Allàh siano sul nostro Profeta Muhammad, su tutta la sua Famiglia e su tutti i suoi Compagni. Shaykh \'Abdul\'Aziz Ibn \'Abdullah Ibn Baz',
'http://www.islamhouse.com/p/175510',
'http://d1.islamhouse.com/data/it/ih_books/single/it_belief_of_ahlu_alsunnah_and_aljamah.pdf',
'',
'',
'',
''),

'23'=>array(
'23',
'Italiano',
'أركان الإيمان',
'أركان الإيمان: هذه الدراسة عن أركان الإيمان هي أحد برامج العمادة العلمية، حيث وجّهت بعض أعضاء هيئة التدريس بالجامعة للكتابة في الموضوع ثمّ كلّفت اللجنة العلمية بالعمادة بدراسة ما كتبوه واستكمال النقص وإخراجه بالصورة المناسبة، مع الحرص على ربط القضايا العلمية بأدلّتها من الكتاب والسنّة. وتحرص العمادة - من خلال هذه الدراسة - إلى تمكين أبناء العالم الإسلامي من الحصول على العلوم الدينية النافعة؛ لذلك قامت بترجمتها إلى اللغات العالمية ونشرها وتضمينها شبكة المعلومات الدولية - الإنترنت -.',
'I Pilastri della fede',
'-',
'http://www.islamhouse.com/p/172721',
'http://d1.islamhouse.com/data/it/ih_books/single/it_pillars_of_eman.pdf,http://d1.islamhouse.com/data/it/ih_books/single/it_pillars_of_eman.doc',
'عمادة البحث العلمي بالجامعة الإسلامية',
'',
'',
'موقع الجامعة الإسلامية بالمدينة المنورة'),

'24'=>array(
'24',
'Italiano',
'أذكار مصورة للطفل المسلم',
'بطاقات أذكار خاصة بالأطفال, يتعلم من خلالها الطفل ماذا يقول عند الاستيقاظ من النوم, عند الخروج من المنزل, عند الطعام, عند نزول المطر, عند المساء ... إلخ',
'Invocazioni quotidiane',
'una raccolta di invocazioni illustrate per imparare cosa dire nelle diverse occasioni della vita quotidiana: prima di mangiare, uscendo di casa, al risveglio, quando si va a dormire...',
'http://www.islamhouse.com/p/172715',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Invocazioni_quotidiane.pdf,http://d1.islamhouse.com/data/it/ih_books/single/it_Invocazioni_quotidiane.doc',
'',
'',
'',
''),

'25'=>array(
'25',
'Italiano',
'الرسول الأعظم محمد صلى الله عليه وسلم',
'الرسول الأعظم : يتكون الكتاب من: الفصل الأول: ويتكون من نبذة عن سبب تأليف الكتاب، ثم الإشارة إلى جوانب عظمة الرسول - صلى الله عليه وسلم -. الفصل الثاني: يغلب فيه التحدث عن كتاب كارلايل هذا الرجل المنصف الذي اتخذ من محمد - صلى الله عليه وسلم - نبياً له يدافع عنه ويذب عنه كل الافتراءات التي حاول أن يلصقها به أعداءه. الفصل الثالث: يحمل عنوان أسرع الأديان نمواً اليوم ويتناول هذا الفصل الأسباب الدافعة للنمو المطرد في الإسلام والمسلمين فهو بحق الدين المثالي الذي يكثر معتنقيه في شتى بقاع العالم.',
'Muhammad il più Grande di tutti i tempi',
'Indice: • Introduzione • Capitolo 1: Muhammad il Grande o il più Grande? • Capitolo 2: Cercando nella storia • Capitolo 3: La Religione più diffusaIntroduzione',
'http://www.islamhouse.com/p/161308',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Muhammad_il_piu_Grande_di_tutti_i_tempi.pdf',
'',
'',
'',
''),

'26'=>array(
'26',
'Italiano',
'الدليل المصور الموجز لفهم الإسلام',
'كتاب الدليل المصور الموجز لفهم الإسلام باللغة الإيطالية، والذي يتحدث بصفة خاصة عن الإعجاز العلمي في الإسلام، وأيضاً يُعنى بمفاهيم الإسلام وتصوره تجاه الفرد والمجتمع، والمكاسب التي تتحقق لك حالة كونك مسلماً ملتزماً بتعاليم الشريعة الإسلامية. هذا الكتاب تصدر قائمة الكتب الدعوية الموجهة لغير المسلمين في عظيم أثره، لذا يحرص المتخصصون في التعريف بالإسلام بالبدء بإهداء ترجمة معاني القرآن الكريم بلغة غير المسلم ثم يليه في قائمة الإهداء هذا الكتاب، ثم بقية الكتب الدعوية الأخرى.',
'Una breve guida illustrata per comprendere l\'Islam',
'Questa guida islamica è rivolta ai non-musulmani che desiderano comprendere l\'Islam, i musulmani e il sacro Corano. È ricca di informazioni, di riferimenti, di bibliografia e illustrazioni. È stata rivista e curata da molti professori e persone colte. È breve e semplice da leggere, sebbene contenga molto sapere scientifico. Contiene tutto il libro, A Brief Illustrated Guide to Understanding Islam (Una breve guida illustrata per comprendere l\'Islam), e altro ancora. Segue l\'indice della guida.',
'http://www.islamhouse.com/p/161306',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Una_breve_guida_illustrata_per_comprendere_lIslam.pdf',
'',
'',
'',
''),

'27'=>array(
'27',
'Italiano',
'الدين الصحيح',
'يتناول هذا الكتاب: • شرحاً موجزاً للدين الإسلامي، وأنه الدين الصحيح الذي لا يقبل الله ديناً سواه. • استعراض الأديان والمبادئ الأخرى وبيان بطلانها. • حقيقة عيسى وأمه - عليهما السلام -. • عالمية الدين الإسلامي والحكمة في خلق الثقلين.',
'LA VERA RELIGIONE',
'-',
'http://www.islamhouse.com/p/120435',
'http://d1.islamhouse.com/data/it/ih_books/single/it_La_vera_religione.pdf,http://d1.islamhouse.com/data/it/ih_books/single/it_La_vera_religione.doc',
'',
'',
'',
''),

'28'=>array(
'28',
'Italiano',
'التعريف بالإسلام والمسلمين',
'',
'Conoscere l\'Islam e i Musulmani',
'-',
'http://www.islamhouse.com/p/1172',
'http://d1.islamhouse.com/data/it/ih_books/single/it_Conoscere_lIslam_e_i_Musulmani.pdf',
'',
'',
'',
'')

);
?>