<?php
$BOOKS = array(
'1'=>array(
'1',
'Nederlands',
'من عقائد الشيعة',
'من عقائد الشيعة: هذه الرسالة تبين بعض معتقدات الشيعة في صورة سؤال وجواب بصورة مختصرة.',
'Een kort overzicht van het sjiitische geloof',
'De verspreiding van het sjiisme in de islamitische wereld de afgelopen jaren, heeft het veel gevaar met zich meegebracht en moslims zijn zich daar niet altijd van bewust.',
'http://www.islamhouse.com/p/383950',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_laatste_versie_shijieten.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_laatste_versie_shijieten.doc',
'Abdellah bin Mohammed Assalafi',
'Abou Abdel Allah',
'Younous Oudaha',
''),

'2'=>array(
'2',
'Nederlands',
'السحر والشعوذة',
'إن السحر من الجرائم العظيمة، ومن أنواع الكفر ومما يبتلى به الناس قديماً وحديثاً، في الأمم الماضية وفي الجاهلية وفي هذه الأمة، وعلى حسب كثرة الجهل وقلة العلم وقلة الوازع الإيماني والسلطاني - يكثر أهل السحر والشعوذة ، وينتشرون في البلاد للطمع في أموال الناس والتلبيس عليهم، ولأسباب أخرى، وعندما يظهر العلم ويكثر الإيمان، ويقوى السلطان الإسلامي يقل هؤلاء الخبثاء وينكمشون وينتقلون من بلاد إلى بلاد لالتماس المحل الذي يروج فيه باطلهم، ويتمكنون فيه من الشعوذة والفساد. وقد بين الكتاب والسنة أنواع السحر وحكمها.',
'Sih\'r (magie) en toekomstvoorspelling',
'Gezien de verspreiding van de charlatans de laatste tijd - zij die beweren genezers te zijn door zwarte magie te gebruiken, enof zij die beweren de toekomst te kunnen voorspellen - wens ik een advies te geven, omwille van Allah en omwille van Zijn dienaren op deze manier hoop ik de gevaren te verduidelijken, die dergelijke zaken zich meebrengen voor zowel de Islaam als voor de moslims.',
'http://www.islamhouse.com/p/374097',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_sihr.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_sihr.doc',
'Abdel Aziez bin Abdel Allah bin Baz',
'',
'Aboe Abdellah Albelgiki',
''),

'3'=>array(
'3',
'Nederlands',
'البكاء من خشية الله تعالى',
'نقف معاً على عجالة في هذه الرسالة على تفصيلٍ حول عبادة من أجلِّ العبادات.. عبادة حُرم منها الكثيرون.. وغفل عنها الكثيرون إلا من رحم الله .... لو علم الخلق فضلها لما كان حالهم كما ترى.. إنها عبادة البكاء من خشية الله وما أعظمها من عبادة! نقف وقفات مع هذه العبادة العظيمة.. وقفة.. (نعلم فيها فضل البكاء من خشية الله وثمراته.. ووقفة أخرى.. نعلم فيها السبب في جفاف أعيننا عن البكاء من خشية الله.. ووقفة ثالثة هي لُبُّ الموضوع.. نعلم فيها السبل الميسرة للبكاء من خشية الله.. ثم وقفتنا الأخيرة.. نتأمل فيها أحوال البكَّائين وعلى رأسهم سيد المرسلين محمد..) لعلنا نقتدي بهم ونتأسى بهديهم.',
'Huilen vanuit nederigheid voor Allah',
'We ervaren in onszelf en zien bij vele Moslims om ons heen dat de slechte dingen die we doen onze harten beinvloeden....Hoe merken we dat? We bidden met automatisme; zonder er iets bij te VOELEN; zonder dat tranen over onze wangen rollen....waar blijven onze tranen en onze rillingen bij het horen van de woorden van Allah?Hoeveel keren per dag of per week of per maand huil je voor Allah?',
'http://www.islamhouse.com/p/371454',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_albokaa.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_albokaa.doc',
'Hoessein Alhawa iechah',
'',
'Aboe Abdellah Albelgiki',
''),

'4'=>array(
'4',
'Nederlands',
'نزول عيسى بن مريم عليه السلام في آخر الزمان',
'نزول عيسى بن مريم عليه السلام في آخر الزمان: من العلامات الكبري ليوم القيامة بعد ظهور المسيح الدجال هي نزول عيسي ابن مريم - عليه السلام -, وهو ينزل بعد ظهور المهدي وخروج الدجال. وفي هذا الكتاب ذِكر أحاديث نزول عيسى ابن مريم - عليه السلام - في آخر الزمان وما يتبَع ذلك من أحداث. - والكتاب ترجمَه إلى الهولندية: أبو يوسف.',
'De neerdaling van ‘Iesaa (Jezus)',
'\'Iesaa is niet zoals de Christen beweren gestorven aan het kruis, maar hij wordt door Allah ten hemel opgenomen en wij nl. moslims geloven dat hij (Isaa) nog zal neerdalen zodanig dat Allah door middel van hem (Isaa) de Islam zal triomferen.',
'http://www.islamhouse.com/p/371282',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_De_neerdaling_van_Iesaa_Jezus.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_De_neerdaling_van_Iesaa_Jezus.doc',
'Omar bin Soelaymane Alashqaar',
'',
'Aboe Abdellah Albelgiki',
'Coöperatieve Bureau voor Da\'wa Rabwa In Riyadh'),

'5'=>array(
'5',
'Nederlands',
'الأزمة المالية',
'الأزمة المالية: فقد ذاع في الأفق خبر الأزمة المالية التي تهاوَت فيها بنوك كبرى ومؤسسات مالية عُظمى، وانحدَرَت فيها البورصات العالمية، وتبخَّرت تريليونات، وطارت مليارات من أسواق المال، وهوَت دولٌ إلى الحضيض، وفقد عشرات الآلاف أموالَهم؛ إما على هيئة أسهم، أو مُدَّخرات أو استثمارات، وتآكَلت من استثمارات الشعب الأمريكي في البورصات المالية بمقدار 4 تريليون دولار، وصارت هذه الأزمة أشبه بتسونامي يعصف باقتصاديات الكثير من الدول. حول هذه الأزمة يدور موضوع هذا الكتاب القيِّم.',
'Analyse van de financiële crisis in het licht van de sharie\'ah',
'Het is voor iedereen duidelijk dat de financiële crisis de hele wereld doet schudden, van het oosten tot het westen. Het is een ingrijpende gebeurtenis welke politici, beleidsmakers, prominente denkers en economen slapeloze nachten bezorgt. Het is een enorme en complexe ramp welke vele implicaties heeft. Dit verklaart de grote onrust die economen en politici ervaren.',
'http://www.islamhouse.com/p/344798',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_azma_maleya.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_azma_maleya.doc',
'Mohammed Salih Almounajid',
'',
'Aboe Abdellah Albelgiki',
''),

'6'=>array(
'6',
'Nederlands',
'هل الكتاب المقدس كلام الله؟',
'هل الكتاب المقدس كلام الله؟: هذه الرسالة نتاج بحث مستفيض لسنين طويلة حول حقيقة الكتاب المقدس وهل هو كلام الله، وبمنهج علمي دقيق، أَثبت المؤلف بطلان هذا الزعم، وعزَّز رأيه بأدلة وبراهين من نصوص الكتاب المقدس. وقد تم ترجمتها إلى عدة لغات عالمية.',
'Is De Bijbel God\'s Woord?',
'Dr. W.Graham Scroggie van het "Moody Bible Instituut" in Chicago, een van de meest prestigieuze Christelijke Evangelische missies ter wereld, geeft als antwoord op de vraag "is de Bijbel het woord van God?" (wat ook de titel van zijn boek is), het volgende antwoord:"Ja, de Bijbel is menselijk ,alhoewel sommigen, vanuit een ijver die niet overeenstemt met kennis dit hebben ontkend. Deze boeken ( de Bijbel) zijn door de dachten van mensen gegaan, zijn in mensentaal geschreven, zijn opgeschreven door mensenhanden , en herbergen in hun stijl de menselijke kenmerken.',
'http://www.islamhouse.com/p/344796',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_Is_The_Bible_Gods_Word.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_Is_The_Bible_Gods_Word.doc',
'Ahmed Deedat',
'Abdoel-Jabbar Vin Daven',
'Aboe Abdellah Albelgiki',
''),

'7'=>array(
'7',
'Nederlands',
'العقيدة الصحيحة وما يضادها ونواقض الإسلام',
'العقيدة الصحيحة وما يضادها ونواقض الإسلام: محاضرة ألقاها فضيلة العلامة الشيخ عبد العزيز بن عبد الله بن باز - رحمه الله - بين فيها أصول عقيدة أهل السنة والجماعة، إذا أنه من المعلوم بالأدلة الشرعية من الكتاب والسنة أن الأعمال والأقوال إنما تصح وتقبل إذا صدرت عن عقيدة صحيحة، فإن كانت العقيدة غير صحيحة بطل ما يتفرع عنها من أعمال وأقوال.',
'De Authentieke Dogmatiek & wat daar tegenover staat',
'Sinds de authentieke `Aqiedah het fundament is van de Islam en de grondlegging van de Islamitische religie is het bekend met de bewijzen uit de Sharie`ah, vanuit het Boek en de Soennah dat iemands handelingen en uitspraken alleen correct en acceptabel zijn (bij Allah) wanneer zij voortvloeien vanuit een correcte `Aqiedah. Wanneer de `Aqiedah niet correct is dan is hetgene wat hieruit voortvloeit ongeldig.',
'http://www.islamhouse.com/p/339638',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_The_Right_Creed_and_what_Opposes_it.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_The_Right_Creed_and_what_Opposes_it.doc',
'Abdel Aziez bin Abdel Allah bin Baz',
'',
'Aboe Abdellah Albelgiki',
''),

'8'=>array(
'8',
'Nederlands',
'شرح القواعد الأربع',
'شرح القواعد الأربع: رسالة مختصرة كتبها الإمام المجدد شيخ الإسلام محمد بن عبد الوهاب - رحمه الله - وقد اشتملت على تقرير ومعرفة قواعد التوحيد، وقواعد الشرك، ومسألة الحكم على أهل الشرك، والشفاعة المنفية والشفاعة المثبتة. - وفي هذه الصفحة شرح للشيخين: عبد الله بن عبد الرحمن الجبرين - رحمه الله -، وصالح بن عبد العزيز آل الشيخ - حفظه الله -، باللغة الهولندية.',
'Uitleg van de vier principes betreft Shirk',
'Men dient te weten dat wanneer aanbidding vermengd wordt (met shirk), de aanbidding niet geaccepteerd wordt en de handeling vernietigd. Als men weet dat personen die zo handelen permanent in het Hellevuur zullen zijn, dan zal men zich bewust van zijn dat tawhied het belangrijkste onderwerp is om te bestuderen (kennen).',
'http://www.islamhouse.com/p/337824',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_Explain_the_rules_of_the_four.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_Explain_the_rules_of_the_four.doc',
'Abdel Allah bin Abdel Arrahman Aljiebrien - Saleh bin Abdel Alaziez Aalchieg',
'',
'Aboe Abdellah Albelgiki',
''),

'9'=>array(
'9',
'Nederlands',
'مختصر لمسائل كتاب الروح لابن القيم',
'قال المؤلف في مقدمته للرسالة: «فهذا مختصر لطيف للمسائل التي أجاب عنها العلامة ابن القيم - رحمه الله - في كتاب (الروح) مع أجوبتها، مقتصرًا في ذلك على ذكر الجواب الصحيح دون التعرض لنقل الخلافيات والأدلة المتشعبة؛ لكي يسهل استحضارها لطلاب العلم، ولعامة المسلمين».',
'De reis van de ziel na de dood',
'Als iemand sterft, komt de Engel des Doods om zijn ziel te nemen, ongeacht wie hij is. De stervende persoon ziet hem, hoort hem en spreekt met hem, maar niet met zijn ogen, zijn oren of zijn tong. Hoe gaat dat dan?',
'http://www.islamhouse.com/p/328989',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_Eigenaar_van_het_boek_Geest_Matters.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_Eigenaar_van_het_boek_Geest_Matters.doc',
'Soelaymane bin Saleh Algoeraashie',
'',
'Aboe Abdellah Albelgiki',
''),

'10'=>array(
'10',
'Nederlands',
'الحكم من كتب ابن القيم',
'الحِكَم من كتب ابن القيم: مجموع فيه حِكَم وأقوال مأثورة من كتب ابن قيم الجوزية - رحمه الله -.',
'De wijsheden van ibn Alqayyim Aljawziyyah',
'In dit artikel zijn wijsheden verzameld van de grote geleerde Ibn al Qayyim al-Jawziyyah (Geb. 691 / 1292 n. Chr. ) uit verschillende boeken die hij geschreven heeft.',
'http://www.islamhouse.com/p/326790',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_hekam_ibn_alkayem_aljawziyah.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_hekam_ibn_alkayem_aljawziyah.doc',
'Ibn Alqayiem Aljawzie',
'',
'Aboe Abdellah Albelgiki',
''),

'11'=>array(
'11',
'Nederlands',
'كتاب الطهارة من كتاب سبل السلام',
'كتاب الطهارة من الكتاب الماتع النافع «سبل السلام شرح بلوغ المرام» للإمام محمد بن إسماعيل الأمير الصنعاني - رحمه الله -.',
'Thema ‘De reiniging\' uit het boek Soeboel Assallaam',
'Reiniging speelt een belangrijke rol binnen de Islam en ook bij het gebed. Het gebed kan alleen worden verricht in een toestand van reinheid, die reinheid is te bereiken door een eenvoudige rituele wassing. Deze wassing wordt \'woedoe\' genoemd Deze wassing is in principe voldoende om over te gaan tot het gebed. In enkele gevallen echter is er een grote rituele wassing nodig, de \'ghoesl\'. Deze wassing is nodig na het hebben van geslachtsgemeenschap, na een zaadlozing, na afloop van de menstruatie en na afloop van de bloedingen na een geboorte. Verder kan er in enkele gevallen eventueel gebruik gemaakt worden van een reiniging door zuivere aarde, de \'tayammoem\'.',
'http://www.islamhouse.com/p/323048',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_reiniging.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_reiniging.doc',
'Mohammed bin Aliemier Assanie - Mohammed bin Aliemier Assanhanie',
'',
'',
''),

'12'=>array(
'12',
'Nederlands',
'العقيدة الواسطية',
'العقيدة الواسطية: رسالة نفيسة لشيخ الإسلام ابن تيمية - رحمه الله - ذكر فيها جمهور مسائل أصول الدين، ومنهج أهل السنة والجماعة في مصادر التلقي التي يعتمدون عليها في العقائد؛ لذا احتلت مكانة كبيرة بين علماء أهل السنة وطلبة العلم، لما لها من مميزات عدة من حيث اختصار ألفاظها ودقة معانيها وسهولة أسلوبها، وأيضاً ما تميزت به من جمع أدلة أصول الدين العقلية والنقلية.',
'Al-‘Aqeedah Al-Waasitiyyah',
'Dit is het Geloof van de Geredde Groep, degenen die triomferen tot de Dag des Oordeels, de Mensen van de Sunnah en de Jamaa’ah [het Geloof in Allah, Zijn Engelen, Zijn Boeken, Zijn Boodschappers, de wederopstanding na de dood, het Geloof in de Goddelijke Voorbeschikking [Al-Qadar], hetzij goed of slecht]].',
'http://www.islamhouse.com/p/323044',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_alwasitiyah.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_alwasitiyah.doc',
'Ahmed bin Abdel-Alhaliem bin Tijy-miyah',
'',
'',
''),

'13'=>array(
'13',
'Nederlands',
'الرحيق المختوم [ بحث في السيرة النبوية ]',
'الرحيق المختوم: لقد حظيت سيرة صاحب الرسالة العظمى - صلى الله عليه وسلم - باهتمام العلماء والمحدثين والكتاب والمؤرخين، المتقدمين منهم والمتأخرين، وكل من هؤلاء الأعلام يغوص في ثبج هذا البحر الزاخر، ويستصفي منه يتيم الجوهر ونفيس الدرر. فمنهم من عني باستخلاص دلائل الإعجاز والخصائص النبوية، ومنهم من صمد إلى الإبانة عن أحداث الغزوات وتفاصيل المعارك، ومنهم من أفاض في ذكر فقهها واستخلاص أحكامها وعبرها، ومنهم من استجلى مواقف عظمة هذه النفس الزكية. ولا تزال وستبقى سيرة هذا النبي الكريم - صلى الله عليه وسلم - ملهمة لأولي الأقلام اللامعة والدراسات العميقة، للاستهداء بهديها والتأسي بصاحبها صلى الله عليه وسلم. وممن أسهم في هذا المضمار ونهل من هذا المعين الصافي الشيخ صفي الرحمن المباركفوري - رحمه الله - في كتابنا هذا؛ حيث كتب عن السيرة فصولاً مضيئة، وموازنات فريدة، وربط الأحداث ببعضها ربطًا متماسكًا بأسلوب بديع أخاذ، حيث استخلص من كتب الأقدمين فوائد بلورها في إيجاز غير مخل، وتطويل غير ممل، فجاء كافيًا وافيًا. وفي زماننا هذا الذي أضحى الناس فيه يلهثون وراء مناهج فاسدة ويسلكون سبلاً معوجة .. تبرز أهمية دراسة السيرة العطرة؛ لتوضح لنا معالم الطريق المستقيم، وعظمة هذا النبي الكريم، عسى أن يكون هذا باعثًا لنا على إصلاح ما أفسده بعدنا عن المنهج الإلهي، والتأسي بمنقذ البشرية من الضلال والتيه صلى الله عليه وسلم.',
'Arrahiq Almagtoom',
'De levensloop van de Profeet, "as-sirah", behoort tot de meest gezaghebbende kennis die men kan vergaren. Het is een verheven leer die men kan begeren, omdat een moslim hierdoor meer komt te weten over zijn religie en zijn Profeet.',
'http://www.islamhouse.com/p/319848',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_Arrahiq_Almakhtoom.pdf',
'Safie Arrahmane Almoebaarakfoerie',
'',
'Aboe Abdellah Albelgiki',
''),

'14'=>array(
'14',
'Nederlands',
'هل اكتشفت جماله الحقيقي؟ [ الإسلام ]',
'هذه الرسالة تشتمل الإجابة على بعض الأسئلة التي غالبًا ما تدور في أذهان غير المسلمين؛ مثل: ما هو الحق؟ من هو الإله الحقيقي؟ كيف الحصول على راحة القلب والسلام؟ وكيف الحصول على المغفرة والناجحة؟ ما هي أركان الإيمان الستة؟ وما هي الأركان الخمسة؟',
'Hebt U haar ware schoonheid al ontdekt?',
'Hebt U haar ware schoonheid al ontdekt?',
'http://www.islamhouse.com/p/315238',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_Have_you_discovered_its_real_beauty.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_Have_you_discovered_its_real_beauty.doc',
'Naji Ibrahim Al-Irfaj',
'',
'',
''),

'15'=>array(
'15',
'Nederlands',
'الأربعون النووية',
'الأربعون النووية: متن مشهور، اشتمل على اثنين وأربعين حديثًا محذوفة الإسناد في فنون مختلفة من العلم، كل حديث منها قاعدة عظيمة من قواعد الدين، وينبغي لكل راغب في الآخرة أن يعرف هذه الأحاديث، لما اشتملت عليه من المهمات، واحتوت عليه من التنبيه على جميع الطاعات.',
'De veertig hadieth\'s van Annawawi',
'Boodschapper van Allah - vrede zij met hem - zei: “Wie aan mijn gemeenschap veertig overleveringen overdraagt over zaken van hun godsdienst, Allah zal hem op de Dag der Opstanding voortbrengen in een gezelschap van rechtsgeleerden en theologen.',
'http://www.islamhouse.com/p/291565',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_forty_hadith_of_nawawi.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_forty_hadith_of_nawawi.doc',
'Aboe Zakrayah An-nawawie',
'',
'Aboe Abdellah Albelgiki',
''),

'16'=>array(
'16',
'Nederlands',
'علاج الهموم',
'علاج الهموم: إن في القرآن والسنة الوقاية والعلاج لحالات الحزن والاكتئاب، وخاصةً ما كان منها لأسبابٍ خارجية، وهذا من رحمة الله سبحانه وتعالى بعباده؛ إذ أنه - سبحانه - جعل القرآن شفاءً ورحمةً للمؤمنين، وما عليهم سوى العودة إلى كتاب ربهم وإلى سنة نبيه - صلى الله عليه وسلم - ليفوزوا بالسعادة والراحة في الدارين، وفي هذا الكتاب علاجٌ لكثير من الهموم.',
'Remedie tegen sterss',
'Het is de aard van dit leven dat mensen lijden aan zorgen en stress, omdat deze wereld de plaats is van ziekte, hardheid en leed. Want onder de dingen die het Paradijs van deze wereld onderscheiden is het feit dat daar geen sprake zal zijn van bezorgdheid of stress: “Vermoeidheid zal hen daar niet raken noch zullen zij er van worden verdreven.” Al-H’idjr 15:48.',
'http://www.islamhouse.com/p/289627',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_Remedie_tegen_sterss.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_Remedie_tegen_sterss.doc',
'Mohammed Salih Almounajid',
'',
'Aboe Abdellah Albelgiki',
''),

'17'=>array(
'17',
'Nederlands',
'آداب الزفاف في السنة المطهرة',
'آداب الزفاف في السنة المطهرة : هذه الرسالة اللطيفة نموذج لناحية من النواحي التي تناولتها رسالة الإسلام بالسنن الصحيحة عن معلم الناس الخير - صلى الله عليه وسلم - في حفلات الزفاف وآدابه وولائمه.',
'De etiquette van het huwelijk',
'Het is bekend dat er vele etiketten zijn op het gebied van het huwelijk, die ieder gehuwdemoslim moet weten. En daarna moet toepassen in zijn dageliks leven.',
'http://www.islamhouse.com/p/286930',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_adab_alzfaf_fi_alsnah_almothrah.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_adab_alzfaf_fi_alsnah_almothrah.doc',
'Mohammed Nasseroedien Alalbanie',
'',
'Aboe Abdellah Albelgiki',
'Coöperatieve Bureau voor Da\'wa Rabwa In Riyadh'),

'18'=>array(
'18',
'Nederlands',
'شرح أركان الإيمان',
'شرح أركان الإيمان: هو كتاب نفيس في بيان أصول العقيدة الإسلامية؛ حيث عني المؤلف - رحمه الله - بذكر خصائص الدين الإسلامي وأركان الإسلام بشكل وجيز، ثم تناول بيان أركان الإيمان الستة بيانًا شافيًا.',
'Uitleg van de pilaren van Imaan',
'Als Tawhied zo belangrijk is, dan dient elke moslim zich te bekommeren om deze kennis te verwerven door het te bestuderen, te begrijpen en er vervolgens in te geloven. Dit is de manier waarop moslims hun religie bouwden op een stevige basis, terwijl zij zekerheid en nederigheid voelden in het geloof. Dit leidt uiteindelijk naar vreugde, nadat de doelen van de Islam zijn bereikt.',
'http://www.islamhouse.com/p/276250',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_de_pilaren_van_imaan.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_de_pilaren_van_imaan.doc',
'Mohammed bin Salih Al-Oethaimine',
'',
'Aboe Abdellah Albelgiki',
'Coöperatieve Bureau voor Da\'wa Rabwa In Riyadh'),

'19'=>array(
'19',
'Nederlands',
'النبي محمد صلى الله عليه وسلم في الإنجيل',
'النبي محمد صلى الله عليه وسلم في الإنجيل:',
'De profeet Mohammed in de Bijbel',
'De komst van de profeet Mohammed wordt voorspeld in het Oude Testament. Ahmed Deedat, die vele boeken over de Islam en het Christendom heeft geschreven (zoals \'Jezus (as) in de Islam\' en \'De Opstanding van Jezus (as)\'), laat heel duidelijk zien, met de desbetreffende verzen, hoe de komst van Mohammed is voorspeld in de Bijbel, het Heilige Boek van de Christenen.',
'http://www.islamhouse.com/p/276248',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_De_Prophet_Mohammed_in_de_Bijbel.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_De_Prophet_Mohammed_in_de_Bijbel.doc',
'Ahmed Deedat',
'',
'Aboe Abdellah Albelgiki',
'Coöperatieve Bureau voor Da\'wa Rabwa In Riyadh'),

'20'=>array(
'20',
'Nederlands',
'المسيح في الإسلام',
'عيسى - عليه السلام - في الإسلام: مقالة بيَّن فيها المؤلف مكانة المسيح عيسى ابن مريم - عليه السلام - في الإسلام.',
'Jezus in de Islam ( Allah\'s vrede en genade zij met hem)',
'Jezus in de Islam ( Allah\'s vrede en genade zij met hem).',
'http://www.islamhouse.com/p/263744',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_jezuse_in_de_islam.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_jezuse_in_de_islam.doc',
'Ahmed Deedat',
'Abdoel-Jabbar Vin Daven',
'Aboe Abdellah Albelgiki',
'Coöperatieve Bureau voor Da\'wa Rabwa In Riyadh'),

'21'=>array(
'21',
'Nederlands',
'الإله الذي لم يكن موجودًا',
'الإله الذي لم يكن موجودًا.',
'De God Die Nooit Bestond',
'De God Die Nooit Bestond.',
'http://www.islamhouse.com/p/263737',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_de_god_die_nooit_bestond.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_de_god_die_nooit_bestond.doc',
'Ahmed Deedat',
'Rachid Mulder',
'Aboe Abdellah Albelgiki',
'Coöperatieve Bureau voor Da\'wa Rabwa In Riyadh'),

'22'=>array(
'22',
'Nederlands',
'كشف الشبهات',
'رسالة نفيسة كتبها الإمام المجدد محمد بن عبد الوهاب - رحمه الله - وهي عبارة عن سلسلة شبهات للمشركين وتفنيدها وإبطالها، وفيها بيان توحيد العبادة وتوحيد الألوهية الذي هو حق الله على العباد، وفيها بيان الفرق بين توحيد الربوبية وتوحيد الإلهية والعبادة.',
'Het ontsluieren van dubieuze zaken',
'Weet - moge Allah je genadig zijn - dat de Tauwhied inhoudt dat Allah alleen wordt aanbeden, en het is de religie van de boodschappers waarmee Allah ze zond naar Zijn dienaren; de eerste van hen is Noeh (Noach) vrede zij met hem, Allah zond hem naar zijn volk nadat zij de grenzen hadden overschreden.',
'http://www.islamhouse.com/p/261134',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_het_ontsluieren_van_dubieuze_zaken.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_het_ontsluieren_van_dubieuze_zaken.doc',
'Mohammed bin Abdoel-Wahhab',
'',
'Aboe Abdellah Albelgiki',
''),

'23'=>array(
'23',
'Nederlands',
'تعدد الزوجات في الإسلام',
'هذا الكتاب يسهم في إيضاح فكرة التعدد في الإسلام من خلال نقاط عدة مثل: بيان أن المسلمين ليسوا أول من سلك هذا المسلك وإنما سبقهم إلى هذا أمم كثيرة منهم: النصارى القدامى، ثم يبين مشروعية التعدد، وشروطه، وحقوق وواجبات كلا الطرفين في ظل هذا النظام.',
'Polygynie in de Islam',
'ِHet huwelijk is een wettige, sociale en religieuze relatie tussen individuen wat de basis vormt van een familie. Historisch gezien was het huwelijk een sociaal contract tussen een man (de echtgenoot) en een vrouw (de echtgenote). Het huwelijk wordt over het algemeen gezien als een man-vrouw relatie ontworpen om kinderen te krijgen en hen succesvol geschikt te maken voor de samenleving. Tevens kan men in een huwelijk zijn of haar seksuele begeerten bevredigen op een toegestane, menselijke en veilige manier.',
'http://www.islamhouse.com/p/228866',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_polygamy_in_islam.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_polygamy_in_islam.doc',
'Bilal Filiebs',
'',
'Aboe Abdellah Albelgiki',
''),

'24'=>array(
'24',
'Nederlands',
'كيفية صلاة النبي صلى الله عليه وسلم',
'كيفية صلاة النبي صلى الله عليه وسلم : ما من عبادة إلا ولها صفة وكيفية، قد تكفل الله سبحانه ببيانها، أو بينها رسوله - صلى الله عليه وسلم -، وفي هذه الرسالة بيان لصفة صلاة النبي - صلى الله عليه وسلم - قال مصنفها في مقدمته « فهذه كلمات موجزة في بيان صفة صلاة النبي - صلى الله عليه وسلم - أردت تقديمها إلى كل مسلم ومسلمة ليجتهد كل من يطلع عليها في التأسي به - صلى الله عليه وسلم - في ذلك لقوله - صلى الله عليه وسلم - { صلوا كما رأيتموني أصلي } رواه البخاري ».',
'De beschrijving van het gebed van onze profeet',
'Het gebed bekleed in de Islam een uiterst belangrijke functie, want het is een contact tussen de dienaar en zijn Heer. Ook is het een oogappel (van de gelovige). Het is de meest geliefde daad tot Allah -verheven is Hij-. Het is een verbinding tussen de dienaar en zijn Heer.',
'http://www.islamhouse.com/p/226470',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_the_description_of_the_prophet_prayer.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_the_description_of_the_prophet_prayer.doc',
'Abdel Aziez bin Abdel Allah bin Baz',
'',
'Aboe Abdellah Albelgiki',
''),

'25'=>array(
'25',
'Nederlands',
'شرح كتاب كيفية صلاة النبي صلى الله عليه وسلم للشيخ ابن باز رحمه الله',
'كيفية صلاة النبي صلى الله عليه وسلم : ما من عبادة إلا ولها صفة وكيفية، قد تكفل الله سبحانه ببيانها، أو بينها رسوله - صلى الله عليه وسلم -، وفي هذه الرسالة بيان لصفة صلاة النبي - صلى الله عليه وسلم - قال مصنفها في مقدمته « فهذه كلمات موجزة في بيان صفة صلاة النبي - صلى الله عليه وسلم - أردت تقديمها إلى كل مسلم ومسلمة ليجتهد كل من يطلع عليها في التأسي به - صلى الله عليه وسلم - في ذلك لقوله - صلى الله عليه وسلم - { صلوا كما رأيتموني أصلي } رواه البخاري ». وفي هذه الصفحة شرح لهذه الرسالة المباركة باللغة الهولندية، شرحها د. سعد بن سعيد الهجري.',
'De beschrijving van het gebed van onze profeet (sav)',
'Het gebed bekleed in de Islam een uiterst belangrijke functie, want het is een contact tussen de dienaar en zijn Heer. Ook is het een oogappel (van de gelovige). Het is de meest geliefde daad tot Allah -verheven is Hij-. Het is een verbinding tussen de dienaar en zijn Heer. - Door de majestueuze Sjeik \'Aboel\'Aziez Bin Baaz met een uitleg van Sjeik dr. Sa\'d Ibn Sa\'ied el-Hijrie.',
'http://www.islamhouse.com/p/208553',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_explanation_the_description_of_the_prophet_prayer.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_explanation_the_description_of_the_prophet_prayer.doc',
'Abdel Aziez bin Abdel Allah bin Baz',
'',
'Aboe Abdellah Albelgiki',
''),

'26'=>array(
'26',
'Nederlands',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة : التحليل العادل والجواب الشافي عن الأسئلة التالية: هل اليهودية والمسيحية والإسلام يشتركون في نفس العقائد الخاصة بالمرأة؟ هل حقاً اليهودية والمسيحية أكرموا المرأة أكثر من الإسلام؟ ما الحقيقة؟',
'Vrouwen binnen de Islaam versus Vrouwen binnen de Judaeo Christelijke Traditie.De Mythe en de Realiteit',
'Vrouwen binnen de Islaam versus Vrouwen binnen de Judaeo Christelijke Traditie.De Mythe en de Realiteit',
'http://www.islamhouse.com/p/191542',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_women_in_islam_and_women_in_the_jewish_and_christian_faith.pdf',
'Charif Abdel-Adhim',
'',
'',
'Association Tabligh Al-Islam - Vereniging Tabligh Al-Islam'),

'27'=>array(
'27',
'Nederlands',
'ثلاثة الأصول وأدلتها',
'ثلاثة الأصول : رسالة مختصرة ونفيسة تحتوي على الأصول الواجب على الإنسان معرفتها من معرفة العبد ربه, وأنواع العبادة التي أمر الله بها، ومعرفة العبد دينه، ومراتب الدين، وأركان كل مرتبة، ومعرفة النبي - صلى الله عليه وسلم - في نبذة من حياته، والحكمة من بعثته، والإيمان بالبعث والنشور، وركنا التوحيد وهما الكفر بالطاغوت, والإيمان بالله، وفي هذه الصفحة ترجمتها إلى اللغة الهولندية.',
'De Drie Principes en zijn bewijzen',
'De Drie Principes en zijn bewijzen',
'http://www.islamhouse.com/p/173049',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_three_fundamental_principles.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_three_fundamental_principles.doc',
'Mohammed bin Abdoel-Wahhab',
'Dioera Tachman Arwin',
'',
'De site van de Islamitische Universiteit in Madinah. http://www.iu.edu.sa'),

'28'=>array(
'28',
'Nederlands',
'التعريف الموجز بالإسلام',
'التعريف الموجز بالإسلام: تعريف موجز بالدين الإسلامي وبيان شموليته لجميع جوانب الحياة مع بيان أهم أركانه الستة.',
'Een Algemeen Beeld van de Islam',
'Een algemeen beeld van de Islam',
'http://www.islamhouse.com/p/173046',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_definition_of_islam.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_definition_of_islam.doc',
'Abdullah Jip Hallmans',
'',
'Decanaat van Wetenschappelijk Onderzoek Islamitische Universiteit Madinah',
'De site van de Islamitische Universiteit in Madinah. http://www.iu.edu.sa'),

'29'=>array(
'29',
'Nederlands',
'الدليل المصور الموجز لفهم الإسلام',
'كتاب الدليل المصور الموجز لفهم الإسلام باللغة الهولندية، والذي يتحدث بصفة خاصة عن الإعجاز العلمي في الإسلام، وأيضاً يُعنى بمفاهيم الإسلام وتصوره تجاه الفرد والمجتمع، والمكاسب التي تتحقق لك حالة كونك مسلماً ملتزماً بتعاليم الشريعة الإسلامية. هذا الكتاب تصدر قائمة الكتب الدعوية الموجهة لغير المسلمين في عظيم أثره، لذا يحرص المتخصصون في التعريف بالإسلام بالبدء بإهداء ترجمة معاني القرآن الكريم بلغة غير المسلم ثم يليه في قائمة الإهداء هذا الكتاب، ثم بقية الكتب الدعوية الأخرى.',
'Een korte; geïllustreerde handleiding om de Islaam beter te begrijpen',
'Een korte; geïllustreerde handleiding om de Islaam beter te begrijpen',
'http://www.islamhouse.com/p/172707',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_brief_illustrated_guide_to_understanding_islam.pdf',
'Ibrahiem Aboe Harb',
'',
'',
'Association Tabligh Al-Islam - Vereniging Tabligh Al-Islam'),

'30'=>array(
'30',
'Nederlands',
'الدين الصحيح',
'الدين الصحيح: كتابٌ قيمٌ للذين يبحثون عن الحق، فهو يهدي الباحثين للطريق الصحيح، يدعو للتفكُّر في حقائق الدين، ويبين العلاقة بين الخالق والمخلوق.',
'Het ware geloof',
'De islam is de ware godsdienst van Allah en zodoende vertegenwoordigt de naam van deze godsdienst het basisprincipe van Allahs (Gods) religie: de totale overgave aan de wil van Allah God.',
'http://www.islamhouse.com/p/161316',
'http://d1.islamhouse.com/data/nl/ih_books/single/nl_True_religion.pdf,http://d1.islamhouse.com/data/nl/ih_books/single/nl_True_religion.doc',
'Bilal Filiebs',
'',
'Aboe Abdellah Albelgiki',
'Association Tabligh Al-Islam - Vereniging Tabligh Al-Islam')

);
?>