<?php
$BOOKS = array(
'1'=>array(
'1',
'Polski',
'عيسى ومحمد عليهما السلام في الكتاب المقدس والقرآن',
'هذه الرسالة تلقي الضوء على سيدنا عيسى وسيدنا محمد - عليهما السلام - وفقاً لم جاء في الكتاب المقدس والقرآن الكريم؛ فهو يساعد على النظر في المذاهب الأساسية للمسيحية ومشاهدة الفرق بين تعاليم الكتاب المقدس وتعاليم المسيحية الحديثة.',
'Jezus i Muhammad pokój z nimi według Biblii i Koranu Z punktu widzenia Muzułmanów',
'Książka dotycząca osoby Jezusa (pokój z nim) a także Muhammada (pokój z nim) pisana z perspektywy muzułmańskiej, wsparta cytatami zarówno koranicznymi, jak i biblijnymi zaczerpniętymi tak ze Starego, jak i Nowego Testamentu. Pomaga spojrzeć na podstawowe doktryny chrześcijańskie i dostrzec różnice pomiędzy naukami biblijnymi a naukami współczesnego chrześcijaństwa.',
'http://www.islamhouse.com/p/333965',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_jesus_and_muhammad.pdf',
'',
'',
'',
''),

'2'=>array(
'2',
'Polski',
'البدعة تعريفها - أنواعها - أحكامها',
'البدعة تعريفها - أنواعها - أحكامها: هذه مقالة لفضيلة الشيخ صالح بن فوزان - حفظه الله - تحدث فيها عن معنى البدعة لغةً واصطلاحًا، وأنواع البدعة، ثم بيَّن حكم الشرع في البدع بجميع صورها وأشكالها، ونبَّه على خطأ تقسيم البدعة إلى حسنة وسيئة، ثم في الأخير ذكر تاريخ ظهور البدع في حياة المسلمين.',
'Każda innowacja jest zbłąkaniem',
'Dogłębne opracowanie poruszające problem innowacji w Islamie – ich znaczenie, kategorie, niebezpieczeństwa i rozwiązania.',
'http://www.islamhouse.com/p/328418',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Kazda_innowacja_jest_zblakaniem.pdf',
'',
'',
'',
''),

'3'=>array(
'3',
'Polski',
'شرح السنة',
'شرح السنة : هذا الكتاب يظهر للقارئ من خلال قراءته أهميته وجودته فقد قرب مفاهيم العقيدة السلفية للناس بأسلوب سهل ميسر، وأظهر نصرة السنة ومحاربة البدعة، وشدد الإنكار على أهل الأهواء المضلة، وخلصه من دنس علم الكلام.',
'Sharh-us-Sunnah',
'Książka ta ukazuje czytelnikowi jak ważne jest poznawanie Sunny w czystej postaci i właściwe zrozumienie religii oraz podążanie za Prorokiem (pokój i błogosławieństwo Allaha z nim) i jego Towarzyszami, którzy trzymali się właściwej drogi.',
'http://www.islamhouse.com/p/328414',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Sharh_Sunnah.pdf',
'',
'',
'',
''),

'4'=>array(
'4',
'Polski',
'المسيح في القرآن',
'-',
'Jezus w Islamie',
'Celem tego opracowania jest ukazanie przesłania Jezusa, pokój z nim, w świetle ostatniego objawienia zesłanego ludzkości – Koranu.',
'http://www.islamhouse.com/p/328410',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_jezus_w_islamie.pdf',
'',
'',
'',
''),

'5'=>array(
'5',
'Polski',
'الخشوع في الصلاة',
'رسالة مختصرة تبين أهمية الخشوع في الصلاة.',
'Serce w modlitwie',
'Ten krótki esej omawia stan, jaki serce muzułmanina powinno osiągnąć podczas modlitwy.',
'http://www.islamhouse.com/p/328404',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Serce_w_modlitwie.pdf',
'',
'',
'',
''),

'6'=>array(
'6',
'Polski',
'الأساليب النبوية في معالجة الأخطاء',
'الأساليب النبوية في معالجة الأخطاء : رسالة مختصرة في بيان بعض أساليب النبي - صلى الله عليه وسلم - في معالجة الأخطاء؛ حيث إن أساليبه - عليه الصلاة والسلام - أحكم وأنجع واستعمالها أدعى لاستجابة الناس، واتباع المربي لهذه الأساليب والطرائق يجعل أمره سديدا وسلوكه في التربية مستقيما. ثمّ إن اتباع المنهج النبوي وأساليبه فيه الاتساء بالنبي - صلى الله عليه وسلم - الذي هو أسوة حسنة لنا ويترتب على ذلك حصول الأجر العظيم من الله تعالى إذا خلصت النية.',
'Sposoby Proroka na poprawianie ludzkich błędów',
'Książka mająca na celu pomóc nam poznać i zrozumieć metodologię Proroka w radzeniu sobie z ludzkimi błędami.',
'http://www.islamhouse.com/p/328402',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Sposoby_Proroka_na_poprawianie_ludzkich_bledow.pdf',
'',
'',
'',
''),

'7'=>array(
'7',
'Polski',
'مقدمة في علوم الحديث',
'رسالة مختصرة تبين ماهية علوم الحديث وأهدافه، وأهمية الإسناد. الرسالة منتقاة من كتاب الأستاذ صهيب حسن - أثابه الله - وعدة مواقع أخرى بواسطة الأخت إيمان.',
'Terminologia Hadisów [Mustalah al-Hadis]',
'Książka ta ma na celu pokrótce wyjaśnić klasyfikację i proces zachowania hadisów, w których Prorok Muhammad (pokój z nim) objaśnił wierzącym bardzo ważne kwestie dotyczące życia tego i przyszłego.',
'http://www.islamhouse.com/p/328400',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Mustalah_alHadis.pdf',
'',
'',
'',
''),

'8'=>array(
'8',
'Polski',
'لماذا نصلي؟',
'لماذا نصلي؟: لا يخفى على كل مسلم مكانة الصلاة في دين الله، ومنزلتها في شرع الله، فهي عمود الإسلام، والفاصل بين الكفر والإيمان، ولذلك كان هذا الكتاب يتحدَّث عن الصلاة وفضلها وحكم تاركها وأحكامها.',
'Dlaczego Powinniśmy się modlić?',
'Modlitwa jest jednym z filarów islamu, jest tym, co odróżnia wierzącego od niewiernego. Książka ta pokazuje dlaczego powinniśmy się modlić, w jaki sposób powinniśmy to robić, jakie warunki musi spełnić modlitwa, aby została przyjęta, jakie ma znaczenie i jakie przynosi nam korzyści.',
'http://www.islamhouse.com/p/328398',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Dlaczego_Powinnismy_sie_modlic.pdf',
'',
'',
'',
''),

'9'=>array(
'9',
'Polski',
'هل عقيدة التثليث وحي إلهي؟',
'يقول المؤلف في مقدمته للكتاب: "لا شيء يؤذي النصارى أكثر من إثارة الشكوك حول عقيدة التثليث التي تعد صلب عقيدتهم. منذ أن نشأت في حجر النصرانية وأنا أعرف بالفطرة أنه سيؤذي أي نصراني متمسك بدينه أن يرتبك، ويشك في شيء يعلم صحته وقدسيته. لكن في القابل من الأيام عندما أعرف أكثر وأكثر سأكون بعيدًا كل البعد عن مفهوم التقوى في النصرانية لأنني سأكون مضطرًا إلى تنفيذ وصايا الرب لإرشاد الذين ضلوا بسبب هذه العقيدة الفاسدة. إنه لمن أبسط الحقوق لكل شخص أن يعرف الحق الذي يرشده ويهديه إلى الصراط المستقيم."',
'Czy doktryna Trójcy pochodzi od Boga?',
'Książka dostarcza odpowiedzi m.in. na pytanie kiedy i w jaki sposób doktryna Trójcy została włączona do wiary chrześcijańskiej.',
'http://www.islamhouse.com/p/328270',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Czy_doktryna_Trojcy_pochodzi_od_Boga.pdf,http://d1.islamhouse.com/data/pl/ih_books/single/pl_Czy_doktryna_Trojcy_pochodzi_od_Boga.doc',
'',
'',
'',
''),

'10'=>array(
'10',
'Polski',
'ما الغرض من الحياة؟',
'-',
'Jaki jest cel naszego życia?',
'Jaki jest cel naszego życia? Czy naszym celem na tym świecie jest po prostu jedzenie, spanie ubieranie się, praca, zdobywanie rzeczy materialnych i dobra zabawa? Czy na tym polega życie? Po co się urodziliśmy? Co jest przedmiotem naszego istnienia? I jaka mądrość stoi za stworzeniem ludzi i otaczającego nas wszechświata? Autor niniejszej książki pragnie zachęcić czytelnika do refleksji, kierując jego myśli ku temu, co w życiu naprawdę się liczy.',
'http://www.islamhouse.com/p/328267',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Jaki_jest_cel_naszego_zycia.pdf,http://d1.islamhouse.com/data/pl/ih_books/single/pl_Jaki_jest_cel_naszego_zycia.doc',
'',
'Monika Meziani',
'',
''),

'11'=>array(
'11',
'Polski',
'الإسلام والجنس',
'-',
'Islam a seks',
'Islam uważa ludzki popęd seksualny za jedną z wielu naturalnych potrzeb człowieka, które należy zaspokoić. Co więcej, traktuje go jako rzecz mile widzianą i pożądaną, pod warunkiem, że jest zaspokajany w granicach określonych przez Boga, nie zaś w sposób przez Niego niedozwolony. Więcej na ten temat dowiedzieć się można z niniejszej książki.',
'http://www.islamhouse.com/p/264561',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Islam_a_seks.pdf',
'عبد الرحمن بن عبد الكريم الشيحة',
'',
'',
''),

'12'=>array(
'12',
'Polski',
'الدليل المصور الموجز لفهم الإسلام',
'كتاب الدليل المصور الموجز لفهم الإسلام باللغة البولندية، والذي يتحدث بصفة خاصة عن الإعجاز العلمي في الإسلام، وأيضاً يُعنى بمفاهيم الإسلام وتصوره تجاه الفرد والمجتمع، والمكاسب التي تتحقق لك حالة كونك مسلماً ملتزماً بتعاليم الشريعة الإسلامية. هذا الكتاب تصدر قائمة الكتب الدعوية الموجهة لغير المسلمين في عظيم أثره، لذا يحرص المتخصصون في التعريف بالإسلام بالبدء بإهداء ترجمة معاني القرآن الكريم بلغة غير المسلم ثم يليه في قائمة الإهداء هذا الكتاب، ثم بقية الكتب الدعوية الأخرى.',
'Krótki ilustrowany przewodnik do zrozumienia Islamu',
'Niniejszy przewodnik jest doskonałą pozycją dla niemuzułmanów pragnących poznać i zrozumieć islam, muzułmanów i ich świętą Księgę - Koran. Zawiera wiele informacji - także naukowych, wzbogacony jest też o liczne przypisy, ilustracje i obszerną bibliografię. Został sprawdzony i zatwierdzona przez wiele wykształconych osób, w tym profesorów.',
'http://www.islamhouse.com/p/232342',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Krotki_ilustrowany_przewodnik_do_zrozumienia_Islamu.pdf,http://d1.islamhouse.com/data/pl/ih_books/single/pl_Krotki_ilustrowany_przewodnik_do_zrozumienia_Islamu.doc',
'',
'Monika Meziani',
'',
''),

'13'=>array(
'13',
'Polski',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة : التحليل العادل والجواب الشافي عن الأسئلة التالية: هل اليهودية والمسيحية والإسلام يشتركون في نفس العقائد الخاصة بالمرأة؟ هل حقاً اليهودية والمسيحية أكرموا المرأة أكثر من الإسلام؟ ما الحقيقة؟',
'Kobieta w tradycji Islamskiej i Judeochrześcijańskiej',
'Dziś często mówi się o statusie kobiety w islamie, jednak opierając się na stereotypach zamiast na faktach. Niniejsza książka ma na celu nie tylko pokazanie jaki jest prawdziwy status kobiety w islamie, lecz także porównanie go z obrazami kobiety w judaizmie i chrześcijaństwie (w oparciu o Święte Księgi i teksty każdego z tych trzech wyznań).',
'http://www.islamhouse.com/p/191536',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_women_in_islam_and_women_in_the_jewish_and_christian_faith.pdf,http://d1.islamhouse.com/data/pl/ih_books/single/pl_women_in_islam_and_women_in_the_jewish_and_christian_faith.doc',
'',
'',
'',
''),

'14'=>array(
'14',
'Polski',
'الإله في النصرانية .. ما طبيعته؟',
'الإله في النصرانية .. ما طبيعته؟ : القصد من هذا العمل هو عرض الحقيقة بكل أمانة وصدق.',
'Bóg w chrześcijaństwie Jaka jest Jego Natura?',
'Krótka broszura skłaniająca chrześcijańskich czytelników do refleksji na temat postrzegania Boga. Jaka jest Jego prawdziwa natura? Co na ten temat mówi Biblia?',
'http://www.islamhouse.com/p/191344',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_god_in_christianity.pdf',
'',
'',
'',
''),

'15'=>array(
'15',
'Polski',
'الدين الصحيح',
'يتناول هذا الكتاب: • شرحاً موجزاً للدين الإسلامي، وأنه الدين الصحيح الذي لا يقبل الله ديناً سواه. • استعراض الأديان والمبادئ الأخرى وبيان بطلانها. • حقيقة عيسى وأمه - عليهما السلام -. • عالمية الدين الإسلامي والحكمة في خلق الثقلين.',
'Prawdziwa religia',
'-',
'http://www.islamhouse.com/p/120437',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Prawdziwa_religia.pdf,http://d1.islamhouse.com/data/pl/ih_books/single/pl_Prawdziwa_religia.doc',
'',
'',
'',
''),

'16'=>array(
'16',
'Polski',
'رسالة واحدة فقط!',
'رسالة واحدة فقط!: يتكلم هذا الكتاب عن رسالة التوحيد الواحدة التي حملها جميع الأنبياء والرسل من لدن آدم - عليه السلام - إلى نبينا محمد - صلى الله عليه وسلم -. ويمتاز .. بإثبات توحيد (وحدانية) الله من كتب اليهود والنصارى (العهد القديم والعهد الجديد) التي بين أيديهم في وقتنا المعاصر.',
'Tylko Jedno Przesłanie!',
'Od stworzenia pierwszego człowieka – Adama, Bóg objawiał ludziom Swoją Wolę. Powoływał wielu Proroków, m.in. Noego, Abrahama, Mojżesza, Jezusa i Muhammada (pokój z nimi). Wszyscy oni zostali wysłani z tym samym przesłaniem: Prawdziwy Bóg jest tylko jeden i tylko Jego należy czcić. Czytamy o tym tak w Biblii, jak i w Koranie. Książka ta pokazuje jak jasny jest to przekaz i skłania czytelnika do refleksji.',
'http://www.islamhouse.com/p/60075',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Tylko_Jedno_Przeslanie.pdf',
'',
'',
'',
''),

'17'=>array(
'17',
'Polski',
'خطواتي الأولى في الإسلام',
'هذا الكتاب يبين أساسيات دين الإسلام، والواجبات على المسلم.',
'Moje pierwsze kroki w islamie',
'Książka zaznajamiająca czytelnika z podstawami islamu, głównymi wierzeniami, obowiązkami muzułmanina, oraz ukazująca dlaczego tak ważnym jest podążanie za religią daną od Boga.',
'http://www.islamhouse.com/p/2201',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Moje_pierwsze_kroki_w_islamie.pdf,http://d1.islamhouse.com/data/pl/ih_books/single/pl_Moje_pierwsze_kroki_w_islamie.doc',
'عبد الرحمن بن عبد الكريم الشيحة',
'',
'',
''),

'18'=>array(
'18',
'Polski',
'المرأة في ظلال الإسلام',
'المرأة في ظلال الإسلام: هذا الكتاب يبين نظرة الأديان والشعوب المختلفة للمرأة، وكيف أعطى الإسلام للمرأة حقوقها كاملة، وأهمية دور المرأة المسلمة في الحياة.',
'Status kobiety w islamie',
'Istnieje wiele stereotypów na temat pozycji kobiety w islamie. A jak wygląda prawda? Książka ta ukazuje jaki naprawdę jest status kobiety w islamie, jaką rolę odgrywa ona w społeczeństwie, jakie są jej prawa zagwarantowane przez Boga.',
'http://www.islamhouse.com/p/2199',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Status_kobiety_w_islamie.pdf,http://d1.islamhouse.com/data/pl/ih_books/single/pl_Status_kobiety_w_islamie.doc',
'عبد الرحمن بن عبد الكريم الشيحة',
'',
'',
''),

'19'=>array(
'19',
'Polski',
'ما يجب معرفته عن الطهارة',
'الإسلام هو دين النقاء، ليس روحياً فقط، بل وجسدياً أيضاً، وهذا الكتاب يبين كل ماتحتاج إلى معرفته عن الطهارة اللازمة لأداء بعض العبادات.',
'Co należy wiedzieć o czystości - ‘tahara’',
'Islam jest religią czystości, nie tylko duchowej, ale i fizycznej. Książka ta mówi wszystko, co należy wiedzieć o oczyszczeniu – ‘tahara’ – niezbędnym do wykonywania pewnych aktów czci.',
'http://www.islamhouse.com/p/2197',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Co_nalezy_wiedziec_o_czystosci_tahara.pdf,http://d1.islamhouse.com/data/pl/ih_books/single/pl_Co_nalezy_wiedziec_o_czystosci_tahara.doc',
'عبد الرحمن بن عبد الكريم الشيحة',
'',
'',
''),

'20'=>array(
'20',
'Polski',
'محمد رسول الله صلى الله عليه وسلم',
'تحتوي هذه الرسالة على تعريف مختصر بسيدنا محمد - صلى الله عليه وسلم - من حيث التعريف بنسبه ومولده ونشأته وبعض صفاته وآدابه وأخلاقه، مع ذكر بعض أقوال المستشرقين، ثم بيان بعض الأدلة الدالة على رسالته ونبوته، وماتقتضيه الشهادة بأن محمداً رسول الله.',
'Muhammad Wysłannik Boży -pokój z Nim-',
'Kiedy mówimy o Wysłanniku Muhammadzie, to mówimy o największej doskonałej ludzkiej postaci wszechczasów. Kto odstawi na bok religijny fanatyzm i osobiste upodobania i zacznie studiować historię życia Proroka, zapoznając się z jego moralnym zachowaniem i szlachetnymi cechami charakteru, ten z pewnością zaświadczy o jego wielkiej i doskonałej osobowości. Niektórzy sprawiedliwi i uczciwi nie-muzułmanie także to poświadczają.',
'http://www.islamhouse.com/p/2195',
'http://d1.islamhouse.com/data/pl/ih_books/single/pl_Muhammad_Wysłannik_Bozy.pdf,http://d1.islamhouse.com/data/pl/ih_books/single/pl_Muhammad_Wysłannik_Bozy.doc',
'عبد الرحمن بن عبد الكريم الشيحة',
'',
'',
'')

);
?>