<?php
$BOOKS = array(
'1'=>array(
'1',
'Português',
'رسالة الإسلام',
'الإسلام هو الدين الوحيد الذي ارتضاه الله للبشرية جمعاء، ولن يقبل الله من أحد دينا سواه، وهو الدين الذي يقدم حلولاً لجميع المشاكل التي يعيشها عالمنا اليوم، وإن الأخذ به وتطبيقه كفيل للقضاء عليها، ورسالته شاملة كاملة لجميع مناحي الحياة وشعبها. وهذا الكتاب يحتوى على بيان رسالة الإسلام الخالدة من أصوله ومبادئه الأساسية متمثلة في أركان الإسلام والإيمان، وبيان خصائصه ومحاسنه متمثلة في أحكامه وشرائعه، كما يحتوي على بيان الأوضاع الاقتصادية والاجتماعية والسياسية والأخلاقية وحقوق الإنسان في الإسلام.',
'A Mensagem do Islam',
'O Islam é a religião que concorda com as disposições naturais do homem. Ela encoraja os muçulmanos e os chama para que perguntem sobre as coisas que são incompreensíveis a eles, através da consultas às autoridades competentes e versadas. No Islam não há coisas obscuras ou misteriosas; ela nos permite perguntar sobre todas as coisas.',
'http://www.islamhouse.com/p/378794',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_A_Mensagem_do_Islam.pdf,http://d1.islamhouse.com/data/pt/ih_books/single/pt_A_Mensagem_do_Islam.doc',
'',
'Ninevah Barreiros',
'Rodrigo Oliveira',
''),

'2'=>array(
'2',
'Português',
'دليل المسلم الجديد',
'كتاب نهديه لكل مسلم جديد عرف طريقه إلى ربه نبصره ونرشده نعينه ونقومه حتى يظل متمسكاً بدينه قوياً متيناً . كتاب من شيخينا المبجل جمال الدين زارابوزو وضع فيه الخطوط العريضة التي يسير عليها المسلم الجديد وعرفه بمزايا الإسلام وفضله عليه ليتمسك بعراه وبين له بطريقة سهلة جوانب الدين كله من إيمان وإسلام . أورد الشيخ شرحاً سهلاً لأركان الايمان التي تقوم عليها عقيدة المرء ، وأيضاً مباني الاسلام الخمسة المشتملة على أجل الأعمال البدنية بعد أجل عمل قلبي وهو التوحيد لله رب العالمين. وبما أن الإسلام دين اجتماعي بين الشيخ السلوك الذي يجب أن يكون عليه المسلم نحو جميع أفراد المجتمع من صغر ومن كبر ممن وافقه في اعتقاده وممن خالفه ، وأيضاً تعاملاته المالية ما يحل منها وما يحرم. ثم يبين الشيخ بعدها العوامل التي يزيد بها إيمان المرء وتعينه على الألتزام بأوامر ربه جل وعلا ، ثم وضح العقبات التي تقف بين العبد وربه من شبهات وشهوات، و أردف ذلك بذكر شروط التوبة التي تكون بين العبد وربه بلا واسطة ، ثم بعدها كلمة أخيرة للمسلم الجديد.',
'Manual Para o Novo Muçulmano',
'Manual Para o Novo Muçulmano',
'http://www.islamhouse.com/p/371348',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_Manual_Para_o_Novo_Muculmano_revisado.pdf,http://d1.islamhouse.com/data/pt/ih_books/single/pt_Manual_Para_o_Novo_Muculmano_revisado.doc',
'',
'',
'',
''),

'3'=>array(
'3',
'Português',
'تفسير العشر الأخير من القرآن الكريم ويليه أحكام تهم المسلم',
'تفسير العشر الأخير من القرآن الكريم ويليه أحكام تهم المسلم: هو كتاب مختصر يحوي أهم ما يحتاجه المسلم في حياته من قرآن وتفسير وأحكام فقهية وعقدية وفضائل و غيرها، والكتاب ينقسم إلى جزئين: فأما الجزء الأول فيشتمل على الأجزاء الثلاثة الأخيرة من القرآن الكريم مع تفسيرها من كتاب زبدة التفسير للشيخ محمد الأشقر. وأما الجزء الثاني فيحتوي على أحكام تهم المسلم، وهي: أحكام التجويد، 62 سؤالا في العقيدة، حوار هادئ عن التوحيد، أحكام الاسلام [ الشهادتان، الطهارة، الصلاة، الزكاة، الحج ]، فوائد متفرقة، الرقية، الدعاء، الأذكار، 100 فضيلة و 70 منهيًا، صفة الوضوء والصلاة مصورة، رحلة الخلود.',
'Explicação do último décimo do Alcorão',
'O Alcorão é a palavra eterna de Allah (subhanahuua ta´ala) e a superioridade de Suas palavras é igual à Sua superioridade sobre Sua criação, assim, a leitura do Alcorão é a melhor ação com a qual a língua pode se ocupar.',
'http://www.islamhouse.com/p/370159',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_Explanation_of_the_Last_Tenth_of_the_Quran.pdf',
'',
'',
'',
''),

'4'=>array(
'4',
'Português',
'حصن المسلم من أذكار الكتاب والسنة',
'حصن المسلم من أذكار الكتاب والسنة: كتيب مبارك احتوى على جُلِّ ما يحتاجه المسلم من الأدعية والأذكار في يومه وليله، وما يحزبُه من أمور عارضة في شؤون حياته؛ وتم ترجمته إلى أكثر من ثلاثين لغة عالمية، وفي هذه الصفحة ترجمتها إلى اللغة البرتغالية.',
'Fortaleza do Muçulmano',
'Eu selecionei desse meu livro a parte das lembranças (adh-dhikr), que colocadas em um pequeno volume seriam fáceis de serem transportadas em viagem. Limiteime apenas a citar os dhikr contidos nos hadith (ditos do profeta) do trabalho original, também, me limitei a citar uma ou duas referências que tenham a origem do hadith. Assim, todos aqueles que desejarem mais informações sobre um específico companheiro ou mais referências sobre um hadith em particular, deverão dirigir-se ao texto original.',
'http://www.islamhouse.com/p/344717',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_Fortificac_o_do_Muculmano.pdf',
'',
'',
'',
''),

'5'=>array(
'5',
'Português',
'التوحيد أول واجب',
'التوحيد أول واجب: رسالة مهمة في تعليم التوحيد، تُبيِّن أن أول واجب على العبيد هو توحيد الله - سبحانه وتعالى -.',
'Tauhid a primeira obrigação',
'Não há dúvida que qualquer ser humano é afectado em grande escala pelo ambiente em que vive. Se o ambiente for bom, ele torna-se bom também. Se for mau, o efeito no homem terá de ser o mesmo. A primeira coisa a exercer influência na pessoa é o lar onde recebe a primeira educação. Isto porque o lar considera-se ponto de partida dos primeiros hábitos. Depois disso, vem à escola, o que nela existe e em seu redor assim como a própria conduta vigente nela. Se os conhecimentos lá ministrados forem proveitosos e a moral louvável, ele cresce virtuoso e adquire conhecimentos benéficos para a sua crença e a sua vida. E de lá sai excelente para servir a sociedade. Daí que o Islam incita a humanidade a fazer reflexão sobre o que existe no universo para que a crença do homem seja de fundamentos baseados na adoração a Allah com sinceridade e afastar-se de tudo o que contraria essa sinceridade. A crença, assim, move a pessoa a praticar virtudes que tem como fruto o amor entre as pessoas na sociedade. É essa crença que faz com que o homem sinta dentro de si que só Allah é que pode beneficiar e causar prejuízos e mais ninguém sem o querer d\'Ele.',
'http://www.islamhouse.com/p/334305',
'http://d1.islamhouse.com/data/pt/ih_books/single/Pt_Tauhid.pdf,http://d1.islamhouse.com/data/pt/ih_books/single/Pt_Tauhid.doc',
'',
'',
'',
''),

'6'=>array(
'6',
'Português',
'نبي الرحمة [ الرسالة والإنسان ]',
'قال المؤلف - وفقه الله -: « .... ولذلك رأيت أن أقوم – بدوري - وإلقاء الضوء على صفات النبي - صلى الله عليه وسلم - الدالة على رحمتة بالبشرية وأخلاقه وشمائله وخصائصه، وتعامله مع المسلمين وغيرهم، وذلك بإسلوب سهل ويسير..وقد جعلت البحث يتحدث بلسان حال علماء الغرب الذين أنصفوا رسول الإسلام - صلى الله عليه وسلم - في كتاباتهم ودراساتهم. ولقد تبين لي من خلال هذا البحث أن الكثير من علماء الغرب قد كشفوا عن الكثير والكثير من الجواهر والدرر في حياة محمد - صلى الله عليه وسلم -، فبينوا الكثير من مظاهر الرحمة والدروس والعبر في سيرة ومسيرة النبي محمد - صلى الله عليه وسلم -.. وتنبع أهمية هذا البحث؛ من كونه رسالة تعريف مبسطة لنبي الإسلام في وقت تكالبت فيه الأقلام المسمومة والألسنة الحاقدة للنيل من مكانته - صلى الله عليه وسلم -.. والدراسة إذ تُّسْهم بمحاولة توضيح صورة نبي الإسلام للعالم، تنطلق من الإيمان بأهمية شهادات العلماء الغربيين المنصفين لنبي الإسلام- صلى الله عليه وسلم -، فرب شهادة باحث غربي أوقع في قلوب الغربيين من نصوص إسلامية كثيرة! ولقد جعل البحث من أدبيات علماء الغرب وحديثهم عن فضائل النبي - صلى الله عليه وسلم -، مصدراً رئيسياً للبحث، ولم يستخدم البحث الأسلوب المعتاد أو التقليدي في الحديث عن شمائل النبي - صلى الله عليه وسلم -، بل استخدم أدبيات الغرب أنفسهم في الحديث عن أخلاقيات وشمائل النبي - صلى الله عليه وسلم -. هذا، و ركز البحث على تناول مظاهر الرحمة في شخصية محمد - صلى الله عليه وسلم -، بلغة سهلة، غير إنها تخاطب العقل، وتحرك الوجدان، واعتمدتُ على الدراسات الإستشراقية المنصفة بالأساس، إضافة إلى كتب السيرة والشمائل والحديث النبوي والدراسات العربية المعاصرة ... ».',
'O Profeta da Misericórdia',
'Quão numerosas são as guerras da mídia deflagradas para difamarem o retrato dos grandes! Quão péssimas são quando transformam os corruptos em virtuosos, os seletos em criminosos, aí vemos os meios de comunicação tendenciosos sendo trombetas que espalham seus venenos por todos os lados, abandonando a sua missão humana e vestindo o manto da humilhação e da vergonha. Esses meios tendenciosos prejudicaram a todos nós, com suas constantes acusações ao Profeta da humanidade e o mestre dos filhos de Adão. Caricaturas, livros, revistas, programas de televisão, declarações dos mais altos escalões políticos e religiosos. Sua principal função passou a ser difamar a figura de “Mohammad Ibn Abdullah” tentando atacar a sua religião, sua honra e sua conduta. São tentativas tolas que tentam atingir a maior arma que o Profeta da Islam possui, a arma da “misericórdia”. Acusam o Profeta do Islam (Deus o abençoe e lhe dê paz) na sua mais importante virtude, a virtude da misericórdia com a qual liderou o mundo. Mesmo que esse tipo de maldade não atinja o Profeta da Misericórdia, uma vez que o latido dos cães não atinge as nuvens, os muçulmanos contemporâneos não estão isentos da responsabilidade, perante Deus, Exaltado seja, além da responsabilidade perante a história humana e do Islam.',
'http://www.islamhouse.com/p/332569',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_Prophet_of_Mercy.pdf',
'',
'',
'Ahmad Mazloum',
''),

'7'=>array(
'7',
'Português',
'الشهادتان معناهما وما تستلزمه كل منهما',
'الشهادتان معناهما وما تستلزمه كل منهما: قال المؤلف في المقدمة: «فحيث إن التلفظ بالشهادتين والعمل بمقتضاهما هو الركن الأساسي للدين الإسلامي، وحيث إن جماهير أمة الدعوة يجهلون ما يراد بهما ويعتقدون أن المراد مجرد النطق بهما دون معرفة وعمل، وأن هناك من يفسرهما بما يخالف معناهما، لذا فقد أحببت أن أكتب بحثًا حول ذلك رجاء أن يستفيد منه من له قصد حسن ممن أراد الله به خيرًا».',
'Os dois testemunhos de Fé Significando e condições',
'Sendo que a pronúncia do testemunho de fé e praticá-lo corretamente é a pedra fundamental do Islam, e considerando que muitos membros da nação islâmica ignoram seus profundos significados e condições, acreditando que o objetivo é somente pronunciá-lo, e existindo também os que interpretam erroneamente, eu consenti em escrever esta pequena investigação para que se beneficiem aqueles que procuram a verdade e desejam estar e manterem-se no caminho correto.',
'http://www.islamhouse.com/p/329585',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_Os_dois_testemunhos_de_Fe.pdf,http://d1.islamhouse.com/data/pt/ih_books/single/pt_Os_dois_testemunhos_de_Fe.doc',
'',
'',
'',
''),

'8'=>array(
'8',
'Português',
'الوسطية وأثرها في حياة المسلم',
'الوسطية وأثرها في حياة المسلم: جعل الله تعالى هذا الدين وسطًا بين الأديان الأخرى، وجعل هذه الأمة وسطًا بين سائر الأمم، وبيَّن أن هذه ميزة خاصة لها، لذا وجب على هذه الأمة أن تكون وسطًا في كل شؤونها. وهذا الكتاب يذكر الأدلة من الكتاب والسنة على ذلك.',
'A Moderação e sua influencia na vida dos muçulmanos',
'Agradeço a Allah por Suas constantes graças e bênçãos, testemunho que não existe deus exceto Allah, único, e que Muhammad é Seu Mensageiro, que Allah lhe envie sua paz e bênçãos a ele, sua família e seguidores. O tema deste artigo é a moderação e sua influência na vida dos muçulmanos. É uma questão que pertence ao Islam já que Allah, Exaltado seja, descreve ao nosso povo como um povo moderado, dizendo-nos no Alcorão: “Fizemos de vocês uma comunidade moderada e justa, de modo que fossem testemunhas perante a humanidade [da chegada dos Profetas anteriores], assim como o Mensageiro será testemunho para vós”. (Alcorão 2: 143). Alem disso, todos os livros escritos por muçulmanos sunnitas e as coletâneas de Hadith enfatizam o fato de que o povo muçulmano é moderado, e que o caminho correto é a moderação mantendo-se assim longe dos extremismos.',
'http://www.islamhouse.com/p/325167',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_A_Moderacao.pdf,http://d1.islamhouse.com/data/pt/ih_books/single/pt_A_Moderacao.doc',
'',
'',
'',
''),

'9'=>array(
'9',
'Português',
'أكثر من ألف سنة في اليوم والليلة',
'كتيب مفيد يحوي ألف سنة من سنن نبينا محمد - صلى الله عليه وسلم - في المواقف المختلفة: عند الاستيقاظ، الذهاب إلى الخلاء، الوضوء، التسوك، ارتداء الحذاء والملابس، الدخول والخروج، الذهاب للمسجد، الأذان والإقامة، صلاة الليل، بالإضافة إلى سنن ما بعد الصلاة.',
'Mil Sunnas, noite y dia',
'Esse livro relata mil sunnas que o profeta praticava durante o dia e durante a noite, e suas explicações. É uma fração de sua vida que nos ajuda a nos aproximarmos dele e de Deus, o Remissório.',
'http://www.islamhouse.com/p/324733',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_1000_Sona.pdf',
'',
'',
'',
''),

'10'=>array(
'10',
'Português',
'كيفية صلاة النبي صلى الله عليه وسلم',
'كيفية صلاة النبي صلى الله عليه وسلم: ما من عبادة إلا ولها صفة وكيفية، قد تكفل الله سبحانه ببيانها، أو بينها رسوله - صلى الله عليه وسلم -، وفي هذه الرسالة بيان لصفة صلاة النبي - صلى الله عليه وسلم - قال مصنفها في مقدمته « فهذه كلمات موجزة في بيان صفة صلاة النبي - صلى الله عليه وسلم - أردت تقديمها إلى كل مسلم ومسلمة ليجتهد كل من يطلع عليها في التأسي به - صلى الله عليه وسلم - في ذلك لقوله - صلى الله عليه وسلم - { صلوا كما رأيتموني أصلي } رواه البخاري ».',
'Como rezar de acordo com a Sunna do Profeta Muhammad',
'Nesta breve obra, explicaremos como o Mensageiro de Allah fazia a oração. O Imam Bukhari registrou as seguintes palavras do Profeta Muhammad: “Realizai a oração tal como me viste fazê-la”.',
'http://www.islamhouse.com/p/324618',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_Como_rezar_de_acordo_com_a_Sunna.pdf,http://d1.islamhouse.com/data/pt/ih_books/single/pt_Como_rezar_de_acordo_com_a_Sunna.doc',
'',
'',
'',
''),

'11'=>array(
'11',
'Português',
'مفهوم الإله في الإسلام',
'مفهوم الإله في الإسلام: رسالةٌ مُوجَّهةٌ لغير المسلمين، وفيها معنى الإله في الإسلام.',
'O conceito de Deus no Islão',
'Alguns não-muçulmanos alegam que Deus no Islã é um Deus severo e cruel que exige ser obedecido completamente e, consequentemente, não é amoroso ou gentil. Nada poderia ser mais distante da verdade do que essa alegação.',
'http://www.islamhouse.com/p/317909',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_o_conceito_de_Deus.pdf',
'',
'',
'',
''),

'12'=>array(
'12',
'Português',
'مريم في الإسلام',
'مريم في الإسلام: هذا كتابٌ يُناسب غير المسلمين؛ حيث يُوضِّح مكانة السيدة مريم - عليها السلام - في الدين الإسلامي.',
'Maria no Islão',
'Maria, a Mãe de Jesus, detém uma posição muito especial no Islã, e Deus a proclama como a melhor mulher entre toda a humanidade, a quem Ele escolhe sobre todas as outras mulheres devido à sua religiosidade e devoção.',
'http://www.islamhouse.com/p/317907',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_Maria_no_Islao.pdf',
'',
'',
'',
''),

'13'=>array(
'13',
'Português',
'الحياة بعد الموت',
'الحياة بعد الموت: كتابٌ فيه بيان مفهوم العقيدة باليوم الآخر لغير المسلمين.',
'Vida após a Morte',
'Todos os profetas de Deus chamaram seus povos para adorar a Deus e para acreditar na vida após a morte. Eles deram muita ênfase na crença na vida após a morte que até a menor dúvida em relação a isso significava negar Deus, fazendo com que todas as outras crenças não tivessem sentido.',
'http://www.islamhouse.com/p/317905',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_vida_apos_a_morte.pdf',
'',
'',
'',
''),

'14'=>array(
'14',
'Português',
'قصص المسلمين الجدد',
'هذا الكتاب يحتوي على بعض قصص المسلمين الجدد.',
'Histórias de Novos Muçulmanos',
'Histórias de Novos Muçulmanos Cat Stevens, ex-Pop star, Reino Unido Jermaine Jackson, EUA Malcolm X, EUA Abdullah ibn Salam, rabino, Medina Idris Tawfiq, Padre Católico, Reino Unido Craig Robertson, Ex-Católico, Canadá Bruce Paterson, ex-cristão, Reino Unido Dr. Ali Selman Benoist, Ex-Católico, França Diane Charles Breslin, Ex-Católica, EUA Natassia M. Kelly, Ex-Cristã, EUA Angel, ex-cristã, EUA Aminah Assilmi, ex-cristã, EUA Akifah Baxter, Ex-Cristã, EUA',
'http://www.islamhouse.com/p/313536',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_historias_de_novos_muculmanos.pdf',
'',
'',
'',
''),

'15'=>array(
'15',
'Português',
'البحث عن الطمأنينة والسعادة النفسية [ البحث عن السلام الداخلي ]',
'نظرة حول طبيعة الناس في تعريفهم للطمأنينة والسعادة النفسية، وسعيهم في البحث عنها وكذلك نظرة حول ما الذي يحول بيننا وبين الطمأنينة والسعادة النفسية أن نحصلها.',
'A busca por Paz Interior',
'O tópico de paz interior aborda uma necessidade universal. Não existe ninguém nesse planeta que não deseje paz interior. Não é um desejo novo de nosso tempo; ao contrário, é algo que todos buscam através dos tempos, independentemente de cor, credo, religião, raça, nacionalidade, idade, gênero, riqueza, habilidade ou avanço tecnológico.',
'http://www.islamhouse.com/p/313534',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_a_busca_por_paz_interior.pdf',
'',
'',
'',
''),

'16'=>array(
'16',
'Português',
'زواج النبي صلى الله عليه وسلم بالسيدة عائشة عند العلماء والعقلاء والمنصفين',
'زواج النبي صلى الله عليه وسلم بالسيدة عائشة عند العلماء والعقلاء والمنصفين: يعرض المقال لبعض أقوال المستشرقين المنصفين كتمهيد، ثم رد هذه الشبهة من خلال النظر إلى طبيعة هذا الزواج، وشهادة العلم، وتسفيه الخيالات المريضة بالأدلة العلمية، ثم لمحات من بركة هذا الزواج.',
'O Casamento do Profeta (S) com Aicha (R) Para os Intelectuais, os Teólogos e os Equitativos',
'O artigo relata a opinião de orientalistas com imparcialidade e equidade a respeito do casamento do Profeta Muhammad (S) com a Aícha, esclarece duvidas surgidas a esse respeito, levando em conta o testemunho da época e o testemunho da ciência, rechaçando os pensamentos doentios com comprovantes cientificos, contém ainda alguns relatos sobre o abençoado casamento.',
'http://www.islamhouse.com/p/309062',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_O_Casamento_do_Profeta.pdf,http://d1.islamhouse.com/data/pt/ih_books/single/pt_O_Casamento_do_Profeta.doc',
'',
'',
'',
''),

'17'=>array(
'17',
'Português',
'تعريف عام بدين الإسلام',
'تعريف عام بدين الإسلام : يتألف هذا الكتاب من اثني عشر فصلاً ومقدمة وخاتمة. فأما المقدمة ففيها تصوير جميل لمعاني الفطرة والتكليف وطريقَي الجنة والنار وحقيقة الدنيا وحقيقة الآخرة، أما الفصول الاثنا عشر فتعرض أبواب الإيمان جميعاً عرضاً واضحاً موجزاً يفهمه الكبير والصغير ويستمتع به العلماء والمثقفون وعامة الناس جميعاً؛ وهذه الفصول منها ثلاثة بمثابة المدخل للموضوع والتمهيد لباقي الكتاب، وهي: دين الإسلام، وتعريفات، وقواعد العقائد. والتسعة الباقية تشرح العقيدة وتبيّنها بما أسلفتُ من تيسير وتبسيط، وهي: الإيمان بالله، وتوحيد الألوهية، ومظاهر الإيمان، والإيمان باليوم الآخر، والإيمان بالقدر، والإيمان بالغيب، والإيمان بالملائكة والجن، والإيمان بالرسل، والإيمان بالكتب.',
'Apresentação Geral da religião do Islam',
'O livro, apresenta a religião islâmica de um modo fácil, claro e diferenciado, contendo uma bela introdução para a compreensão da crença e um resumo sobre as adorações, a fé e os pilares do islam, esta edição se diferencia pelas correções e revisões feitas, além da inclusão dos versículos corânicos em árabe, prar que fique claro qua a palavra de Allah é em árabe e que a tradução é somente dos significados.',
'http://www.islamhouse.com/p/228872',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_definition_of_religion_in_islam.pdf',
'',
'',
'',
''),

'18'=>array(
'18',
'Português',
'صور من حياة الصحابة',
'صور من حياة الصحابة : هذا الكتاب يعرض صوراً من حياة مجموعة من نجوم الهداية التى نشأت فى أحضان المدرسة المحمدية بأسلوب جمع بين البلاغة الأدبية والحقيقة التاريخية .. فيجد طالب الأسلوب الإنشائي فى هذا الكتاب بغيته، وناشد الفن القصصي طلبته، والساعي إلى التأسي بالكرام ما يرضيه ويغنيه، والباحث عن الحقيقه التاريخية ما يفي بغرضه.',
'Retratos das Vidas dos Sahabas',
'O livro traz relatos da vida de um grupo de companheiros do Profeta (S),o autor de uma forma fácil e agradável,relata a vida de uma geração jamais vista pela humanidade ,objetivando revelar a gloriosa passagem deles ,o apoio ao Profeta(S),a imigração, a prática e propagação da religião, o esforço e perseverança que empenharam na divulgação da religião, entre outras coisas sobre o seus nobres adjetivos.',
'http://www.islamhouse.com/p/228868',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_pictures_from_life_of_companions.pdf',
'',
'',
'',
''),

'19'=>array(
'19',
'Português',
'قطوف من الشمائل المحمدية والأخلاق النبوية والآداب الإسلامية',
'قطوف من الشمائل المحمدية والأخلاق النبوية والآداب الإسلامية : كتاب مختصر يحتوي على قطوف من الشمائل المحمدية، حيث بين المصنف بعض أخلاق النبي - صلى الله عليه وسلم -، وآدابه، وتواضعه، وحلمه، وشجاعته، وكرمه ... إلخ من الأمور التي ينبغي أن يحرص كل مسلم أن يعرفها عن النبي - صلى الله عليه وسلم -.',
'Os Atributos do Profeta Muhammad',
'Você gostaria de conhecer o derradeiro dos profetas e mensageiros? Ele acreditou nos anteriores Livros Divinos: A Torá, o Evangelho, os Salmos e lhe foi revelado o último Livro Divino, o Alcorão Sagrado. Você deseja viver com o Profeta da misericórdia? Ele completou a mensagem dos profetas anteriores a ele, na convocação dos servos de Deus, Único, sem parceiros, como Abraão, Ismael, Isaac, Jacó, Moisés, Jesus e outros (que a paz esteja com eles). A leitura deste livro: “Os Atributos do Profeta Mohammad”, apresentando a conduta do Profeta e a ética islâmica, de autoria do Sheikh Mohammad Ibn Jamil Zino, irá lhe proporcionar uma excelente idéia a respeito da biografia da melhor das criaturas, Mohammad Ibn Abdullah (Deus o abençoe e lhe dê paz).',
'http://www.islamhouse.com/p/204522',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_Os_Atributos_do_Profeta.pdf',
'',
'',
'',
''),

'20'=>array(
'20',
'Português',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة : التحليل العادل والجواب الشافي عن الأسئلة التالية: هل اليهودية والمسيحية والإسلام يشتركون في نفس العقائد الخاصة بالمرأة؟ هل حقاً اليهودية والمسيحية أكرموا المرأة أكثر من الإسلام؟ ما الحقيقة؟',
'A Mulher no Islam',
'Gostaria de enfatizar que a minha proposta para este estudo não é denegrir o Judaísmo ou o Cristianismo. Como muçulmanos acreditamos nas origens divinas de ambos. Ninguém pode ser muçulmano sem acreditar em Moisés e Jesus como grandes profetas de Deus. A minha intenção é somente afirmar o Islam e pagar um tributo para a última mensagem verdadeira de Deus para a raça humana para a última mensagem verdadeira de Deus para a raça humana. Também gostaria de enfatizar que me preocupei somente com a Doutrina, isto é, minha preocupação é, principalmente, a posição das mulheres nas três religiões, como aparece nas suas fontes originais, e não como é praticada por seus milhões de seguidores no mundo hoje.',
'http://www.islamhouse.com/p/204510',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_women_in_islam_and_women_in_the_jewish_and_christian_faith.pdf',
'',
'',
'',
''),

'21'=>array(
'21',
'Português',
'أنت تسأل والقرآن يجيب',
'أنت تسأل والقرآن يجيب : رسالة لطيفة تحتوي على 32 سؤال أجاب عنها الكاتب من خلال آيات القرآن الكريم. 1- من هو الخالق؟ 2- من هو الله؟ 3- هل تعتقد أن الله خلقنا عبثاً بدون أي هدف؟ 4- لماذا خلق الله الخلق؟ 5- ماذا أمرنا الله أن نفعل؟ 6- من أين نطلب الرشد؟ 7- لمن نلجأ في وقت المحن والمصائب؟ 8- هل حفظ الله القرآن من التحريف؟ 9- ماذا حصل للأمم السابقة عندما عصوا الله؟ 10- لمن تجب العبادة؟ 11- ماهو دين الله؟ 12- ماهو الدين الذي ارتضاه الله لنا وابتغاه؟ 13- من أين أتى (أنزل) القرآن؟ 14- لماذا أرسل الله الرسل؟ 15- هل يجب علينا الإيمان بالرسل؟ 16- ماذا حصل للكتب السابقة؟ 17- من هو آخر الرسل؟ 18- لمن أرسل الله آخر الرسل(محمد صلى الله عليه وسلم)؟ 19- ماذا أعد الله للمؤمنين من اليهود والنصارى؟ 20- ماهو مثل عيسى عند الله؟ 21- ماذا قال الله عن مريم؟ 22- هل صلب عيسى عليه السلام؟ 23- هل عيسى ابن الله؟ 24- كيف يتحقق لنا الأمن؟ 25- ماهي الحياة الدنيا؟ 26- هل النعم التي ننعم بها من الله؟ 27- ما الذي يزيد لنا النعمه من الله؟ 28- كيف تقي نفسك من العذاب الأليم؟ 29- ماهو جزاء من اتقى بالله؟ 30- ما هو مصير المكذبين؟ 31- ماهو مصير المؤمنين؟ 32- كيف تتحقق لنا السعادة؟.',
'Você pergunta e o Alcorão responde',
'Este livro titulado Você pergunta e o Alcorão responde responde a 32 importantes perguntas que todo muçulmano deveria conhecer.',
'http://www.islamhouse.com/p/191212',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_you_ask_the_quran_answers.pdf,http://d1.islamhouse.com/data/pt/ih_books/single/pt_you_ask_the_quran_answers.doc',
'',
'',
'',
''),

'22'=>array(
'22',
'Português',
'التعريف بالإسلام والمسلمين',
'هذا الكتاب الملون يناسب غير المسلمين، وهو يعطي معلومات عن الإسلام والمسلمين وبعض الإعجازات العلمية التي ثبتت في الكتاب والسنة.',
'Compreenda o Islam e os Muçulmanos',
'O Islam não é uma religião nova, o Islam é a mesma verdade que Deus revelou por meio de seus profetas para toda a humanidade. Para um quinto da população mundial, o Islam é uma religião e um sistema de vida completo. Os muçulmanos seguem uma religião de paz, misericórdia, perdão, e a maioria nada tem a ver com os eventos extremamente graves que ficaram associados com sua fé.',
'http://www.islamhouse.com/p/167496',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_Understanding_Islam_and_Muslims.pdf',
'',
'',
'',
''),

'23'=>array(
'23',
'Português',
'عقيدة أهل السنة والجماعة',
'عقيدة أهل السنة والجماعة: تشتمل هذه الرسالة على بيان عقيدة أهل السنة والجماعة في باب توحيد الله وأسمائه وصفاته، وفي أبواب الإِيمان بالملائكة، والكتب، والرسل، واليوم الآخر، والقدَر خيره وشره.',
'A CRENÇA dos Seguidores do Profeta Muhammad e a tendência da maioria dos Muçulmanos',
'Devido à importância deste tema e à diferença de opiniões sobre o assunto, gostaria de explicar brevemente o nosso credo na crença dos Sunitas (Os seguidores do Profeta Muhammad) e a maioria dos Muçulmanos (Ahl as-Sunnah wa al-Jama\'ah). Este credo é a crença em Allah, Seus Anjos, Seus livros, Seus mensageiros, o Dia do Julgamento, e o destino, ainda que seja agradável ou desagradável.',
'http://www.islamhouse.com/p/150279',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_belief_of_ahlu_sunnah_and_jamaha.pdf,http://d1.islamhouse.com/data/pt/ih_books/single/pt_belief_of_ahlu_sunnah_and_jamaha.doc',
'',
'',
'',
'المكتب التعاوني للدعوة وتوعية الجاليات بحي الربوة بمدينة الرياض'),

'24'=>array(
'24',
'Português',
'الدليل المصور الموجز لفهم الإسلام',
'الدليل المصور الموجز لفهم الإسلام : هذا الكتاب الملون يناسب غير المسلمين، وهو يعطي معلومات عن الإسلام والمسلمين وبعض الإعجازات العلمية التي ثبتت في الكتاب والسنة.',
'Um Breve Guia Ilustrado Para Compreender o Islã',
'Esse livro é um breve guia para compreender o Islã. Se nós quisermos saber se uma religião é verdadeira ou falsa, não devemos depender de nossas emoções, sentimentos ou tradições. Ao contrário, devemos nos basear em nossa razão e intelecto. Quando Deus enviou os profetas, Ele os apoiou com milagres e evidências que provaram que eles eram verdadeiros profetas enviados por Deus, e portanto que a religião que traziam era verdadeira.',
'http://www.islamhouse.com/p/61307',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_Um_Breve_Guia_Ilustrado_Para_Compreender_o_Isla.pdf',
'',
'',
'',
''),

'25'=>array(
'25',
'Português',
'الإعجاز العلمي في القرآن والسنة [ تاريخه وضوابطه ]',
'-',
'Os Milagres Científicos no Alcorão e na Sunnah',
'-',
'http://www.islamhouse.com/p/61305',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_scientific_approach_in_quran_sunnah.pdf',
'',
'',
'',
''),

'26'=>array(
'26',
'Português',
'أركان الإسلام و الإيمان [ كتاب الطهارة ]',
'باب الطهارة من كتاب أركان الإسلام و الإيمان: ويحتوي على أبواب المياه, الوضوء, نواقض الوضوء, المسح على الخفين, الغسل, نواقض الغسل و التيمم.',
'O Livro da Purificação -Tahara-',
'O Livro da Purificação (Tahara), A categoria da água, Os tipos de banho, Como realizar o ghusl, Fatores que anulam o wudu, Passar a mão úmida sobre o pé vestido com meia ou calçado, o ghusl e o que o faz obrigatório, As coisas proibidas ao junub, Os pilares fundamentais do ghusl, A maneira de realizar o Ghusl de acordo com a Sunnah, O ghusl recomendável, Alguns assuntos relacionados com o ghusl, O taiammum (purificação com terra ou areia)',
'http://www.islamhouse.com/p/53691',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_kitab_al_tahara.pdf',
'',
'',
'',
'المكتب التعاوني للدعوة وتوعية الجاليات بحي الربوة بمدينة الرياض'),

'27'=>array(
'27',
'Português',
'الأربعون النووية',
'متن الأربعين النووية للإمام النووي - رحمه الله - متن مشهور، اشتمل على اثنين وأربعين حديثاً محذوفة الإسناد في فنون مختلفة من العلم، كل حديث منها قاعدة عظيمة من قواعد الدين، وينبغي لكل راغب في الآخرة أن يعرف هذه الأحاديث؛ لما اشتملت عليه من المهمات، واحتوت عليه من التنبيه على جميع الطاعات.',
'OS QUARENTA HADITH [DITOS]',
'Os quarenta do imam Nawawi é um texto famoso com quarenta dois hadith em campos diferentes do conhecimento. Cada hadith é considerado uma base das bases da religião',
'http://www.islamhouse.com/p/53689',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_forty_Hadith.pdf',
'',
'',
'',
'المكتب التعاوني للدعوة وتوعية الجاليات بحي الربوة بمدينة الرياض'),

'28'=>array(
'28',
'Português',
'الدين الصحيح',
'الدين الصحيح: كتابٌ قيمٌ للذين يبحثون عن الحق، فهو يهدي الباحثين للطريق الصحيح، يدعو للتفكُّر في حقائق الدين، ويبين العلاقة بين الخالق والمخلوق.',
'A Verdadeira Religião de Deus',
'Cada ser nasce em circunstâncias que, de modo algum, são de sua escolha. A religião professada pela família, ou respectiva ideologia, são-lhe impostas desde o minuto primeiro da sua existência. Ao atingir a adolescência, é normal a pessoa acreditar plenamente que, as crenças da sociedade em que se encontra inserida, são os verdadeiros credos em que todos deveriam acreditar. Contudo, algumas, ao atingirem a vida adulta e quando expostas a outros sistemas de crenças, começam a questionar a validade daquilo em que acreditam e que lhes foi transmitido.',
'http://www.islamhouse.com/p/53685',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_the_true_religion.pdf',
'',
'',
'',
''),

'29'=>array(
'29',
'Português',
'الواجبات المتحتمات المعرفة على كل مسلم ومسلمة',
'الواجبات المتحتمات المعرفة على كل مسلم ومسلمة: رسالة مختصرة ونفيسة تحتوي على الأصول الواجب على الإنسان معرفتها من معرفة العبد ربه, وأنواع العبادة التي أمر الله بها، ومعرفة العبد دينه، مع بيان شروط لا إله إلا الله، ثم بيان نواقض الإسلام، ثم بيان أقسام التوحيد مع ذكر ضده وهو الشرك، مع بيان أقسامه.',
'Fundamentos que todo muçulmano e muçulmana deve saber',
'Saiba que os três fundamentos que todo muçulmano e muçulmana deve saber são: conhecer seu Senhor, sua Religião e Seu Profeta (que a paz de Allah esteja sobre ele).',
'http://www.islamhouse.com/p/53681',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_Wajibat_al_mutakhatimat.pdf',
'',
'',
'',
'المكتب التعاوني للدعوة وتوعية الجاليات بحي الربوة بمدينة الرياض'),

'30'=>array(
'30',
'Português',
'محمد رسول الله صلى الله عليه وسلم',
'تعريف مختصر بالنبي - صلى الله عليه وسلم - من حيث التعريف بنسبه ومولده وبعض صفاته وآدابه وأخلاقه، مع ذكر بعض أقوال المستشرقين في سيدنا محمد - صلى الله عليه وسلم -.',
'Muhammad, o Mensageiro de Deus',
'Quando se fala do Profeta Muhammad deve ter-se em conta que se está falando do maior indivíduo da historia. Nenhum homem possuía as características, as atitudes e a ética que ele tinha em conjunto.',
'http://www.islamhouse.com/p/53679',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_muhammad_the_messenger_of_Allah.pdf',
'',
'',
'',
'المكتب التعاوني للدعوة وتوعية الجاليات بحي الربوة بمدينة الرياض'),

'31'=>array(
'31',
'Português',
'عيسى رسول الإسلام',
'عيسى رسول الإسلام: رسالةٌ تحتوي على الأدلة من القرآن والإنجيل على رسالة عيسى - عليه السلام - ونبوته، خلافًا لعقيدة النصارى فيه من تأليهه وادّعاء بُنوّته لله - تعالى الله عما يقولون علوًّا كبيرًا -.',
'Jesus um Profeta do Islam',
'O objetivo principal do livro Jesus um profeta do Islam, é o de apresentar a posição islâmica a respeito de Jesus, a paz esteja com ele, um dos mas favorecidos Profetas que Deus enviou como guia para as ovelhas perdidas de Casa de Israel.',
'http://www.islamhouse.com/p/2211',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_jesus_prophet_of_islam.pdf',
'',
'',
'',
'الدار العالمية للكتاب الإسلامي'),

'32'=>array(
'32',
'Português',
'المرأة في الإسلام',
'المرأة في الإسلام: هذه المقالة تُبيِّن أن مكانة المرأة رفيعة في الإسلام كأم وزوجة وابنة وأخت، وفي كل تلك المقامات لها مكانتها واحترامها، وأن أعداء الدين يحاولون دائمًا تشويه صورة المرأة في الإسلام، والطريق الوحيد للرد على شبهاتهم هو ثبات المرأة والاعتزاز بعقيدتها والتمسك بالعروة الوثقى، وبهذا ترجع عزتها وكرامتها ومكانتها في المجتمع.',
'A Mulher no Islaam',
'Este livro explica o status das mulheres no Islão e explora muitos dos conceitos errados do ocidente sobre as grandes direitas que o Islão outorgou a lha mulher.',
'http://www.islamhouse.com/p/2209',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_woman_in_islam.pdf',
'',
'',
'',
''),

'33'=>array(
'33',
'Português',
'القرآن الكريم وترجمة معانيه إلى اللغة البرتغالية',
'',
'Tradução do sentido do Nobre Alcorão para a língua portuguesa',
'Tradução dos significados do Sagrado Alcorão na língua portuguesa.',
'http://www.islamhouse.com/p/7',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_Portuguese_translation_of_the_meanings_of_quran.pdf,http://d1.islamhouse.com/data/pt/ih_books/single/pt_Gratis_Quran_Port_Final.pdf',
'',
'',
'',
'مجمع الملك فهد لطباعة المصحف الشريف'),

'34'=>array(
'34',
'Português',
'التعريف الموجز بالإسلام',
'التعريف الموجز بالإسلام: تعريف موجز بالدين الإسلامي وبيان شموليته لجميع جوانب الحياة مع بيان أهم أركانه الستة.',
'Um resumo do que é o Islam',
'O Islam é o selo de todas as mensagens divinas reveladas ao último dos profetas, Muhammad filho de Abdullah, que a paz e as bençãos de Deus esteja com ele. É a última religião e a única que será aceite por Deus; uma religião de fácil prática, sem dificuldades nem adversidades. Aquilo que uma pessoa não pode praticar, não é de forma alguma obrigada a fazê-lo',
'http://www.islamhouse.com/p/5',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_brief_definition_of_islam.pdf,http://d1.islamhouse.com/data/pt/ih_books/single/pt_brief_definition_of_islam.doc',
'Deanery investigação científica Universidade Islâmica de Medina',
'',
'',
'موقع الجامعة الإسلامية بالمدينة المنورة'),

'35'=>array(
'35',
'Português',
'الإسلام هو ...',
'الإسلام هو: كتابٌ قيِّم عرض المؤلف فيه بإيجاز التعريف بالإسلام، وبيان أنه الدين الصحيح، والدين الوحيد المُتَّبَع.',
'O Islão é…',
'-',
'http://www.islamhouse.com/p/1',
'http://d1.islamhouse.com/data/pt/ih_books/single/pt_Islam_Is.pdf,http://d1.islamhouse.com/data/pt/ih_books/single/pt_Islam_Is.doc',
'',
'',
'',
'المكتب التعاوني للدعوة وتوعية الجاليات بحي الربوة بمدينة الرياض')

);
?>