<?php
$BOOKS = array(
'1'=>array(
'1',
'Romanian',
'عتاد الجهاد والرد علي خصوم الإسلام بالحجج والبرهان',
'هذه الرسالة هي خلاصة 50 عاماً من البحث عن الحقيقة.',
'Combat Kit',
'-',
'http://www.islamhouse.com/p/338099',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Combat_Kit.pdf',
'',
'',
'',
''),

'2'=>array(
'2',
'Romanian',
'الإسلام دين الجميع',
'رسالة مختصرة تبين محاسن دين الإسلام.',
'ISLAM RELIGIA TUTUROR',
'-',
'http://www.islamhouse.com/p/338097',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Islam_religia_tuturor.pdf',
'',
'',
'',
''),

'3'=>array(
'3',
'Romanian',
'ما هو اسمه؟ [ الله في اليهودية والنصرانية والإسلام ]',
'ما هو اسمه؟ : هذا الكتاب يدور حول مفهوم الإله في الأديان المختلفة، ويبين أن الأديان كلها - فيما عدا دين الإسلام - لديها مفاهيم خاطئة - أو على أقل تقدير - ناقصة عن آلهتها، حيث تنسب إليها صفات معيبة لا تليق بجلال الخالق وكماله. وهذا الكتاب يقع في أربعة فصول: 1- عالمية الإيمان بالله. 2- المفاهيم. 3- من هو جهيوفة؟ 4- الله في الكتاب المقدس.',
'Care este Numele Lui?',
'-',
'http://www.islamhouse.com/p/338094',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Care_este_Numele_Lui.pdf',
'',
'',
'',
''),

'4'=>array(
'4',
'Romanian',
'مسألة صلب المسيح بين الحقيقة والافتراء',
'مسألة صلب المسيح بين الحقيقة والافتراء : هذا الكتاب إنما هو جديد جديد .. جديد في أسلوبه الواضح، وجديد في منهجه العلمي الذي يعتمد على " النصوص " ويعتمد على الوثائق. إنه لا يتحدث فيحتمل حديثه الصدق أو الكذب، ولكنه يدع النصوص والوثائق تتحدث، ولك أن تصدقها، ولك أن تكذبها حسب قوة الإقناع بها.',
'Crucifixion or Cruci-Fiction',
'-',
'http://www.islamhouse.com/p/338073',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Crucifixion_or_CruciFiction.pdf',
'',
'',
'',
''),

'5'=>array(
'5',
'Romanian',
'ماذا يقول الكتاب المقدس عن محمد صلى الله عليه وسلم؟',
'هذا الكتاب يحتوي على 21 صفحة، وهو صيغة حوارية بين أحمد ديدات وبعض القساوسة الذين يحاولون جاهدين إنكار البشارة بمحمد - صلى الله عليه وسلم - في الكتاب المقدس، ومع التحريف فقد فلتت بعض البشارات التي لا يمكن أن تنطبق على أحد سوى محمد صلى الله عليه وسلم.',
'Muhammed (pacea şi binecuvântarea lui Allah fie asupra sa!) în Biblie',
'-',
'http://www.islamhouse.com/p/338071',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Muhammed_in_the_Bible.pdf',
'',
'',
'',
''),

'6'=>array(
'6',
'Romanian',
'هل الكتاب المقدس كلام الله؟',
'هذه الرسالة نتاج بحث مستفيض لسنين طويلة حول حقيقة الكتاب المقدس وهل هو كلام الله؟ وبمنهج علمي دقيق، أَثبت المؤلف بطلان هذا الزعم، وعزز رأيه بأدلة وبراهين من نصوص الكتاب المقدس، وقد تم ترجمته إلى عدة لغات عالمية.',
'Este Biblia cu adevărat Cuvântul lui Dumnezeu?',
'-',
'http://www.islamhouse.com/p/338068',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Is_The_Bible_Gods_Word.pdf',
'',
'',
'',
''),

'7'=>array(
'7',
'Romanian',
'القرآن الكريم والعلم الحديث',
'الرسالة التي بين أيدينا جاءت ردًّا على طغيان المادية التي تزعم أن الدين والعلم لا يلتقيان وهي تهدف إلى تقديم دراسة مقارنة عن الكتب المقدسة في ضوء المعارف العلمية الحديثة. والكتيب عبارة عن تفريغ لمحاضرة ألقاها الدكتور موريس بوكاي، مع تحرير للنص من قبل الشيخ بلال فليبس.',
'Coranul şi ştiinţa modernă',
'Această cărticică de Dr. Maurice Bucaille a fost în circulaţie în ultimii 19 ani şi a fost un instrument foarte util în prezentarea Islamului celor nemusulmani, aşa cum a fost în aprofundarea musulmanilor în aspectele miracolelor ştiinţifice ale Coranului. Este bazată pe o copie a unei conferinţe ţinută de Dr. Bucaille în Franţa. În această ediţie, am decis să îmbunătăţesc prezentarea prin simplificarea limbajului şi editarea textului dintr-un format oral într-un format broşură. Erau trecute, de asemenea, referinţe făcute de autor în lucrarea sa "Biblia, Coranul şi Ştiinţa" care au avut nevoie de explicaţie. Mi-am permis să includ părţi explicatorii din cartea sa unde era nevoie de mai multe explicaţii. Câteva note de subsol au fost, de asemenea, adăugate pentru claritate şi un hadis menţionat de autor a fost înlocuit din cauza inautenticităţii lui. Au fost făcute, de asemenea, nişte corecturi la materialul istoric cu privire la "strângerea" părţilor din Coran. Speranţa mea este ca aceste neînsemnate îmbunătăţiri aduse să facă o treabă excelentă, chiar mai de efect, în prezentarea revelaţiei finale a lui Dumnezeu pentru omenire.',
'http://www.islamhouse.com/p/338063',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Coranul_Stiinta_Moderna.pdf',
'',
'',
'',
''),

'8'=>array(
'8',
'Romanian',
'القرآن المذهل [ القرآن المعجز ]',
'ليس المسلمون وحدهم من أطلق على القرآن الكريم أنه رائع ومدهش، وهم فقط الذين يُقدِّرون هذا الكتاب ويُجلُّونه، في الحقيقة فقد أطلق عليه غير المسلمين هذه الصفة، وحتى من أناس يكرهون الإسلام كراهية كبيرة، ما زالوا يُطلقون عليه هذه الصفة. ومن هؤلاء: أستاذ اللاهوت وعالم الرياضيات الدكتور «جاري ميلر»; إذ أسلم بسبب نظره في القرآن بقصد إخراج الأخطاء منه، فاندهش وانبهر بما فيه من عجائب.',
'Coranul uimitor',
'-',
'http://www.islamhouse.com/p/338061',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_The_Amazing_Quran.pdf',
'',
'',
'',
''),

'9'=>array(
'9',
'Romanian',
'الإسلام هو ...',
'الإسلام هو: كتابٌ قيِّم عرض المؤلف فيه بإيجاز التعريف بالإسلام، وبيان أنه الدين الصحيح، والدين الوحيد المُتَّبَع.',
'Islam este...',
'-',
'http://www.islamhouse.com/p/224796',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_islam_is_pete_seda.pdf',
'',
'',
'',
''),

'10'=>array(
'10',
'Romanian',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة : التحليل العادل والجواب الشافي عن الأسئلة التالية: هل اليهودية والمسيحية والإسلام يشتركون في نفس العقائد الخاصة بالمرأة؟ هل حقاً اليهودية والمسيحية أكرموا المرأة أكثر من الإسلام؟ ما الحقيقة؟',
'Femeile în Islam Mit şi realitate',
'-',
'http://www.islamhouse.com/p/191538',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Femeia_in_Islam.pdf',
'',
'',
'',
''),

'11'=>array(
'11',
'Romanian',
'الدليل المصور الموجز لفهم الإسلام',
'كتاب الدليل المصور الموجز لفهم الإسلام باللغة الرومانية، والذي يتحدث بصفة خاصة عن الإعجاز العلمي في الإسلام، وأيضاً يُعنى بمفاهيم الإسلام وتصوره تجاه الفرد والمجتمع، والمكاسب التي تتحقق لك حالة كونك مسلماً ملتزماً بتعاليم الشريعة الإسلامية. هذا الكتاب تصدر قائمة الكتب الدعوية الموجهة لغير المسلمين في عظيم أثره، لذا يحرص المتخصصون في التعريف بالإسلام بالبدء بإهداء ترجمة معاني القرآن الكريم بلغة غير المسلم ثم يليه في قائمة الإهداء هذا الكتاب، ثم بقية الكتب الدعوية الأخرى.',
'SCURT GHID ILUSTRAT, PENTRU A ÎNŢELEGE ISLAMUL',
'-',
'http://www.islamhouse.com/p/175558',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Scurt_Ghid_Ilustrat_pentru_a_intelege_Islamul.pdf',
'',
'',
'',
''),

'12'=>array(
'12',
'Romanian',
'الدين الصحيح',
'يتناول هذا الكتاب: • شرحاً موجزاً للدين الإسلامي، وأنه الدين الصحيح الذي لا يقبل الله ديناً سواه. • استعراض الأديان والمبادئ الأخرى وبيان بطلانها. • حقيقة عيسى وأمه - عليهما السلام -. • عالمية الدين الإسلامي والحكمة في خلق الثقلين.',
'Adevarata Religie',
'-',
'http://www.islamhouse.com/p/120439',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Adevarata_Religie.pdf,http://d1.islamhouse.com/data/ro/ih_books/single/ro_Adevarata_Religie.doc',
'',
'',
'',
''),

'13'=>array(
'13',
'Romanian',
'شخصية المرأة المسلمة كما يصوغها الإسلام في الكتاب والسنة',
'-',
'Femeia musulmana Adevărata personalitate islamică a femeii musulmane după Coran şi Sunna',
'„Femeia musulmană” reprezintă o contribuţie valoroasă pentru literatura islamică prin versetele şi hadis-urile pe care le conţine, precum şi prin modul minunat de prezentare a tuturor informaţiilor atât de folositoare pentru toţi cititorii. Structurată pe zece capitole în care se regăsesc foarte multe învăţături din Coran şi „Tradiţia Profetului” (Sunna), cartea tratează în detaliu fiecare aspect al vieţii, reuşind pe deplin să ofere o imagine cuprinzătoare a locului pe care îl ocupă femeia în societatea islamică. Adevărata personalitate a unui musulman nu se poate afla decât în învăţăturile religiei pe care o urmează, căci islamul a venit să modeleze caracterul omului, să îl îndrepte şi să îl călăuzească pe calea pe care Allah o iubeşte. Avem speranţa că cititorii noştri musulmani, şi nu numai, vor găsi în această carte un adevărat „prieten” care îi povăţuieşte şi îi îndeamnă să fie mai buni, să îşi iubească aproapele şi să se afle în orice clipă pe drumul cel drept.',
'http://www.islamhouse.com/p/108349',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Femeia_musulmana.pdf',
'',
'',
'',
''),

'14'=>array(
'14',
'Romanian',
'شخصية المسلم كما يصوغها الإسلام في الكتاب والسنة',
'شخصية المسلم كما يصوغها الإسلام في الكتاب والسنة : الإنسان المسلم كما وجهت به النصوص القرآنية والأحاديث النبوية، ينبغي أن يكون إنساناً اجتماعياً راقياً فذاً، تضافرت على تكوينه هذا التكوين الفريد مجموعة من مكارم الأخلاق. وفي هذه الكتاب بين الكاتب - وفقه الله - بعض الأخلاق التي ينبغي على المسلم أن يتحلى بها.',
'Barbatul musulman Adevărata personalitate islamică după Coran şi Sunna',
'Dr. Muhammad Ali Al-Hashimi, un foarte cunoscut scriitor al lumii arabe, reuşeşte pe deplin să redea în cărţile sale, într-un stil clar şi direct, o gamă largă de învăţături islamice, făcând astfel din lucrările sale adevărate îndrumare pentru cititori. Publicată pentru prima dată în limba arabă în anul 1981, „Bărbatul musulman” se doreşte a fi o călăuză într-o lume în care uităm adesea de lucrurile cu adevărat importante. Plină de învăţături, având ca principale surse Coranul şi „Tradiţia Profetului”, cartea dezvăluie adevăratul mod de viaţă islamic. Uşor de citit şi de înţeles, ea nu ar trebui să lipsească din biblioteca niciunui musulman. De-a lungul celor nouă capitole, cartea se referă pe rând la fiecare aspect din viaţa unui om, amintindu-ne că trebuie să trasăm întotdeana un echilibru în tot ceea ce facem, fără să acordăm mai multă atenţie unui lucru în detrimentul altuia. Trebuie să purtăm mereu în suflet versetele din Coran, să luăm aminte la „Tradiţia Profetului” (Sunna), să împlinim fapte bune şi numai atunci cu adevărat Allah va fi mulţumit de noi. „Adoraţi-L pe Allah şi nu-I asociaţi Lui nimic! Purtaţi-vă bine cu părinţii, cu rudele, cu orfanii, cu sărmanii, cu vecinul apropiat şi cu vecinul străin, cu tovarăşul de alături, cu călătorul de pe drum şi cu cei stăpâniţi de mâinile voastre drepte, căci Allah nu-l iubeşte pe cel trufaş şi pe cel lăudăros!” [Coran 4:36]',
'http://www.islamhouse.com/p/108347',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Barbatul_musulman.pdf',
'',
'',
'',
''),

'15'=>array(
'15',
'Romanian',
'كتاب الصلاة',
'-',
'Cartea rugaciunii',
'-',
'http://www.islamhouse.com/p/108345',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_The_book_of_Prayer.pdf',
'',
'',
'',
''),

'16'=>array(
'16',
'Romanian',
'قصص الأنبياء',
'قصص الأنبياء : النفس مجبولة على التأسي بغيرها، والاعتبار بما يحدث لمن حولها؛ ولذلك اعتنى القرآن الكريم بالقصص عناية كبيرة، فقد قص علينا قصصاً كثيرة لنأخذ منها العظة والعبرة، ومن القصص العظيمة التي قصها لنا القرآن، قصص الأنبياء - عليهم السلام -، ففيها عظات وعبر لا يستغني عن تدبرها المؤمن خلال سيره إلى الله تعالى. وقد قام الحافظ ابن كثير - رحمه الله - بجمع هذه القصص في كتاب، ليسهل الانتفاع بها، وقد بين قصصهم - عليهم السلام - من خلال ما جاء في آيات القرآن والأحاديث النبوية والمأثور من الأقوال والتفاسير.',
'Istorisiri despre profeti',
'În Sfântul Coran Allah Preaînaltul pomeneşte numele a douăzeci şi cinci de profeţi care au fost trimişi pe pământ. Niciun credincios nu are dreptul să tăgăduiască acest lucru. Aceştia sunt: Adam, Idris, Noe, Nuh, Salih, Avraam, Lot, Ismail, Isaac, Iacob, Iusuf, Şu’aib, Iov, Dhu-l-Kifl, Moise, Aaron, David, Solomon, Elia, Eliasar, Iona, Zaharia, Yahya, Isus şi Muhammed – Pacea şi binecuvântarea lui Allah fie asupra tuturor! Mai există de asemenea şi alţi profeţi, la care însă Coranul nu se referă în amănunt şi despre care nu se relatează nimic, ci se vorbeşte despre ei în ansamblu şi se cuvine să credem şi în aceştia, pentru că Allah a trimis pe pământ numeroşi profeţi, pentru fiecare comunitate şi grup de oameni, în diferite vremuri şi locuri. Această carte ne înfăţişează viaţa şi misiunea unora dintre aceşti douăzeci şi cinci de profeţi despre care se vorbeşte în Sfântul Coran. Menţionând un mare număr de versete din Coran, lucrarea de faţă ne dezvăluie povestea unor oameni drepţi, cu frică de Allah, care au întâmpinat numeroase greutăţi din partea neamurilor lor. Niciun profet nu a avut o misiune uşoară, căci întotdeauna mesajul Adevărului a fost întâmpinat cu necredinţă. Având ca principale surse Coranul şi Sunna (Tradiţia Profetului), „Istorisiri despre profeţi” este o carte plină de învăţături, care ne prezintă pe larg eforturile ce au fost depuse pentru a transmite mai departe mesajul credinţei drepte.',
'http://www.islamhouse.com/p/108343',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Istorisiri_despre_profeti.pdf',
'',
'',
'',
''),

'17'=>array(
'17',
'Romanian',
'أشراط الساعة',
'أشراط الساعة : تناول الباحث في هذه الرسالة أشراط الساعة الصغرى والكبرى وذلك من خلال تمهيد وبابين : أما التمهيد: فقد تحدث فيه عن أهمية الإيمان باليوم الآخر، وأثر ذلك على سلوك الفرد والمجتمع، ومظاهره، وحجية خبر الآحاد، وإخبار النبي بأشراط الساعة، وعلمها، وقربها، وأما الباب الأول: فقد تحدث فيه عن تعريف الأشراط وأقسامها، ثم الأشراط الصغرى بدءاً من بعثة النبي - صلى الله عليه وسلم - وحتى استحلال البيت الحرام وهدم الكعبة. ثم خص الباحث الباب الثاني بالأشراط الكبرى وقدم للباب بالحديث عن ترتيب الأشراط وتتابعها ثم استعرض الأشراط الكبرى وهي: المهدي والمسيح الدجال، ونزول عيسى - عليه السلام -، ويأجوج ومأجوج والخسوفات الثلاثة، والدخان، وطلوع الشمس من مغربها، وخروج الدابة، والنار التي تحشر الناس ثم الخاتمة وأهم النتائج.',
'Semnele zilei de apoi',
'Credinţa în Ziua de Apoi reprezintă unul dintre principiile de bază ale islamului. Profetul Muhammed ne-a prevenit despre semnele Ceasului din Urmă şi în această lucrare ele sunt împărţite pe categorii, după cum urmează: semne care au apărut şi s-au petrecut până acum, semne care sunt aşteptate foarte curând şi semne care se vor ivi când Ziua din Urmă va fi aproape. Viaţa pământească este o viaţă trecătoare, adevărata viaţă veşnică este în Ziua de Apoi. Să nu uităm niciodată acest lucru şi să încercăm să împlinim bine pe pământ, căci în Viaţa de Apoi, viaţa veşnică, nu vom mai putea schimba nimic şi atunci vom avea parte fie de răsplată, fie de osândă, după cum au fost şi faptele noastre aici pe pământ. Allah ne-a trimis multe semne care să ne aducă mereu aminte că există viaţă după moarte. Să luăm aminte la toate acestea. Să ne rugăm Domnului vieţii pământeşti şi Vieţii de Apoi, căci El ne va auzi, ne va ierta, ne va călăuzi şi ne va uşura calea.',
'http://www.islamhouse.com/p/108336',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Semnele_zilei_de_apoi.pdf',
'',
'',
'',
''),

'18'=>array(
'18',
'Romanian',
'رياض الصالحين',
'كتاب رياض الصالحين للإمام المحدث الفقيه أبي زكريا يحيى بن شرف النووي المتوفى سنة 676هـ - رحمه الله - من الكتب المهمة، وهو من أكثر الكتب انتشاراً في العالم؛ وذلك لاشتماله على أهم ما يحتاجه المسلم في عباداته وحياته اليومية مع صحة أحاديثه - إلا نزراً يسيراً - واختصاره وسهولته وتذليل المصنف لمادته، وهو كتاب ينتفع به المبتديء والمنتهي، وقد تُرجم إلى العديد من اللغات، وفي هذه الصفحة ترجمته إلى اللغة الرومانية.',
'Riyad As-Salihin',
'Încă de pe vremea profetului Muhammed, musulmanii au acordat un mare interes hadis-urilor şi atât în timpul vieţii sale, cât şi după moartea sa au existat mulţi musulmani care au început să redea în scris relatările Profetului, pentru ca învăţătura pe care o conţineau să rămână pentru veşnicie. Există un hadis în care se menţionează că profetul Muhammed a spus în timpul pelerinajului său de rămas-bun: „După moartea mea vă las două lucruri. Dacă vă ţineţi cu statornie de ele, n-o să vă rătăciţi niciodată de la calea cea dreaptă. Unul dintre aceste lucruri este Sfântul Coran, iar celălalt este Sunna mea sau hadis-urile. De acea, urmarea hadis-urilor este la fel de importantă ca şi respectarea poruncilor din Coran.” Considerat cel mai mare învăţat al vremii sale, imamul An-Nawawi, autorul acestei culegeri de hadis-uri, şi-a petrecut întreaga viaţă ca un om cu frică de Dumnezeu şi s-a menţinut întotdeauna pe calea dreptăţii. Fiind cea mai importantă dintre lucrările sale, Liga Islamică şi Culturală a reuşit să redea şi în limba română traducerea acesteia, pentru ca toţi cei care doresc să îşi îmbogăţească bagajul de cunoştinţe în ceea ce priveşte relatările pline de învăţăminte ale profetului Muhammed. Lucrarea de faţă menţionează 1901 de hadis-uri care, aşa cum spune însuşi autorul, „servesc ca mijloc de purificare pentru sufletele oamenilor şi le înalţă pe cel mai înalt pisc al moralităţii şi conştiinţei de Dumnezeu.” Liga Islamică şi Culturală din România are deplina convingere că această importantă lucrare îi va călăuzi pe cititori în toate aspectele vieţii, le va arăta ce e bine şi îi va ajuta să se ferească de ce e rău.',
'http://www.islamhouse.com/p/108330',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Riyad_Salihin.pdf',
'',
'',
'',
''),

'19'=>array(
'19',
'Romanian',
'عظمة محمد مجمع العظمات البشرية',
'عظمة محمد صلى الله عليه وسلم مجمع العظمات البشرية.',
'Muhammed - modelul perfect pentru omenire',
'-',
'http://www.islamhouse.com/p/108328',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Muhammed_modelul_perfect_pentru_omenire.pdf',
'',
'',
'',
''),

'20'=>array(
'20',
'Romanian',
'العمرة والحج والزيارة في ضوء الكتاب والسنة',
'-',
'Ghidul pelerinului - pentru Hajj si \'Umra',
'-',
'http://www.islamhouse.com/p/108320',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Ghidul_pelerinului.pdf',
'Sa\'id bin Ali Al Qahtany',
'',
'',
''),

'21'=>array(
'21',
'Romanian',
'الرحيق المختوم [ بحث في السيرة النبوية ]',
'الرحيق المختوم : إن حاجة الأمة إلى معرفة سيرة المصطفى - صلى الله عليه وسلم -والاقتباس من مشكاة النبوة فوق كل حاجة، بل إن ضرورتها إلى ذلك فوق كل ضرورة، وستظل السيرة العطرة الرصيد التاريخي والمنهل الحضاري، والمنهج العلمي والعملي الذي تستمد منه الأجيال المتلاحقة، من ورثة ميراث النبوة وحملة مشاعل الهداية زاد مسيرها، وأصول امتدادها، وعناصر بقائها، فكل من يرجو الله واليوم الآخر يجعل الرسول - صلى الله عليه وسلم - قدوته، والمصطفى - عليه الصلاة والسلام - أسوته: { لَقَدْ كَانَ لَكُمْ فِي رَسُولِ اللَّهِ أُسْوَةٌ حَسَنَةٌ لِمَنْ كَانَ يَرْجُو اللَّهَ وَالْيَوْمَ الْآخِرَ وَذَكَرَ اللَّهَ كَثِيراً }. ونظراً لأهمية معرفة السيرة النبوية؛ فقد أضفنا هذا الكتاب، والذي يتميز باسلويه السهل والمبسط، والكتاب حاز على الجائزة الأولى في مسابقة السيرة النبوية، التي نظمتها رابطة العالم الإسلامي عام 1396هـ.',
'Biografia nobilului profet - nectarul pecetluit',
'-',
'http://www.islamhouse.com/p/108316',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_nectarul_pecetluit.pdf',
'',
'',
'',
''),

'22'=>array(
'22',
'Romanian',
'القرآن الكريم وترجمة معانيه إلى اللغة الرومانية',
'-',
'Traducerea sensurilor Coranului cel Sfânt în limba română',
'Liga Islamica si Culturala din Romania a editat traducerile sensurilor Coranului cel sfant in limba romana in mai multe editii de-a lungul timpului, iar acum aveti facilitatea de a citi o editie online a acestuia pe noul nostru site de internet De asemenea aceasta pagina va mai ofera facilitatea de a putea downloada clipuri audio cu recitatori de Coran cunoscuti pe plan mondial',
'http://www.islamhouse.com/p/108313',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Traducerea_sensurilor_Coranului_cel_Sfant_in_limba_romana.pdf',
'',
'',
'',
''),

'23'=>array(
'23',
'Romanian',
'حصن المسلم من أذكار الكتاب والسنة',
'حصن المسلم : لمصنفه فضيلة الشيخ سعيد بن علي بن وهف القحطاني - حفظه الله - يعد من أنفس كتب أذكار عمل اليوم والليلة في حياة المسلم، وبفضل الله تمت ترجمة هذا الكتاب إلى العديد من اللغات، وحرصنا على جمعها في صفحة واحدة ومواصلة الجهود في ترجمة هذا الكتاب تحت إشراف المؤلف إلى بقية اللغات الأخرى.',
'Rugile și Pomenirile Musulmanului',
'Credinciosul se roagă întotdeauna Domnului său Atotputernic, indiferent de timp sau de loc, însă această carte vine să enumere aproximativ o sută treizeci de rugi care au un statut mai special. Profetul a spus: „Tot neamul lui Adam greşeşte, însă cei mai buni dintre cei care greşesc sunt cei care se căiesc.” Omul este predispus la greşeală, aşa stă în firea lui, însă în Ziua Judecăţii el nu va fi tras la răspundere pentru că a păcătuit, ci pentru că nu s-a căit pentru faptele sale rele. Allah este Atotputernic şi Atoateştiutor şi El pe toate le ştie, văzute şi nevăzute. Recitarea versetelor din Coran, precum şi rugăciunile, rugile şi pomenirile ne ajută să ne aflăm mai aproape de Allah şi să nu ne abatem de la calea cea dreaptă pe care El voieşte să o urmăm. „Şi Domnul vostru zice: Chemaţi-Mă şi Eu vă voi răspunde!” [Coran 40:60], aşadar să ne rugăm la Allah să ne îndrume mereu pe calea cea dreaptă, să ne rugăm pentru iertarea greşelilor, pentru pace şi să nu uităm niciodată să Îi mulţumim pentru Marea Sa Milă faţă de oameni. Liga Islamică şi Culturală s-a îngrijit de traducerea şi editatea acestei lucrări şi, în dorinţa de a-i ajuta pe toţi cei care doresc să îşi cimenteze învăţăturile islamice, prezintă toate rugile şi pomenirile atât în limba arabă şi în limba română, dar reuseşte în acelaşi timp să redea şi transcrierea fonetică a tuturor rugilor şi pomenirilor. Go to the Top',
'http://www.islamhouse.com/p/1097',
'http://d1.islamhouse.com/data/ro/ih_books/single/ro_Hisn_Almuslim.pdf',
'Sa\'id bin Ali Al Qahtany',
'',
'',
'')

);
?>