<?php
$BOOKS = array(
'1'=>array(
'1',
'Sindhi',
'تفسير العشر الأخير من القرآن الكريم ويليه أحكام تهم المسلم',
'كتاب مختصر يحوي أهم ما يحتاجه المسلم في حياته من قرآن وتفسير وأحكام فقهية وعقدية وفضائل وغيرها، والكتاب ينقسم إلى جزئين: فأما الجزء الأول فيشتمل على الأجزاء الثلاثة الأخيرة من القرآن الكريم مع تفسيرها من كتاب زبدة التفسير للشيخ محمد الأشقر. وأما الجزء الثاني فيحتوي على أحكام تهم المسلم، وهي: أحكام التجويد، 62 سؤالا في العقيدة، حوار هادئ عن التوحيد، أحكام الاسلام [ الشهادتان، الطهارة، الصلاة، الزكاة، الحج ]، فوائد متفرقة، الرقية، الدعاء، الأذكار، 100 فضيلة و 70 منهيًا، صفة الوضوء والصلاة مصورة، رحلة الخلود.',
'Explanation of the Last Tenth of the Quran Followed By Rulings that Concern Every Muslim',
'-',
'http://www.islamhouse.com/p/384095',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_Explanation_of_the_Last_Tenth_of_the_Quran.pdf',
'',
'',
'',
''),

'2'=>array(
'2',
'Sindhi',
'التوحيد والشرك في ضوء الكتاب والسنة',
'-',
'توحيد ۽ شرڪ قرآني آيتن جي روشني ۾',
'-',
'http://www.islamhouse.com/p/193731',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_monotheism_and_polytheism_in_the_light_of_the_book.pdf,http://d1.islamhouse.com/data/sd/ih_books/single/sd_monotheism_and_polytheism_in_the_light_of_the_book.doc',
'',
'',
'',
''),

'3'=>array(
'3',
'Sindhi',
'صفة الصلاة',
'ما من عبادة إلا ولها صفة وكيفية، قد تكفل الله سبحانه ببيانها، أو بينها رسوله - صلى الله عليه وسلم -، وفي هذا الكتاب بيان لصفة صلاة النبي - صلى الله عليه وسلم -',
'نماز جا مسئلا',
'-',
'http://www.islamhouse.com/p/193729',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_description_of_prayer.pdf',
'محمد اقبال ڪيلاني',
'سكندر عباسي',
'صفي الرحمن مبارڪپوري',
''),

'4'=>array(
'4',
'Sindhi',
'الشفاعة',
'-',
'شفاعت جو بيان',
'-',
'http://www.islamhouse.com/p/193727',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_intercession.pdf',
'محمد اقبال ڪيلاني',
'سكندر عباسي',
'',
''),

'5'=>array(
'5',
'Sindhi',
'التمائم في ميزان العقيدة',
'بيان موقف الشرع من التمائم.',
'التمائم في ميزان الاسلام',
'-',
'http://www.islamhouse.com/p/193725',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_tamayem_in_islam.pdf,http://d1.islamhouse.com/data/sd/ih_books/single/sd_tamayem_in_islam.doc',
'',
'',
'',
''),

'6'=>array(
'6',
'Sindhi',
'مشكاة المصابيح',
'مشكاة المصابيح : اعتمد المصنف - رحمه الله - في تأليفه على كتاب مصابيح السنة للفراء البغوي - رحمه الله -، وذلك أنه وجد هذا الكتاب أجمع كتاب صنف في باب ، وأضبط لشوارد الأحاديث وأوابدها، حيث جمع فيه معظم مايحتاجه المسلم من أحاديث العقيدة والفقه .. إلخ، ولكن صاحب المصابيح أغفل إسناد بعض الأحاديث، ولم يذكر مخرجها، فجاء الخطيب التبريزي، فذكر ما أغفله صاحب المصابيح، وأودع كل حديث في مقره. وقد سرد الخطيب التبريزي الكتب والأبواب كما سردها صاحب المصابيح، فرتب الكتب على ترتيب كتب الفقه، وقسم الكتاب إلى أبواب، وقسم كل كتاب غالباً إلى ثلاثة فصول: أولها : ما أخرجه الشيخان أو أحدهما، واكتفى بهما ( أي البخاري ومسلم)، وإن اشترك فيه الغير، لعلو درجتهما في الرواية. وثانيها : ما أورده غيرهما من الأئمة. ثالثها : ما اشتمل على معنى الباب من ملحقات مناسبة مع محافظة منه على إضافة الحديث إلى راويه من الصحابة والتابعين ونسبته إلى مخرجه من الأئمة.',
'مشڪواة المصابيح',
'-',
'http://www.islamhouse.com/p/193723',
'http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_01_mashkaat_almasabah.pdf,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_02_mashkaat_almasabah.pdf,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_03_mashkaat_almasabah.pdf,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_01_mashkaat_almasabah.doc,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_02_mashkaat_almasabah.doc,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_03_mashkaat_almasabah.doc,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_01_mashkaat_almasabah.pdf,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_02_mashkaat_almasabah.pdf,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_03_mashkaat_almasabah.pdf,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_01_mashkaat_almasabah.doc,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_02_mashkaat_almasabah.doc,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_03_mashkaat_almasabah.doc,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_01_mashkaat_almasabah.pdf,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_02_mashkaat_almasabah.pdf,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_03_mashkaat_almasabah.pdf,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_01_mashkaat_almasabah.doc,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_02_mashkaat_almasabah.doc,http://d1.islamhouse.com/data/sd/ih_books/chain/mashkaat_almasabah/sd_03_mashkaat_almasabah.doc',
'',
'',
'',
''),

'7'=>array(
'7',
'Sindhi',
'محرمات استهان بها كثير من الناس',
'محرمات استهان بها كثير من الناس : في هذه الرسالة يجد القارئ الكريم عدداً من المحرمات التي ثبت تحريمها في الشريعة مع بيان أدلة التحريم من الكتاب والسنة، وهذه المحظورات مما شاع فعلها وعم ارتكابها بين كثير من المسلمين، والله المستعان.',
'المحرمات استهان بها الناس',
'-',
'http://www.islamhouse.com/p/193721',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_prohibitions_that_are_taken_to_lightly.pdf,http://d1.islamhouse.com/data/sd/ih_books/single/sd_prohibitions_that_are_taken_to_lightly.doc',
'',
'',
'',
''),

'8'=>array(
'8',
'Sindhi',
'المنظار في بيان كثير من الأخطاء الشائعة',
'المنظار في بيان كثير من الأخطاء الشائعة : هذه الرسالة تحتوي على نصائح وتنبيهات على مخالفات للشريعة، شاع غشيانها، وكثر الجهل بحكمها.',
'المنظار في بيان كثير من الأخطاء الشائعة',
'-',
'http://www.islamhouse.com/p/193719',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_almonzar_fe_byan_kather_men_alkhta.pdf,http://d1.islamhouse.com/data/sd/ih_books/single/sd_almonzar_fe_byan_kather_men_alkhta.doc',
'',
'',
'',
''),

'9'=>array(
'9',
'Sindhi',
'اعتقاد الأئمة الأربعة',
'اعتقاد الأئمة الأربعة باللغة السندية: في هذه الرسالة بيان اعتقاد الأئمة الأربعة - أبو حنيفة، مالك، الشافعي، أحمد بن حنبل - رحمهم الله -، وأن عقيدتهم هي ما نطق به الكتاب والسُّنَّة وما كان عليه الصحابة والتابعون لهم بإحسان وليس بين هؤلاء الأئمة ولله الحمد نزاع في أصول الدين بل هم متفقون على الإيمان بصفات الرب وأن القرآن كلام الله غير مخلوق، وأن الإيمان لا بد فيه من تصديق القلب واللسان، بل كانوا ينكرون على أهل الكلام من جهمية وغيرهم ممن تأثروا بالفلسفة اليونانية والمذاهب الكلامية.',
'اعتقاد الأئمة الأربعة',
'اما بعد! مون ”امام ابو حنيفه جي نظر ۾ دين جا اصول“ جي موضوع تي ڊاڪريٽ جي ڊگري حاصل ڪرڻ لاءِ هڪ مفصل مقالو لکيو هو ۽ ان جي مقدمي ۾ ٻين ٽن امامن يعني مالڪ، شافعي ۽ احمد جي عقيدي جي تلخيص به شامل ڪري ڇڏي هئي. تنهن تي ڪن عالمن مون کان گهر ڪئي ته انهن ٽنهي امامن جي عقيدي جو ڌار ڌار ذڪر ڪريان، پر مون ائمه اربعه جي عقيدي جي ذڪر جي تڪميل جي پيشِ نظر اهو مناسب سمجهيو ته پنهنجي ڪتاب جي مقدمي ۾ جيڪي ڪجهه مون بيان ڪيو آهي، ان سان گڏ هن بحث جي به تلخيص شامل ڪري ڇڏيان، جنهن ۾ مون توحيد، تقدير ۽ ايمان ۽ اصحابين جي باري ۾ امام ابوحنيفه جي عقيدي ۽ علم ڪلام جي باري ۾ سندس موقف کي تفصيل سان بيان ڪيو آهي. الله کان دعا آهي ته اهو هن عمل کي قبوليت جي سند عطا فرمائي ۽ اسان سڀني کي پنهنجي ڪتاب ۽ پنهنجي رسول صلى الله عليه وسلم جي سنت تي هلڻ جي توفيق عطا فرمائي ۽ الله هن قصد جي پٺيان آهي ۽ اهو ئي اسان لاءِ ڪافي آهي ۽ بهترين ڪارساز آهي.',
'http://www.islamhouse.com/p/193717',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_creed_of_the_four_imams.pdf,http://d1.islamhouse.com/data/sd/ih_books/single/sd_creed_of_the_four_imams.doc',
'',
'',
'',
''),

'10'=>array(
'10',
'Sindhi',
'حصن المسلم من أذكار الكتاب والسنة',
'حصن المسلم من أذكار الكتاب والسنة : لمصنفه فضيلة الشيخ سعيد بن علي بن وهف القحطاني - حفظه الله - يعد من أنفس كتب أذكار عمل اليوم والليلة في حياة المسلم، وبفضل الله تمت ترجمة هذا الكتاب إلى العديد من اللغات، وحرصنا على جمعها في صفحة واحدة ومواصلة الجهود في ترجمة هذا الكتاب تحت إشراف المؤلف إلى بقية اللغات الأخرى.',
'دعائن جو خزانو [ حصن المسلم ]',
'-',
'http://www.islamhouse.com/p/193715',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_hisn_almuslim.pdf,http://d1.islamhouse.com/data/sd/ih_books/single/sd_hisn_almuslim.doc',
'',
'',
'',
''),

'11'=>array(
'11',
'Sindhi',
'التوحيد',
'كتابٌ في التوحيد وبيان أقسامه الثلاثة: توحيد الربوبية، وتوحيد الألوهية، وتوحيد الأسماء والصفات، وكل ذلك بالآيات الربانية، والأحاديث النبوية.',
'توحيد رباني',
'-',
'http://www.islamhouse.com/p/2369',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_Tawheed_rabane.pdf',
'بديع الدين شاه الراشدي',
'',
'',
''),

'12'=>array(
'12',
'Sindhi',
'الرحيق المختوم [ بحث في السيرة النبوية ]',
'الرحيق المختوم : إن حاجة الأمة إلى معرفة سيرة المصطفى - صلى الله عليه وسلم -والاقتباس من مشكاة النبوة فوق كل حاجة، بل إن ضرورتها إلى ذلك فوق كل ضرورة، وستظل السيرة العطرة الرصيد التاريخي والمنهل الحضاري، والمنهج العلمي والعملي الذي تستمد منه الأجيال المتلاحقة، من ورثة ميراث النبوة وحملة مشاعل الهداية زاد مسيرها، وأصول امتدادها، وعناصر بقائها، فكل من يرجو الله واليوم الآخر يجعل الرسول - صلى الله عليه وسلم - قدوته، والمصطفى - عليه الصلاة والسلام - أسوته: { لَقَدْ كَانَ لَكُمْ فِي رَسُولِ اللَّهِ أُسْوَةٌ حَسَنَةٌ لِمَنْ كَانَ يَرْجُو اللَّهَ وَالْيَوْمَ الْآخِرَ وَذَكَرَ اللَّهَ كَثِيراً }. ونظراً لأهمية معرفة السيرة النبوية؛ فقد أضفنا هذا الكتاب، والذي يتميز باسلويه السهل والمبسط، والكتاب حاز على الجائزة الأولى في مسابقة السيرة النبوية، التي نظمتها رابطة العالم الإسلامي عام 1396هـ.',
'الرحيق المختوم',
'-',
'http://www.islamhouse.com/p/2261',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_Raheeq_Makhtum.pdf',
'صفي الرحمن مبارڪپوري',
'قاضي مقصود احمد',
'',
''),

'13'=>array(
'13',
'Sindhi',
'رسالة عاجلة إلى جار المسجد',
'-',
'مسجد جوحق پاڙيسري تي',
'-',
'http://www.islamhouse.com/p/2259',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_Neighbor_of_the_Masjeed_and_Who_listen_to_the_Call.pdf',
'محمد بن عبد العزيز المسند',
'عبدالغفار جوڻيجو',
'',
''),

'14'=>array(
'14',
'Sindhi',
'كتاب النار',
'',
'دوزخ جو بيان',
'-',
'http://www.islamhouse.com/p/2257',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_Book_of_Fire.pdf',
'محمد اقبال ڪيلاني',
'سكندر عباسي',
'',
''),

'15'=>array(
'15',
'Sindhi',
'خذ عقيدتك من الكتاب والسنة',
'كتيب يحتوي على أسئلة مهمة في العقيدة، أجاب عنها المصنف مع ذكر الدليل من القرآن والسنة؛ ليطمئن القارئ إلى صحة الجواب؛ لأن عقيدة التوحيد هي أساس سعادة الإنسان في الدنيا والآخرة.',
'اسلامي تعليم',
'-',
'http://www.islamhouse.com/p/2255',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_Take_your_Belief_from_the_Quran_and_Sunnah.pdf',
'محمد جميل زينو',
'عبدالغفار جوڻيجو',
'',
''),

'16'=>array(
'16',
'Sindhi',
'القرآن الكريم وترجمة معانيه إلى اللغة السندية',
'',
'قرآن مجيد سنڌي ترجمي سان',
'-',
'http://www.islamhouse.com/p/417',
'http://d1.islamhouse.com/data/sd/ih_books/single/sd_Translation_of_the_Meaning_of_the_Holy_Quran_in_Sindhi.pdf',
'',
'تاج محمود امروٽي',
'',
'شاھ فهد ڪمپليڪس قرآن ڪريم پرنٽنگ')

);
?>