<?php
$BOOKS = array(
'1'=>array(
'1',
'Somali',
'حصن المسلم من أذكار الكتاب والسنة',
'حصن المسلم : لمصنفه فضيلة الشيخ سعيد بن علي بن وهف القحطاني - حفظه الله - يعد من أنفس كتب أذكار عمل اليوم والليلة في حياة المسلم',
'XISNUL MUSLIM DHUFEYSKA MUSLINKA',
'Fortress of the Muslim, Invocations from the Quran and Sunnah: is a very beautiful booklet consists of many authentic Dua&#039;s (supplications) for a Muslim to supplicate on a daily basis and on special occasions.',
'http://www.islamhouse.com/p/380108',
'',
'',
'',
'',
''),

'2'=>array(
'2',
'Somali',
'شرح الأربعين النووية',
'شرح الأربعين النووية: الأربعون في مباني الإسلام وقواعد الأحكام، المشهورة بمتن الأربعين النووية، وهو متن مشهور، اشتمل على اثنين وأربعين حديثاً محذوفة الإسناد في فنون مختلفة من العلم، كل حديث منها قاعدة عظيمة من قواعد الدين، وينبغي لكل راغب في الآخرة أن يعرف هذه الأحاديث؛ لما اشتملت عليه من المهمات، واحتوت عليه من التنبيه على جميع الطاعات.',
'AFARTAN XADIIS',
'-',
'http://www.islamhouse.com/p/339628',
'',
'',
'',
'',
''),

'3'=>array(
'3',
'Somali',
'فصول في الصيام والتراويح والزكاة',
'-',
'SOONKA, TARAA WIIXDA IYO SAKADA',
'-',
'http://www.islamhouse.com/p/339624',
'',
'Cabdulcasiis Xasan Yacquub',
'',
'',
''),

'4'=>array(
'4',
'Somali',
'الدروس المهمة لعامة الأمة',
'هذه الرسالة على صغر حجمها جمع المؤلف - رحمه الله - بين دفتيها سائر العلوم الشرعية من أحكام الفقه الأكبر والفقه الأصغر، وما ينبغي أن يكون عليه المسلم من الأخلاق الشرعية والآداب الإسلامية، وختم هذه الرسالة بالتحذير من الشرك وأنواع المعاصي، فأتت الرسالة بما ينبغي أن يكون عليه المسلم عقيدة وعبادةً، وسلوكا ومنهجا، فهذه الرسالة اسم على مسمى فهي بحق الدروس المهمة لعامة الأمة.',
'Duruusta Muhiimka u ah Umadda oo dhan',
'-',
'http://www.islamhouse.com/p/339604',
'',
'',
'cabdi raxmaan maxamed qeyliye',
'',
''),

'5'=>array(
'5',
'Somali',
'محرمات استهان بها كثير من الناس',
'محرمات استهان بها كثير من الناس : في هذه الرسالة يجد القارئ الكريم عدداً من المحرمات التي ثبت تحريمها في الشريعة مع بيان أدلة التحريم من الكتاب والسنة، وهذه المحظورات مما شاع فعلها وعم ارتكابها بين كثير من المسلمين، والله المستعان.',
'WAXYAALO ILAAHAY XARIMAY DADKUNA FUDUDAYSTAY IN LA ISAGA DIGANA AY WAAJIB TAHAY',
'-',
'http://www.islamhouse.com/p/339560',
'',
'',
'',
'',
''),

'6'=>array(
'6',
'Somali',
'أكثر من ألف سنة في اليوم والليلة',
'كتيب مفيد يحوي ألف سنة من سنن نبينا محمد - صلى الله عليه وسلم - في المواقف المختلفة: عند الاستيقاظ، الذهاب إلى الخلاء، الوضوء، التسوك، ارتداء الحذاء والملابس، الدخول والخروج، الذهاب للمسجد، الأذان والإقامة، صلاة الليل، بالإضافة إلى سنن ما بعد الصلاة.',
'INKA BADAN 1000 SUNO MAALINTII IYO HABEENKII',
'-',
'http://www.islamhouse.com/p/339558',
'',
'',
'C/Qaadir sh.max,ed akhii',
'',
''),

'7'=>array(
'7',
'Somali',
'تلخيص صفة صلاة النبي صلى الله عليه وسلم',
'تلخيص صفة صلاة النبي صلى الله عليه وسلم : ما من عبادة إلا ولها صفة وكيفية، قد تكفل الله سبحانه ببيانها، أو بينها رسوله - صلى الله عليه وسلم -، وفي هذه الرسالة بيان لصفة صلاة النبي - صلى الله عليه وسلم - مختصرة.',
'Siduu u tukan jirey Nebiga naxariista Eebbe iyo nabadgelyadiisa korkiisa ha ahaatee oo kooban',
'Siduu u tukan jirey Nebiga naxariista Eebbe iyo nabadgelyadiisa korkiisa ha ahaatee oo kooban',
'http://www.islamhouse.com/p/172225',
'',
'',
'',
'',
''),

'8'=>array(
'8',
'Somali',
'أحكام تجويد القرآن الكريم',
'أحكام تجويد القرآن الكريم : يتناول الكتاب أحكام تجويد كتاب الله تعالى بأسلوب مبسط ويسير مع الاستعانة بأمثلة تطبيقية من كتاب الله - عز وجل - والكتاب باللغة الصومالية.',
'Xeerarka tajwiidka Qur’aanka',
'Xeerarka qurxinta aqriska Qur’aanka, أحكام تجويد القرآن waxaan u qoray Soomaalida jecel iney bartaan, rabana inay u sii gudbiyaan caruurtooda.',
'http://www.islamhouse.com/p/61670',
'',
'',
'',
'',
''),

'9'=>array(
'9',
'Somali',
'أحسن القصص [ قصص الأنبياء ]',
'أحسن القصص [ قصص الأنبياء ] : النفس مجبولة على التأسي بغيرها، والاعتبار بما يحدث لمن حولها؛ ولذلك اعتنى القرآن الكريم بالقصص عناية كبيرة، فقد قص علينا قصصاً كثيرة لنأخذ منها العظة والعبرة، ومن القصص العظيمة التي قصها لنا القرآن، قصص الأنبياء - عليهم السلام -، ففيها عظات وعبر لا يستغني عن تدبرها المؤمن خلال سيره إلى الله تعالى. وفي هذا الكتاب ذكر لقصص الأنبياء - عليهم السلام - وذلك بصورة مختصرة، وقد استفادها الكاتب من كتاب قصص الأنبياء للحافظ ابن كثير - رحمه الله -.',
'Sheekooyinkii ugu wanaagsanaa',
'Sheekooyinkii ugu wanaagsanaa أحسن القصص waxaan u qoray Soomaalida jecel sheekooyinka Islaamiga ah, rabana inay u sii gudbiyaan caruurtooda.',
'http://www.islamhouse.com/p/61666',
'',
'',
'',
'',
''),

'10'=>array(
'10',
'Somali',
'الموجز في قواعد اللغة العربية',
'الموجز في قواعد اللغة العربية : كتاب جامع يضم بحوثاً في قواعد اللغة العربية، وكل بحث يحتوي على ما ينبغي معرفته من قواعد اللغة العربية، بالإضافة إلى ملحق خاص بالشواهد المناسبة منسوبة إلى قائليها، ويشتمل الكتاب على بحوث في الأفعال والأسماء، وبحوث صرفية وبحوث عامة، وفي هذه الصفحة اختصار للكتاب وترجمته إلى اللغة الصومالية.',
'Naxwaha carabiga oo kooban',
'Naxwaha carabiga oo kooban waxaan ka turjumay kitaabka la yiraahdo "Xeerarka afka carabiga oo kooban" الموجز في قواعد اللغة العربية ee uu qoray Siciid Maxamed Axmed oo loo yaqaan "Siciid Al-Afgaani". Mana wada turjumin naxwahaasi ee waan soo koobay.',
'http://www.islamhouse.com/p/61659',
'',
'',
'',
'',
''),

'11'=>array(
'11',
'Somali',
'قاموس صومالي عربي',
'قاموس صومالي عربي: ملف يحتوي على ترجمة بعض الكلمات من اللغة الصومالية إلى اللغة العربية.',
'Qaamuus soomaali carabi oo kooban',
'Qaamuuska soomaali carabi oo kooban waxaan u qoray Soomaalida jecel iney bartaan afka Qur’aanka kariimka.',
'http://www.islamhouse.com/p/61650',
'',
'',
'',
'',
''),

'12'=>array(
'12',
'Somali',
'قاموس عربي صومالي [ مختار الصحاح ]',
'مختار الصحاح : مختصر في علم اللغة، جمعه الشيخ محمد بن عبد القادر الرازي - رحمه الله - من كتاب الصحاح للإمام " أبي نصر إسماعيل بن حماد الجوهري "، لما رآه في كتاب " الجوهري " من ترتيب لأصول اللغة، وسماه " مختار الصحاح "، واقتصر فيه على ما لا بد لكل عالم فقيه، أو حافظ، أو محدث، أو أديب من معرفته وحفظه، لكثرة استعماله وجريانه على الألسن، فما هو الأهم فالأهم، خصوصاً ألفاظ القرآن الكريم والأحاديث النبوية الشريفة، واجتنب فيه عويص اللغة وغريبها، طالباً للاختصار وتسهيلاً للحفظ. وضمّ إليه فوائد كثيرة من تهذيب الأزهري وغيره من أصول اللغة الموثوق بها، وفي هذه الصفحة ترجمة لبعض أجزاء الكتاب إلى اللغة الصومالية.',
'Qaamuuska carabiga oo kooban',
'Qaamuuska carabiga waxaan ka turjumay qaamuuska la yiraahdo "Sixaaxii oo la soo koobay" مختار الصحاح ee uu qorey Maxamed Abuubakar Cabdulqaadir oo loo yaqaan "Ar-raazi". Mana wada turjumin qaamuuskaasi ee waan soo koobay.',
'http://www.islamhouse.com/p/61645',
'',
'',
'',
'',
''),

'13'=>array(
'13',
'Somali',
'ثلاثة الأصول وأدلتها',
'ثلاثة الأصول : رسالة مختصرة ونفيسة تحتوي على الأصول الواجب على الإنسان معرفتها من معرفة العبد ربه, وأنواع العبادة التي أمر الله بها، ومعرفة العبد دينه، ومراتب الدين، وأركان كل مرتبة، ومعرفة النبي - صلى الله عليه وسلم - في نبذة من حياته، والحكمة من بعثته، والإيمان بالبعث والنشور، وركنا التوحيد وهما الكفر بالطاغوت,والإيمان بالله.',
'SADDEXDA ASAL IYO DALIILAHOODA',
'SADDEXDA ASAL IYO DALIILAHOODA',
'http://www.islamhouse.com/p/459',
'',
'Maxamed Bin Cabdulwahaab',
'Cabdifataax Axmed',
'',
'www.iu.edu.sa'),

'14'=>array(
'14',
'Somali',
'أركان الإيمان',
'أركان الإيمان: هذه الدراسة عن أركان الإيمان هي أحد برامج العمادة العلمية، حيث وجّهت بعض أعضاء هيئة التدريس بالجامعة للكتابة في الموضوع ثمّ كلّفت اللجنة العلمية بالعمادة بدراسة ما كتبوه واستكمال النقص وإخراجه بالصورة المناسبة، مع الحرص على ربط القضايا العلمية بأدلّتها من الكتاب والسنّة. وتحرص العمادة - من خلال هذه الدراسة - إلى تمكين أبناء العالم الإسلامي من الحصول على العلوم الدينية النافعة؛ لذلك قامت بترجمتها إلى اللغات العالمية ونشرها وتضمينها شبكة المعلومات الدولية - الإنترنت -.',
'Rukniga sedaxaad',
'Rukniga sedaxaad',
'http://www.islamhouse.com/p/457',
'',
'عمادة البحث العلمي بالجامعة الإسلامية',
'عبد القادر حسين طحلو',
'',
'www.iu.edu.sa'),

'15'=>array(
'15',
'Somali',
'القرآن الكريم وترجمة معانيه إلى اللغة الصومالية',
'',
'QURAANIKA KARIIMKA Iyo Tarjamada Macnihiisa Ee Afka Soomaaliga',
'-',
'http://www.islamhouse.com/p/453',
'',
'',
'',
'',
'Wadajirka Adeegaha Labada Xaram Ee Sharafka Badan Boqor Fahad Ee Daabacaadda Jaamaca Sharafta Badan')

);
?>