<?php
$BOOKS = array(
'1'=>array(
'1',
'Shqip',
'تفسير العشر الأخير من القرآن الكريم ويليه أحكام تهم المسلم',
'كتاب مختصر يحوي أهم ما يحتاجه المسلم في حياته من قرآن وتفسير وأحكام فقهية وعقدية وفضائل وغيرها، والكتاب ينقسم إلى جزئين: فأما الجزء الأول فيشتمل على الأجزاء الثلاثة الأخيرة من القرآن الكريم مع تفسيرها من كتاب زبدة التفسير للشيخ محمد الأشقر. وأما الجزء الثاني فيحتوي على أحكام تهم المسلم، وهي: أحكام التجويد، 62 سؤالا في العقيدة، حوار هادئ عن التوحيد، أحكام الاسلام [ الشهادتان، الطهارة، الصلاة، الزكاة، الحج ]، فوائد متفرقة، الرقية، الدعاء، الأذكار، 100 فضيلة و 70 منهيًا، صفة الوضوء والصلاة مصورة، رحلة الخلود.',
'Kurani Tri pjesët e fundit nga Kurani, bashkë më një shpjegim të shkurtër të tyre',
'-',
'http://www.islamhouse.com/p/384093',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Explanation_of_the_Last_Tenth_of_the_Quran.pdf',
'Një Grup Hoxhallarësh',
'',
'',
'Uebfaqja i pjesës së Dhjetë të fundit nga Kurani - http://www.tafseer.info'),

'2'=>array(
'2',
'Shqip',
'هذا النبي محمد صلى الله عليه وسلم رسول الله إلى الناس كافة',
'هذا النبي محمد صلى الله عليه وسلم رسول الله إلى الناس كافة: كتاب يحتوي على سيرة النبي - صلى الله عليه وسلم -، وقد اشتمل على أربعة أبواب: الباب الأول: يتحدَّث عن سيرة النبي - صلى الله عليه وسلم - بصورة مختصرة. الباب الثاني: يشتمل على الفضائل والشمائل التي تحلَّى بها ودعا إليها - عليه الصلاة والسلام -. الباب الثالث: يتحدَّث عن شخصية النبي - صلى الله عليه وسلم - ودعوته تحت مجهر الشخصيات الغربية. الباب الرابع: يجمع دروسًا من سيرته ودعوته - صلى الله عليه وسلم -.',
'Ky është profeti Muhamed',
'Ky libër është një jetëpërshkrim i shkurtër i jetës së Muhamedit (Alejhis salatu ues selam). Libri përmban katër kapituj: 1. Ta njohim të Dërguarin e fundit (alejhis salatu ues selam) 2. Profeti që përsosi virtytet njerëzore. 3. Profeti (aljehis salatu ues selam) në optikën e personaliteteve botërore. 4. Disa mësime që i nxjerrim nga jeta e Profetit (alejhis salatu ues selam).',
'http://www.islamhouse.com/p/354848',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Ky_eshte_profeti_Muhamed.pdf',
'',
'',
'Sulejman Uthmani',
'Instituti Shqiptar i Qytetërimit dhe Mendimit Islam - http://www.aiitc.org'),

'3'=>array(
'3',
'Shqip',
'أجوبة على الأسئلة الشائعة لغير المسلمين حول الإسلام',
'أجوبة على الأسئلة الشائعة لغير المسلمين حول الإسلام: مجموعة من الأسئلة الشائعة التي تتبادر لأذهان غير المسلمين حول الإسلام، يجاب عنها بأجوبة سديدة في ضوء الكتاب والسنة لبيان حقيقة هذا الدين، وإجلاء المفاهيم الخاطئة.',
'Përgjigje jomuslimanëve në pyetjet më të shpeshta rreth Islamit',
'Ky libër përmban përgjigje në shumë pyetje bashkëkohore rreth Islamit të cilat shtrohen nga jomuslimanët apo edhe muslimanët e hutuar nga ajo që mediet prezantojnë për Islamin dhe muslimanët. Autori, një studiues i mirënjohur me përmasa ndërkombëtare, u jep përgjigje bindëse këtyre pyetjeve dhe demaskon shpifjet dhe paragjykimet ndaj Islamit dhe muslimanëve.',
'http://www.islamhouse.com/p/354815',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Pergjigjet_jomuslimaneve_ne_pyetjet_me_te_shpeshta_rreth_Islamit.pdf',
'Zakir b. AbdulKerim Najk',
'Fehim Dragusha',
'Driton Morina',
''),

'4'=>array(
'4',
'Shqip',
'كن مسلمًا منتجًا',
'كن مسلمًا منتجًا: مقالات رائعة جُمعت على شكل كتاب بتصميم أنيق، تجمع شتات الآداب والضوابط التي تجعل المسلم منتجًا ومثمرًا في حياته.',
'Bëhu Musliman Produktiv',
'Ky libër është përmbledhje e 2 viteve të mendimeve produktive, ideve dhe këshillave. I përpiluar nga një mori artikujsh të zgjedhur dhe me një dizajn shumë tërheqës, ka përmbledhur rregulla dhe udhëzime të ndryshme të cilat ia mundësojnë muslimanit të jetë produktiv dhe dobiprurës në jetën e tij.',
'http://www.islamhouse.com/p/354812',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Muslimani_Produktiv.pdf',
'',
'',
'',
'Uebfaqja \'Muslimani Produktiv\' - http://www.productivemuslim.com'),

'5'=>array(
'5',
'Shqip',
'الصحوة الإسلامية .. ضوابط وتوجيهات',
'الصحوة الإسلامية .. ضوابط وتوجيهات: قال المؤلف - رحمه الله -: «لا يخفى على الجميع ما منَّ الله به على الأمة الإسلامية في هذه البلاد وفي غيرها من الحركة المباركة, واليقظة الحية لشباب الإسلام, في اتجاههم الاتجاه الذي يكمّل به اتجاه السابق. هذا الاتجاه السليم الذي هدفه الوصول إلى شريعة الله من خلال كتاب الله وسنة رسوله - صلى الله عليه وسلم -. ولا شك أن هذه اليقظة وهذه الحركة - كغيرها من الحركات واليقظات الطيبة المباركة -سيقوم ضدها أعداء؛ لأن الحق كلما اشتعل نوره اشتعلت نار الباطل .. إن هذه الصحوة الإسلامية التي نجدها - ولله الحمد - في شبابنا من الذكور والإناث؛ هذه الصحوة التي ليست في هذه البلاد فحسب؛ بل في جميع الأقطار الإسلامية، إنها تحتاج إلى أمور تجعلها حركة نافعة بنَّاءة - بإذن الله تعالى -. وفيما يلي سأُبيِّن - مستعينًا بالله - هذه الأمور، وهذه الضوابط حتى تكون هذه الصحوة ناجحة ونافعة وبنَّاءة - بإذن الله تعالى -».',
'Rigjallërimi Islam - Rregulla dhe Udhëzime',
'Rigjallërimi Islam që ka përshkuar tërë botën tash e sa kohë ka nevojë për disa faktorë që të shndërrohet në një lëvizje të dobishme dhe ripërtëritëse. Ky libër në pjesën e tij të parë ofron trembëdhjetë rregulla që orientojnë këtë rigjallërim. Ndërsa në pjesën e tij të dytë, në formë të pyetjeve dhe përgjigjeve, jep udhëzime rreth shumë çështjeve që kanë të bëjnë me thirrjen në rrugë të Allahut, grupimet dhe fraksionet dhe qëndrimin kundrejt tyre dhe sjelljen në raport me ta si dhe për jomuslimanët dhe thirrjen e tyre në Islam. Libri përfundon me një shtojcë për mesataren e cila duhet të ndiqet në Dave – Thirrjen islame.',
'http://www.islamhouse.com/p/354807',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Rigjallerimi_Islam.pdf',
'Muhamed b. Salih El Uthejmin',
'Justinian Topulli',
'',
'Uebfaqja e organizatës kulturore "Tradita" - http://www.tradita.org'),

'6'=>array(
'6',
'Shqip',
'حصن المسلم من أذكار الكتاب والسنة',
'حصن المسلم من أذكار الكتاب والسنة: هو كتيب مبارك احتوى على جل ما يحتاجه المسلم من الأدعية والأذكار في يومه وليله، وما يحزبه له من أمور عارضة في شؤون حياته.',
'Mburoja e muslimanit - Lutje nga Kurani dhe Suneti',
'Mburoja e muslimanit është një libër i begatë që përmbledh lutjet dhe dhikrin (përmendjen e Allahut) për të cilin ka nevojë muslimani gjatë ditës dhe natës si dhe në raste të ndryshme me të cilat përballet gjatë jetës së tij. Ky libër është përkthyer në shumë gjuhë të botës dhe atë në miliona e miliona ekzemplarë, vetëm në islamhouse ekziston në më tepër se 30 gjuhë.',
'http://www.islamhouse.com/p/354804',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Mburoja_e_Muslimanit.pdf',
'Seid b. Ali b. Vehf El Kahtani',
'',
'Driton Lekaj',
''),

'7'=>array(
'7',
'Shqip',
'الأربعون النووية',
'الأربعون النووية: متن مشهور، اشتمل على اثنين وأربعين حديثًا محذوفة الإسناد في فنون مختلفة من العلم، كل حديث منها قاعدة عظيمة من قواعد الدين، وينبغي لكل راغب في الآخرة أن يعرف هذه الأحاديث؛ لما اشتملت عليه من المهمات، واحتوت عليه من التنبيه على جميع الطاعات؛ وقد سميت بالأربعين في مباني الإسلام وقواعد الأحكام.',
'Dyzet Hadithe nga Imam Neveviu',
'Ky është një ndër librat e shkurtra (El Metn) më të njohura. Këto dyzet hadithe janë të përmendura pa zinxhirin e transmetimit dhe përfshinë fusha të ndryshme islame, ku çdo hadith prej tyre konsiderohet si një bazë madhështore e bazave të fesë. Çdo musliman duhet t’i dijë këto hadithe për shkak të rëndësisë së mësimeve të cilat i përmbajnë.',
'http://www.islamhouse.com/p/354802',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Dyzet_hadithe_nga_Imam_Neveviut.pdf',
'Ebu Zekerija En Nevevi',
'',
'Driton Lekaj',
'Zyra e Bashkëpunimit për Dave dhe Vetëdijësim të Komuniteteve - Rebve - www.islamhouse.com'),

'8'=>array(
'8',
'Shqip',
'رفقًا أهل السنة بأهل السنة',
'رفقًا أهل السنة بأهل السنة: كتاب قيم يتحدث عن وجوب الرفق واللين مع أهل السنة وعدم القسوة عليهم في المعاملات والدعوة و كذلك عند القيام بالأمر بالمعروف والنهي عن منكر فيما بينهم.',
'Silluni butë o Pasues të Sunetit me Pasuesit e Sunetit',
'Në këtë libër Shejhu i mirënjohur, AbdulMuhsin El Abbad, flet rreth obligimit për trajtimin me butësi dhe mirësi të pasuesve të Sunetit dhe mosashpërsisë ndaj tyre në sjellje, dave dhe gjithashtu gjatë urdhërimit në të mirë dhe ndalimit nga e keqja në mesin e tyre.',
'http://www.islamhouse.com/p/354736',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Silluni_bute_o_pasues_te_Sunetit.pdf',
'Abdul Muhsin b. Hamed El Abbad El Bedr',
'Bilal Shkrepi',
'',
'Uebfaqja e organizatës kulturore "Tradita" - http://www.tradita.org'),

'9'=>array(
'9',
'Shqip',
'الضوابط الشرعية لموقف المسلم من الفتن',
'الضوابط الشرعية لموقف المسلم من الفتن: أصل هذا الكتاب محاضرة للشيخ صالح آل الشيخ - حفظه الله -، وقد فُرِّغت في رسالة. ذكر الشيخ في مقدمتها مفهوم الفتن وخطرها، وذكر فوائد التمسك بالضوابط الشرعية فيها، ومن أين استمدها. ثم عرج لذكر هذه الضوابط والتي تدل على أن المسلم ينبغي أن يراقب نفسه ويخضع حياته للضوابط الشرعية، إضافة إلى الضوابط التي تساعده على تقييم الأشخاص والمواقف المختلفة، والغرض منها تجنيب الإنسان نفسه عن الأخطاء قدر الإمكان، والفوز برضا الله - عز وجل -.',
'Rregullat fetare që duhet të ndjekë një Musliman në rast Fitnesh',
'Në këtë libër përmenden parime dhe rregulla islame shumë të rëndësishme që u vlejnë të gjithë muslimanëve, në çdo kohë dhe vend, e veçanërisht kur ata kalojnë sprova të rënda që rrezikojnë unitetin dhe bashkësinë e tyre fetare. Dijetari në parathënien e librit të tij flet për rrezikun e fitneve, dobitë e ndjekjes së këtyre rregullave dhe argumentet në të cilat i ka mbështetur këto rregulla dhe më pas ka përmendur nëntë rregulla. Që të gjitha na japin një panoramë të shkurtër dhe të përmbledhur se si muslimani gjatë gjithë jetës së tij duhet të ketë vetëkontroll në pajtim me rregullat e fesë, si duhet të vlerësojë njerëzit dhe situatat, për t’iu ruajtur sa më shumë gabimeve dhe për të fituar kënaqësinë e Allahut.',
'http://www.islamhouse.com/p/354729',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Rregullat_fetare_ne_rast_fitnesh.pdf',
'Salih b. AbdulAziz Ali Shejh',
'Justinian Topulli',
'',
'Uebfaqja e organizatës kulturore "Tradita" - http://www.tradita.org'),

'10'=>array(
'10',
'Shqip',
'الشفاعة عند أهل السنة والرد على المخالفين فيها',
'الشفاعة عند أهل السنة والرد على المخالفين فيها: يتحدَّث الكتاب عن مسألة الشفاعة التي زلَّ فيها قديمًا وحديثًا طوائف من الناس. واعتقاد أهل السنة في الشفاعة هو الاعتقاد الوسط والحق. فالمؤلف يعرض منهج أهل السنة فيها من خلال الأبواب التالية: معنى وإثبات الشفاعة مع ذكر االأدلة على ثبوتها، ثم يُعرِّج على أنواع شفاعة النبي - عليه الصلاة والسلام - وذكر غيره ممن يشفع، ثم شروط الشفاعة وأسباب حصولها، وأخيرًا يذكر الشفاعة عند المخالفين لأهل السنة ويرد عليهم، وهم قسمان: القسم الأول: المعتزلة والخوارج، والقسم الثاني: القبوريون ونحوهم.',
'Shefati, ndërmjetësimi në Ditën e Gjykimit',
'Ky libër shtjellon një ndër tematikat më të rëndësishme të akides e që është: “Shefati - Ndërmjetësimi në Ditën e Gjykimit” dhe në shtjellimin e së cilës kanë devijuar grupe të shumta. Autori sjell besimin e Ehlu Sunetit rreth Shefatit, i cili është besimi mesatar dhe i vërtetë në këtë çështje. Shejhu i nderuar e trajton këtë temë përmes disa kapitujve, si: Kuptimi i shefatit dhe argumentet që e vërtetojnë atë dhe dallimi mes shefatit në këtë botë dhe në tjetrën, llojet e shefatit të Pejgamberit (alejhis salatu ues selam) dhe kush bën shefat përveç tij, kushtet e shefatit dhe shkaqet e përfitimit të tij dhe në fund flet rreth shefatit sipas kundërshtarëve të Ehlu Sunetit dhe përgjigja ndaj tyre.',
'http://www.islamhouse.com/p/354324',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Shefati_ne_Diten_e_Gjykimit.pdf',
'Nasir b. Abdurr-Rrahman El Xhudej',
'Altin Plumbi',
'Justinian Topulli',
'Uebfaqja e organizatës kulturore "Tradita" - http://www.tradita.org'),

'11'=>array(
'11',
'Shqip',
'خير الزاد إلى يوم المعاد من غير الفريضة على هدي خير العباد',
'خير الزاد إلى يوم المعاد من غير الفريضة على هدي خير العباد: تحتوي هذه الرسالة على: أولاً: بيان بعض الأعمال التي يعود نفعها على فاعلها وحده في الدنيا والآخرة. ثانيًا: بيان بعض الأعمال التي يعود نفعها على فاعلها وغيره في الدنيا والآخرة.',
'Furnizimi më i mirë - deri në Ditën e Premtimit (Ringjalljes) veç farzit (obligimit) sipas udhëzimit të më të mirit prej njerëzve - Profetit Muhamed (lavdërimi dhe paqja e Allahut qoftë mbi të)',
'Furnizimi më i mirë - deri në Ditën e Premtimit (Ringjalljes) veç farzit (obligimit) sipas udhëzimit të më të mirit prej njerëzve - Profetit Muhamed (lavdërimi dhe paqja e Allahut qoftë mbi të ). Ky libër shtjellon këto tematika: Së pari: Veprime, mirësia e të cilave në dynja dhe Amshim i kthehet vetëm atij që i ka kryer. Së dyti: Veprime, dobia e të cilave në dynja dhe në Amshim i kthehet kryerësit të tyre dhe tjetërkujt.',
'http://www.islamhouse.com/p/343916',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Furnizimi_me_i_mire.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Furnizimi_me_i_mire.doc',
'Hakem b. Adil Zemu El Ukajli',
'Ali Kasa',
'Driton Lekaj',
'Zyra e Bashkëpunimit për Dave dhe Vetëdijësim të Komuniteteve - Rebve - www.islamhouse.com'),

'12'=>array(
'12',
'Shqip',
'طريق المسلم',
'طريق المسلم: كتاب يحتوي على التعاليم الأساسية للإسلام، وقد جاء في أربعة أقسام: الفصل الأول: يحتوي على ذكر أركان الإسلام، والإيمان، وذكر الإحسان. والفصل الثاني: إيراد للفاتحة وأواخر المفصل. والفصل الثالث: يشتمل على أحكام الطهارة والصلاة مع عرض مُصوَّر لصفة الوضوء والصلاة. والفصل الرابع: فيه شرح لبعض الأحاديث وذكر لبعض الأدعية المأثورة.',
'Rruga e muslimanit',
'Rruga e muslimanit është një doracak që përmbledh njohuritë elementare rreth Islamit. Pjesa e parë e tij flet rreth disa parimeve të përgjithshme të fesë Islame si: Shtyllat e Islamit, Imanit dhe Ihsanit, pastaj disa sqarime rreth Shehadetit. Pjesa e dytë: përmban disa nga suret e shkurtra të Kuranit me përkthim në gjuhën shqipe. Pjesa e tretë: flet rreth rregullave elementare të Fikhut gjegjësisht pastërtisë dhe namazit duke ilustruar me foto mënyrën e marrjes së abdesit dhe faljes së namazit. Pjesa e katërt: veçohet me komentimin e disa haditheve dhe përfundon me një mori lutjesh të shoqëruara me përkthimin në shqip.',
'http://www.islamhouse.com/p/339686',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Rruga_e_muslimanit.pdf',
'',
'Driton Lekaj',
'',
'Organizata bamirëse \'El Haremejn\''),

'13'=>array(
'13',
'Shqip',
'الإسلام وأثره في الحضارة وفضله على الإنسانية',
'الإسلام وأثره في الحضارة وفضله على الإنسانية: إن موضوع الإسلام وأثره في الحضارة موضوع واقعي حيوي ليس وثيق الصلة بالبعثة المحمدية ورسالة الإسلام وتعاليمه فحسب؛ بل بواقع الحياة وحاضر الإنسان ومستقبله ودور الأمة في بناء حضارتها وتوجيهها كذلك، وهذا الكتاب عبارة عن بحث تاريخي وتحليلي لأثر الإسلام والبعثة المحمدية في الحضارة الإنسانية.',
'Islami - ndikimi i tij në civilizim dhe merita e tij për njerëzimin',
'Ky libër në bazë është punim i ofruar Këshillit Nacional për Kulturë i Kuvajtit. Libri shtjellon ndikimin e Islamit në civilizimin njerëzor në vazhdimësi që nga periudha profetike. Por, nëse duhet përmbledhur sferat në të cilat ka ndodhur ky ndikim më tepër, atëherë duhet zgjedhur dhjetë dhurata të cilat ia ka ofruar Islami njerëzimit duke filluar nga besimi i çiltër, të drejtat e gruas, afirmimi i lidhjes mes fesë dhe shkencës etj.',
'http://www.islamhouse.com/p/339682',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Islami_dhe_ndikimi_i_tij_ne_civilizim.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Islami_dhe_ndikimi_i_tij_ne_civilizim.doc',
'Ebul Hasen En Nedevi',
'Bashkim Aliu',
'',
'Komiteti i Lartë Saudit në ndihmë Bosnjës dhe Hercegovinës.'),

'14'=>array(
'14',
'Shqip',
'ترجمة معاني القرآن الكريم إلى اللغة الألبانية',
'ترجمة معاني القرآن الكريم إلى اللغة الألبانية: ترجمة لمعاني القرآن الكريم إلى اللغة الألبانية، وقد قام بها مجموعة من المترجمين لدى دار السلام للنشر والتوزيع. وهي الترجمة الوحيدة التي تمت بعمل فريق من المترجمين، وتتميز بالعناية بآيات العقيدة لتترجم على ضوء العقيدة الصحيحة، عقيدة أهل السنة والجماعة.',
'Kur\'an – i',
'Kur’an-i: Është përkthim i domethënieve të Kuranit Fisnik në shqip nga një grup përkthyesish pranë shtëpisë botuese Darus Selam. Është i vetmi përkthim deri më tani që është kryer në grup dhe shquhet për nga kujdesi që ajetet që kanë të bëjnë me akiden - besimin të përkthehen në dritën e besimit të pastër Islam – Besimit të Ehli Sunetit.',
'http://www.islamhouse.com/p/332473',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Kurani_perkthimi_i_Darus_Selam.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Kurani_perkthimi_i_Darus_Selam.doc',
'',
'Një Grup përkthyesish',
'Një grup recenzuesish',
''),

'15'=>array(
'15',
'Shqip',
'القرآن الكريم وترجمة معانيه إلى اللغة الألبانية',
'القرآن الكريم وترجمة معانيه إلى اللغة الألبانية: هذه الطبعة من القرآن الكريم قد ترجم معانيها إلى اللغة الألبانية الأستاذ حسان أ. ناهي - رحمه الله -، وقد كان من أبرز المشايخ في زمانه، ومن النوادر الذين واصلوا دراساتهم خارج البلاد، وتعتبر ترجمته من أدق الترجمات للقرآن الكريم باللغة الألبانية.',
'Kurani i madhërishëm',
'Ky botim i Kuranit të madhërishëm në shqip përmban përkthimin e domethënieve të Kuranit nga Prof. Hasan I. Nahi (Allahu e mëshiroftë). Prof. Hasan Nahi ishte një ndër hoxhallarët më të shquar të kohës së tij dhe ndër të vetmit që shkollimin superior e kishin kryer jashtë vendit. Sipas disa kritikëve përkthimi i tij konsiderohet si një ndër përkthimet më autentike të Kuranit në shqip.',
'http://www.islamhouse.com/p/332470',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Kurani_i_madherishem.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Kurani_i_madherishem.doc',
'',
'Hasan I. Nahi',
'',
'Instituti Shqiptar i Qytetërimit dhe Mendimit Islam - http://www.aiitc.org'),

'16'=>array(
'16',
'Shqip',
'التوحيد والشرك',
'التوحيد والشرك: كتاب بيَّن فيه الشيخ محمد جميل زينو - رحمه الله - أهميةَ وفضل التوحيد وخطر الشرك، وذلك بذكر الشرك الأكبر والأصغر وصور كلٍّ منهما.',
'Teuhidi dhe Shirku',
'Teuhidi dhe Shirku: Në këtë libër hoxha i nderuar, Muhamed Xhemil Zejno (Allahu e mëshiroftë), sqaron rëndësinë dhe vlerën e teuhidit – njësimit të Allahut dhe dëmin e shirkut – adhurimit të dikujt tjetër pos Allahut. Ai gjithashtu sqaron shirkun e madh dhe llojet e tij si dhe shirkun e vogël me llojet e tij, ku dhe tërheq vërejtjen nga disa forma të tyre të cilat i veprojnë njerëzit.',
'http://www.islamhouse.com/p/332075',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Teuhidi_dhe_Shirku.pdf',
'Muhamed Xhemil Zejno',
'',
'Ekrem Avdiu',
'Zyra e Bashkëpunimit për Dave dhe Vetëdijësim të Komuniteteve - Rebve - www.islamhouse.com'),

'17'=>array(
'17',
'Shqip',
'الجمعة - أفضل أيام الأسبوع',
'الجمعة أفضل أيام الأسبوع: كتاب يتحدَّث عن فضل يوم الجمعة وما اختصَّه الله تعالى من بين سائر الأيام، مع ذكر الأحكام التي تتعلَّق بيوم الجمعة عامةً، والأحكام المتعلقة بالصلاة خاصةً.',
'Xhumaja - Dita më e zgjedhur e javës',
'Ky libërth flet për vlerën e ditës së Xhuma dhe veçoritë me të cilat Allahu i lartësuar e ka dalluar nga ditët e tjera. Gjithashtu flet edhe për shumë dispozita që kanë të bëjnë me ditën e Xhuma në përgjithësi dhe me namazin e xhumasë në veçanti.',
'http://www.islamhouse.com/p/329572',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Xhumaja_dita_me_e_zgjedhur_e_javes.pdf',
'Salih El Kurdi',
'Selim Sulejmani',
'',
''),

'18'=>array(
'18',
'Shqip',
'تعليم الإسلام',
'تعليم الإسلام: كتاب يعرض بأسلوب سهل أهم المعلومات عن الإسلام؛ يتحدَّث الكتاب أولاً عن أركان الإيمان بالتفصيل، ثم يتحدث عن ركني الشهادة والصلاة من أركان الإسلام، ثم يعرض إجمالاً بعض الآداب الإسلامية، ويختم الكتاب بعرض أهم الوقائع المتعلقة بالسيرة النبوية.',
'Ta mësojmë Islamin',
'Ta mësojmë Islamin: është libër i cili prezanton, me një metodologji të thjeshtë, njohuritë themelore rreth Islamit. Së pari, libri flet rreth shtyllave të besimit dhe atë hollësisht, e pastaj flet për dy shtyllat e para të Islamit, shehadetin dhe namazin, gjithashtu hollësisht. Pas kësaj në mënyrë të përgjithësuar shtjellon disa virtyte islame dhe libri përmbyllet me ngjarjet më të rëndësishme gjatë jetës së Pejgamberit (lavdërimi dhe shpëtimi i Allahut qofshin mbi të).',
'http://www.islamhouse.com/p/329569',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Ta_mesojme_Islamin.pdf',
'Muhamed ALij Fet-hullah',
'Irfan Salihu',
'',
'Komiteti i Lartë Saudit në ndihmë Bosnjës dhe Hercegovinës.'),

'19'=>array(
'19',
'Shqip',
'مجموعة قصص - للأطفال',
'مجموعة قصص للأطفال: كتاب يحتوي على مجموعة من القصص الإسلامية للأطفال، مكتوبة بأسلوب روائي يُناسِب الأطفال. وهي قصص هادفة مُقتبسة من القرآن والسنة وتاريخ الأمة الإسلامية.',
'Përmbledhje tregimesh',
'Përmbledhje tregimesh: Është libër i cili ka përmbledhur një sërë tregimesh islame për fëmijë, të cilat janë të shkruara me një metodologji të përshtatshme për fëmijët. Tregimet janë edukative dhe janë marrë nga Libri i Allahut - Kurani, Tradita profetike – Suneti dhe historia islame.',
'http://www.islamhouse.com/p/329565',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Permbledhje_tregimesh.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Permbledhje_tregimesh.doc',
'Muhamed Muveffek Selime - Muhamed Munir El Xhenbaz - Muhjid-din Selime',
'Irfan Salihu',
'',
'Komiteti i Lartë Saudit në ndihmë Bosnjës dhe Hercegovinës.'),

'20'=>array(
'20',
'Shqip',
'المحادثة اليومية باللغة العربية والإنجليزية والألبانية',
'هذا الكتاب يحتوي على الكلمات المستخدمة في المحادثات اليومية في اللغة الألبانية، وترجمتها بالعربية، والإنجليزية. وهو مُوجَّه للمهتمين بهذه اللغات من المبتدئين أو الذين يريدون أن يُعمِّقوا معارفهم، ويُتيحُ لهم فرصةَ المقارنة فيما بينها، فهو بمثابة القاموس الثلاثي. وقد راجعه مجموعة من الأساتذة الجامعيين.',
'Bisedë e përditshme - Shqipe, Angleze dhe Arabe',
'Ky libër përmban fjalë dhe biseda në gjuhët: shqip, anglisht dhe arabisht. Libri është i përpiluar për nivelin e fillestarëve dhe ju ndihmon t’i thellojnë njohuritë e tyre në këto gjuhë si dhe të bëjnë krahasim mes tyre.',
'http://www.islamhouse.com/p/329560',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Bisede_e_perditshme_Shqipe_Angleze_dhe_Arabe.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Bisede_e_perditshme_Shqipe_Angleze_dhe_Arabe.doc',
'Fehim Dragusha',
'',
'Një grup recenzuesish',
''),

'21'=>array(
'21',
'Shqip',
'الوجيز في منهج السلف الصالح',
'الوجيز في منهج السلف الصالح: كتيب للشيخ عبد القادر الأرناؤوط - رحمه الله - عرض فيه عقيدة ومنهج السلف - رضوان الله عليهم - مُستدلاًّ لذلك بالأدلة من الكتاب والسنة ونفائس كلام علماء السلف.',
'Mbi rrugën e të parëve tanë (Selefit)',
'Libërth i shkruar nga dijetari shqiptar Abdul Kadër Arnauti (Allahu e mëshiroftë) ku sqaron me fjalë të shkurtra por, të qarta akiden - besimin e gjeneratave të arta islame (Selefit) dhe metodologjinë e tyre në kuptimin e fesë. Libri përveç argumenteve nga Kurani dhe Syneti përmban edhe një mori nga fjalët më të arta të dijetarëve të Selefit.',
'http://www.islamhouse.com/p/328711',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Mbi_rrugen_e_te_pareve_tane.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Mbi_rrugen_e_te_pareve_tane.doc',
'AbdulKadir El Arnaut',
'Bekr Halimi',
'Sedat Shabani',
''),

'22'=>array(
'22',
'Shqip',
'مشاريع العشر',
'مشاريع العشر: كتيب للشيخ المربي محمد حسين يعقوب - حفظه الله - يبين فضل العشر من ذي الحجة ويقدم من خلاله خطة لأمثل استغلال لها، من خلال المشاريع التالية: مشروع القرآن الكريم، وليمة لكل صلاة، الذكر، الصيام، الحج والعمرة، قناطير الفردوس، الأخوة في الله، صلة الأرحام، يوم عرفة، مشروع يوم العيد، ويختمها بفرص ذهبية.',
'Plani dhjetëditor',
'Plani dhjetëditor është një libërth i edukatorit dhe dijetarit Muhamed Husejn Jakub, ku flet për vlerën e dhjetë ditëve të Dhul Hixhes dhe prezanton një program për shfrytëzimin sa më të mirë të tyre. Ky plan përmban dhjetë projekte, e ato janë: Projekti i Kuranit Fisnik, banketi për çdo namaz, dhikrit, agjërimit, haxhit dhe umres, projekti “Kanatirul Firdevs”, i vëllazërisë për hir të Allahut, i lidhjes familjare, ditës së Arafatit, ditës së Bajramit dhe e përfundon librin e tij me shanse të arta që duhet çdo musliman të përfitoj prej tyre.',
'http://www.islamhouse.com/p/327427',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Plani_dhjete_ditor.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Plani_dhjete_ditor.doc',
'Muhamed Husejn Jakub',
'Ulvi Fejzullahu',
'Redaksia e uebfaqes Albislam',
'Uebfaqja \'Albislam\' - http://www.albislam.com'),

'23'=>array(
'23',
'Shqip',
'أخطاء يرتكبها بعض الحجاج',
'أخطاء يرتكبها بعض الحجاج: هذه الرسالة تبين السنة في بعض الأعمال التي يكثر فيها الأخطاء في الحج والعمرة.',
'Gabime në të cilat bien disa haxhilerë',
'Ky libërth sqaron disa nga ritualet e haxhit, duke bërë të qartë mënyrën e saktë të kryerjes së tyre në pajtim me traditën e Pejgamberit (lavdërimi dhe shpëtimi i Allahut qofshin mbi të) dhe duke tërhequr vërejtjen nga gabimet në të cilat bien disa haxhilerë. Këto rituale dhe gabimet në to janë: Ihrami, tavafi, dy rekatet pas tavafit, ngjitja mbi Safa dhe Merve, qëndrimi në Arafat, hedhja e gurëve, tavafi lamtumirës.',
'http://www.islamhouse.com/p/327422',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Gabime_ne_te_cilat_bien_disa_haxhilere.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Gabime_ne_te_cilat_bien_disa_haxhilere.doc',
'Muhamed b. Salih El Uthejmin',
'Driton Lekaj',
'',
'Zyra e Bashkëpunimit për Dave dhe Vetëdijësim të Komuniteteve - Rebve - www.islamhouse.com'),

'24'=>array(
'24',
'Shqip',
'صيام التطوع',
'صيام التطوع: كتيب يحتوي على أهمية صيام التطوع، وأحكام عامة حوله، ثم ذكر ما هو مستحب من صيام التطوع: يوما الاثنين والخميس، صيام ثلاثة أيام من كل شهر، يوم عاشوراء، يوم عرفة، ثم ذكر الأيام المنهي عن الصيام فيها: إفراد يوم الجمعة أو السبت بالصوم، صوم المرأة بدون إذن زوجها، العيدين، أيام التشريق، وأن يتقدم رمضان بصوم يوم أو يومين، وأخيرًا ما يتعلق بصيام كل شهر بعينه حسب ترتيبها.',
'Agjërimi vullnetar',
'Agjërimi fakultativ (vullnetar): është një libërth që përmban rëndësinë e agjërimit vullnetar, disa rregulla të përgjithshme rreth agjërimit vullnetar, pastaj agjërimet ditore të lejuara si: dita e hënë dhe enjte, agjërimi i tre ditëve të çdo muaji, dita e Ashurasë dhe dita e Arafatit, pastaj ato të ndaluara: agjërimi i ditës së Xhuma të vetme, agjërimi i gruas pa lejen e burrit, agjërimi i bajrameve, agjërimi i ditëve të teshrikut dhe një apo dy dite para muajit të Ramazanit dhe për fund agjërimi i muajve në bazë të radhitjes së tyre vjetore.',
'http://www.islamhouse.com/p/321755',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Agjerimi_vullnetar.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Agjerimi_vullnetar.doc',
'Sedat Islami',
'',
'Driton Lekaj',
''),

'25'=>array(
'25',
'Shqip',
'سيرة النبي صلى الله عليه وسلم',
'هذا الكتاب يحمل في طياته سيرة النبي - صلى الله عليه وسلم - من البداية إلى النهاية. وقد كتب باسلوب سهل جذاب مما يجعله مناسبًا للأطفال والشباب.',
'Jeta e profetit Muhamed (sal-lAllahu alejhi ue sel-lem)',
'Ky libër përmban në vete jetëpërshkrimin e të Dërguarit (sal-lAllahu alejhi ue sel-lem) që nga fillimi e deri në fund. I shkruar me një metodologji të lehtë dhe tërheqëse është i përshtatshëm për fëmijët dhe moshat e reja.',
'http://www.islamhouse.com/p/314578',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Jeta_e_Profetit_Muhamed.pdf',
'',
'',
'',
''),

'26'=>array(
'26',
'Shqip',
'الإسلام والنصرانية',
'الإسلام والنصرانية: هذا الكتاب محاولة لتقديم الصورة الصحيحة لكثير من المسائل التي تمثل الفرق بين الإسلام والنصرانية. وبما أن ساحة الكتاب الألباني شهدت كتابات كثيرة في هذا المجال، يحاول الكتاب أن يقدم دراسة جادة وأجوبة شافية حول كثير من الأسئلة، منها: 1- هل المسيح هو الله؟ 2- وهل فدى بنفسه عن ذنوب البشرية؟ 3- وأي كلام الله بم يتبدل: الكتاب المقدس أم القرآن؟',
'Islami dhe Krishterizmi',
'“Viteve të fundit publiku shqiptar është ballafaquar me literaturë të shumtë rreth Islamit dhe Krishterimit. Libri të cilin e keni në duar synon që të japë një pikëpamje alternative në shumicën e çështjeve të cilat i ndajnë këto dy besime. Duke konsultuar burime autoktone të dy besimeve sikur edhe duke hyrë në thellësinë e dorëshkrimeve të vjetra të shkrimeve kristiane, e edhe atyre kur‟anore gjithashtu, kemi dhënë ide të përgjithshme për çështje si: a është Jezusi (Isai a.s) Zot, a u kryqëzua ai për të na larë nga mëkatet, cila është Fjala e pandryshuar e Perëndisë – Bibla apo Kurani, etj.”',
'http://www.islamhouse.com/p/314473',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Islami_dhe_Krishterizmi.pdf',
'',
'',
'',
''),

'27'=>array(
'27',
'Shqip',
'تعريف موجز بالإسلام',
'تعريف موجز بالإسلام: كتيب يتضمن تعريفا ً موجزا ً بمراتب الدين الثلاثة: الإسلام، والإيمان والإحسان.',
'Njohje e përgjithshme me Islamin',
'Libërth i cili përmban një pasqyrë të shkurtë rreth gradave të fesë Islame: Islamit (nënshtrimit përmes veprave të dukshme) dhe kushteve të tij, Imanit (besimit) dhe kushteve të tij si dhe Ihsanit (bamirësë).',
'http://www.islamhouse.com/p/314465',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Njohje_e_pergjithshme_me_Islamin.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Njohje_e_pergjithshme_me_Islamin.doc',
'Dekanati për Hulumtime Shkencore pranë Universitetit Islamik të Medinës',
'Ahmed Kalaja',
'',
'Uebfaqja e Universitetit Islamik në Medinën e Ndritshme'),

'28'=>array(
'28',
'Shqip',
'حقوق دعت إليها الفطرة وقررتها الشريعة',
'حقوق دعت إليها الفطرة وقررتها الشريعة : قال المصنف - رحمه الله -: " فإن من محاسن شريعة اللّه تعالى مراعاة العدل وإعطاء كل ذي حق حقه من غير غلو ولا تقصير .. فقد أمر اللّه بالعدل والإحسان وإيتاء ذي القربى. وبالعدل بعثت الرسل وأنزلت الكتب وقامت أمور الدنيا والآخرة. والعدل إعطاء كل ذي حق حقه وتنزيل كل ذي منزلة منزلته ولا يتم ذلك إلا بمعرفة الحقوق حتى تعطى أهلها، ومن ثم حررنا هذه الكلمة في بيان المهم من تلك الحقوق؛ ليقوم العبد بما علم منها بقدر المستطاع، ويتخلص ذلك فيما يأتي: 1 - حقوق اللّه تعالى. 2 - حقوق النبي - صلى الله عليه وسلم -. 3 - حقوق الوالدين. 4 - حقوق الأولاد. 5 - حقوق الأقارب. 6 - حقوق الزوجين. 7 - حقوق الولاة والرعية. 8 - حقوق الجيران. 9 - حقوق المسلمين عموما. 10 - حقوق غير المسلمين. هذه هي الحقوق التي نريد أن نتناولها بالبحث على وجه الاختصار.',
'Të vërteta në të cilat ftoi natyra e i pranoi Sheriati',
'Shejhu (Allahu e mëshiroftë) e përshkruan librin e tij me fjalët: “Prej mirësive të sheriatit të Allahut xh.sh. është përkujdesja ndaj drejtësisë duke ia kushtuar një rëndësi të veçantë ... Drejtësia është dhënia çdo kujt hakun që i takon, duke mos e tepruar në të e as pakësuar. Ne me ndihmën e Zotit xh.sh. do të mundohemi që të sqarojmë diç për të drejtat gjegjësisht obligimet më kryesore të cilat i ka njeriu ndaj të tjerëve” E këto të drejta janë si vijon: 1. Obligimet ndaj Allahut të madhëruar. 2. Obligimet ndaj të Dërguarit të Zotit (sal-lAllahu alejhi ue sel-lem) 3. Obligimet ndaj prindërve. 4. Obligimet ndaj fëmijëve. 5. Obligimet ndaj të afërmve. 6. Obligimi i bashkëshortëve ndaj njëri- tjetrit. 7. Obligimi ndaj fqinjit. 8. Obligimi ndaj muslimanëve – në përgjithësi.',
'http://www.islamhouse.com/p/314463',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Te_verteta_ne_te_cilat_ftoi_natyra_e_i_pranoi_Sheriati.pdf',
'Muhamed b. Salih El Uthejmin',
'Dr. Shefqet Krasniqi',
'',
''),

'29'=>array(
'29',
'Shqip',
'أجوبة الأسئلة التشكيكية الموجهة من قبل إحدى المؤسسات التبشيرية العاملة تحت تنظيم الآباء البيض',
'هذا الكتاب يتضمن أجوبة على أسئلة وجهت إلى الأمانة العامة للمجلس القاري لمساجد أوروبا من إحدى المؤسسات التبشيرية العاملة تحت تنظيم "الآباء البيض"، ثم وجهها الأمانة العامة إلى المؤلف ليعتني بجوابها ويفند شبهها. وقد قدم المؤلف لكتابه بتمهيد فيه مقدمة عامة حول مفاهيم إسلامية لا بد من بيانها ثم شرح مفهوم الحرية والمساواة في الإسلام إذ الأسئلة تتعلق بها. وبعد ذلك، شرع في الجواب على الأسئلة واحدة تلو الأخرى وبين وجه الحق فيها. إن هذا الكتاب وإن كان صغيرًا في حجمه إلا أنه يتصدى بجدارة لكل محاولات التشكيك، ويقف في وجه الشبهات ويفندها حتى من مصادرهم.',
'Priftërinjtë pyesin dhe Hoxhallarët përgjigjen',
'“Përse ky libër? Nuk do të jenë të paktë ata që ndoshta do ta bëjnë një pyetje të tillë pasi të njihen me tematikën që ai trajton. Në një kohë kur Islami dhe ithtarët e tij janë vënë në bankën e të akuzuarve për një mori akuzash, ku më të spikaturat dallojnë ato të terrorizmit, obskurantizmit, mungesës së tolerancës, prapambetjes, egërsisë, brutalitetit…etj, del në skenë një libër i tillë për ta mbrojtur atë! Pikërisht ky libër u shkrua për t’u dhënë sadopak përgjigje këtij llumi të shpifur akuzash. Ky libër i shkurtër dhe përmbledhës jep një ide të përgjithshme të botëkuptimeve islame dhe më pas iu përgjigjet një seri pyetjesh në mënyrë të shkurtër dhe të përmbledhur.” Ky libër u shkrua si përgjigje ndaj një mori pyetjesh që iu drejtuan Sekretariatit të Këshillit kontinental për Xhamitë në Evropë nga një organizatë evangjeliste, e të cilat kanë të bëjnë me liritë individuale dhe me barazinë mes njerëzve.',
'http://www.islamhouse.com/p/314460',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Prifterinjte_pyesin_dhe_hoxhallaret_pergjigjen.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Prifterinjte_pyesin_dhe_hoxhallaret_pergjigjen.doc',
'Abdurr-Rrahman Hasen Habenneke El Mejdani',
'Justinian Topulli',
'',
''),

'30'=>array(
'30',
'Shqip',
'رسالة واحدة فقط!',
'رسالة واحدة فقط! : يتكلم هذا الكتاب عن رسالة التوحيد الواحدة التي حملها جميع الأنبياء والرسل من لدن آدم - عليه السلام - إلى نبينا محمد - صلى الله عليه وسلم -. ويمتاز .. بإثبات توحيد ( وحدانية ) الله من كتب اليهود والنصارى ( العهد القديم والعهد الجديد ) التي بين أيديهم في وقتنا المعاصر.',
'Një mesazh i vetëm!',
'Ky libër flet për mesazhin e vetëm me të cilin janë ngarkuar tërë pejgamberët dhe të dërguarit që nga koha e Ademit e deri te pejgamberi ynë, Muhamedi (sal-lAllahu alejhi ue sel-lem). Si dhe dallohet për shkak të vërtetimit të njëshmërisë së Allahut – monoteizmit përmes librave të krishterëve dhe jehudëve (Dhjata e vjetër dhe e re), të cilat i posedojnë tash para vetes.',
'http://www.islamhouse.com/p/314454',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Nje_mesazh_i_vetem.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Nje_mesazh_i_vetem.doc',
'Naxhi b. Ibrahim El Arfexh',
'Bledar Haxhiu',
'',
''),

'31'=>array(
'31',
'Shqip',
'كتاب التوحيد',
'كتاب التوحيد: مما لا شك فيه أن علم العقيدة الإسلامية هو العلم الأساسي الذي تجدر العناية به تعلما وتعليما وعملا - بموجبه لتكون الأعمال صحيحة مقبولة عند الله نافعة للعاملين، خصوصا وأننا في زمان كثرت فيه التيارات المنحرفة: تيار الإلحاد، وتيار التصوف والرهبنة، وتيار القبورية الوثنية، وتيار البدع المخالفة للهدي النبوي. وكلها تيارات خطيرة ما لم يكن المسلم مسلحا بسلاح العقيدة الصحيحة المرتكزة على الكتاب والسنة وما عليه سلف الأمة؛ فإنه حري أن تجرفه تلك التيارات المضلة، وهذا مما يستدعي العناية التامة بتعليم العقيدة الصحيحة لأبناء المسلم أن من مصادرها الأصيلة؛ لذا فهذا كتاب في علم التوحيد، راعى فيه المصنف - حفظه الله - الاختصار مع سهولة العبارة، وقد اقتبسه من مصادر كثيرة من كتب أئمتنا الأعلام - ولا سيما كتب شيخ الإسلام ابن تيمية، وكتب العلامة ابن القيم، وكتب شيخ الإسلام محمد بن عبد الوهاب وتلاميذه من أئمة الدعوة المباركة - رحمهم الله -.',
'Libri i Teuhidit',
'Është e ditur se shkenca për akiden islame është shkenca bazë e cila meriton të përkujdesemi për ta mësuar dhe për t’ua mësuar të tjerëve dhe prej saj varet pranimi i veprave dhe saktësia e tyre. Sidomos kur ne jetojmë kur janë shtuar grupet e devijuara si: Rryma e ateizmit, rryma e sufizmit dhe dervishizmit, rryma e idhujtarisë bashkëkohore – adhurimit të varrezave, rryma e risive të cilat janë në kundërshtim me traditën profetike dhe që tërë këto rryma janë të rrezikshme po që se muslimani nuk është i armatosur me dijen e akides së vërtetë e cila mbështetet në Librin e Allahut dhe Synetin e të Dërguarit (sal-lAllahu alejhi ue sel-lem). ky libër është shkruar në lëmin e akides dhe autori është kujdesur të jetë i shkurtër dhe i qartë. Shejhu e ka mbështetur librin e tij në burime të shumta të dijetarëve e sidomos në librat e Shejhul Islam Ibn tejmijes, Ibn Kajjimit, Muhamed b. Abdul Vehabit dhe dijetarë që i përkasin kësaj thirrjeje të begatshme.',
'http://www.islamhouse.com/p/314452',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Libri_i_Tevhidit.pdf',
'',
'',
'',
'Ministria e Punëve Islame, Vakëfit, Daves dhe Udhëzimit'),

'32'=>array(
'32',
'Shqip',
'حقوق المرأة المسلمة وواجباتها في الإسلام',
'هذا الكتاب باللغة الألبانية يوضح للمرأة المسلمة دورها الأساسي في الأسرة والمجتمع والحقوق التي منحها الإسلام لها، ويرد على الشبهات التي تستهدف المرأة المسلمة بالأدلة القاطعة من القرآن والسنة.',
'Karta e të drejtave të gruas dhe detyrat e saj në Islam',
'Ky dokument është përgatitur për të sqaruar qëndrimin e sheriatit (legjislacionit) islam rreth çështjes më të përfolur në mesin e muslimanëve; çështjes së gruas, prej së cilës është sprovuar qytetërimi perëndimor, vesa e së cilës ka prekur disa shoqëri islame dhe logjikën e disa prej bijve të saj. Ky dokument përmban sqarimin e çështjes më të rëndësishme rreth gruas, si dhe çështje të tjera që kanë të bëjnë me të në aspektin e themelimit dhe mbrojtjes, gjë të cilën e kërkon natyra e kësaj etape. Ky sqarim është përpjekja e dhjetëra dijetarëve dhe mendimtarëve, në mënyrë që të arrinte në formën e dokumentit dhe përmbledhjes. ... “Jemi përpjekur në këtë dokument përmbledhës që të komentojmë e argumentojmë në mënyrë të shkurtër rreth këtyre pikave: - Pikënisjet bazë. - Bazat e sheriatit rreth të drejtave të gruas dhe detyrave të saj. - Largpamësi komentuese dhe arsyetuese të disa prej këtyre bazave. - Këshilla dhe kërkesa.”',
'http://www.islamhouse.com/p/314450',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Karta_e_te_drejtave_te_gruas.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Karta_e_te_drejtave_te_gruas.doc',
'Ibrahim Nasir En Nasir',
'Bledar Haxhiu',
'',
''),

'33'=>array(
'33',
'Shqip',
'الدين الصحيح',
'ما ضوابط الدين الصحيح؟ كيف تجب أن تكون العلاقة بين الخالق والمخلوق؟ كيف تعرف ربك حتى تعبده و تتبع صراطه المستقيم؟ المؤلف يجيب على أكثر من هذه الأسئلة بأمثلة واضحة, و يأتي أيضاً بمقتبسات من الكتب المقدسة عند أهل الكتاب ليشرح عقائدهم.',
'Feja e vërtetë e Zotit',
'Cilat janë rregullat e fesë vërtetë? Si duhet të jetë lidhja mes Krijuesit dhe krijesës? Si ta njohësh Zotin tënd, që ta adhurosh dhe ta pasosh rrugën e Tij të drejtë? Autori iu përgjigjet këtyre dhe shumë pyetjeve tjera me shembuj të qartë dhe gjithashtu sjell citate nga librat e shenjtë të ithtarëve të librit. Libri në shqip përfundon me një rezyme rreth biografisë së autorit i cili edhe është një nga thirrësit e mirënjohur.',
'http://www.islamhouse.com/p/314448',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Feja_e_vertete_e_Zotit.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Feja_e_vertete_e_Zotit.doc',
'Bilal Filips',
'',
'Bahri Curri',
''),

'34'=>array(
'34',
'Shqip',
'حي على الفلاح!',
'حي على الفلاح: انطلاقًا من أهمية تعاليم الإسلام والتي بعد الإيمان تتقدمها الصلاة؛ نجد من الواجب علينا الاشتغال ببيان فضلها وكيفية أدائها بأيسر طريقة. ومن هنا جاءت فكرة هذا الدليل المصور لتعليم أحكام الصلاة وبيان الأخطاء التي تقع فيه. ومرفق معه مختصر لهذا الكتاب الماتع.',
'Ejani në shpëtim!',
'“Duke pasur parasysh rëndësinë e praktikimit të mësimeve islame, të cilave pas besimit, me vlerë dhe rëndësi iu paraprinë namazi, na imponohet që të jemi të mobilizuar në sqarimin e këtyre mësimeve si nga këndi i ndriçimit të vlerës së secilit prej tyre, ashtu edhe në shpjegimin praktik se si duhet të kryhet cilido. Prandaj ju ofrojmë këtë udhëzues të ilustruar për mësimin e namazit dhe gabimet që bëhen në të.”',
'http://www.islamhouse.com/p/314443',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Ejani_ne_Shpetim.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Ejani_ne_shpetim_version_i_shkurtuar.pdf',
'Eroll Nesimi',
'',
'Ekrem Avdiu',
''),

'35'=>array(
'35',
'Shqip',
'شرح مبادئ التوحيد',
'شرح مبادئ التوحيد : كتاب فيه بيان لأقسام التوحيد وأهمية توحيد العبادة من بينها، وأنه من أجله أرسل الرسل وأنزلت الكتب. ثم يبدأ المؤلف - وفقه الله - بذكر الأعمال والأقوال التي تناقض توحيد العبادة جزئيًا أو كليًا، مع ذكر الانحرافات الواقعة في المجتمعات الإسلامية، والتي تتصل بتوحيد العبادة، إلى اليوم. ويستدل على كل ذلك بأدلة من الكتاب والسنة وأقوال الأئمة.',
'Bazat e Teuhidit - Monoteizmi Islam',
'Tevhidi, njësimi i Zotit, është thelbi i besimit islam. Njerëzit janë të urdhëruar ta zbatojnë këtë koncept në tokë, në çdo hap të jetës, që nga ditët e Ademit. Në këtë libër fillimisht sqarohen kategoritë e tevhidit e më pas libri në mënyrë të qartë flet për kategorinë: Tevhidul – Ibade (Njësimin e Allahut në adhurim) dhe sqaron rëndësinë e tij pasi që të gjithë Pejgamberët (lavdërimi dhe shpëtimi i Allahut qofshin mbi ta) kanë thirrur në të. Libri flet për bindjet dhe veprat e njerëzve të cilat bien në kundërshtim me të, e të cilat fatkeqësisht janë shumë të përhapura në mesin e muslimanëve edhe në ditët e sotme.',
'http://www.islamhouse.com/p/314440',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Bazat_e_Teuhidit.pdf',
'Bilal Filips',
'',
'',
''),

'36'=>array(
'36',
'Shqip',
'الإيمان أركانه، حقيقته، نواقضه',
'الإيمان: أركانه، حقيقته، ونواقضه: كتاب معاصر في بيان عقيدة أهل السنة والجماعة بالأدلة والبراهين، وقد عرض الموضوعات بشكل تسلسلي جميل. ويتكون من ثلاثة أبواب: الباب الأول: في أركان الإيمان الستة. الباب الثاني: في حقيقة الإيمان ومعناه. الباب الثالث: في الأقوال والأعمال التي تخرج صاحبها من الإيمان.',
'Besimi - Bazat, Esenca, Negacioni',
'Akideja – Besimi, është pjesa më e rëndësishme që duhet ta dijë myslimani rreth fesë së tij. Ky libër që po u ofrojmë është shkruar në lëmin e akides dhe është ndër librat bashkëkohorë më të njohur. Libri është i bazuar në kuptimin e akides sipas gjeneratave të para islame, i mbështetur në argumente dhe larg devijimeve të grupeve të ndryshme. Libri ka tre kapituj: I pari: Flet për gjashtë kushtet e besimit. I dyti: Flet për thelbin dhe esencën e besimit. I treti: Flet për fjalët dhe veprat që të nxjerrin prej besimit.',
'http://www.islamhouse.com/p/306589',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Besimi_bazat_esenca_dhe_negacionet.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Besimi_bazat_esenca_dhe_negacionet.doc',
'Muhamed Nuajm Jasin',
'',
'',
''),

'37'=>array(
'37',
'Shqip',
'أريد أن أتوب .. ولكن!',
'أريد أن أتوب ولكن!: تحتوي هذه الرسالة على مقدمة عن خطورة الاستهانة بالذنوب فشرحاً لشروط التوبة، ثم علاجات نفسية، وفتاوى للتائبين مدعمة بالأدلة من القرآن الكريم والسنة، وكلام أهل العلم وخاتمة.',
'Dëshiroj të pendohem, por...!',
'Dëshiroj të pendohem, por... : Ky libërth përmban një parathënie rreth rrezikut të përçmimit të mëkateve, pastaj një koment të shkurtër rreth kushteve të pendimit – Teubes dhe disa udhëzime për shërim të shpirtrave. Libërthi përfundon me disa fetva për të penduarit, të mbështetura në argumentet e Kuranit dhe Sunetit dhe fjalët e Dijetarëve.',
'http://www.islamhouse.com/p/306587',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Deshiroj_te_pendohem,http://www.islamhouse.com/d/por.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Deshiroj_te_pendohem,http://www.islamhouse.com/d/por.doc',
'Muhamed Salih El Munexhid',
'Ekrem Avdiu',
'Umer Musa',
''),

'38'=>array(
'38',
'Shqip',
'آداب إسلامية',
'هذا الكتيب يحتوي على بيان بعض الآداب الإسلامية التي ينبغي على المسلم أن يتحلى بها.',
'Etika Islame',
'Ky është një libër përmbledhës që përmban një varg rregullash për të cilat ka nevojë muslimani gjatë jetës së tij të përditshme. Këtë libër ia paraqes si këshillë umetit: Mësim për të paditurin, përkujtim për harrestarin dhe vërej-tje për shpërfillësin e këtyre rregullave. Ky libër është këshillë për besimtarin, që të jetojë me udhëzimet e Pejgamberit (sal-lAllahu alejhi ue sel-lem)',
'http://www.islamhouse.com/p/306584',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Etika_islame.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Etika_islame.doc',
'AbdulHamid b. Abdurr-Rrahman Es Suhejbani',
'Ferid Selimi',
'Umer Musa',
''),

'39'=>array(
'39',
'Shqip',
'المعين على فهم الجزء الثلاثين',
'المعين على فهم الجزء الثلاثين : يتميز هذا الكتاب بأنه: 1ـ تفسير واضح لجزء عم بعيدا عن الغموض والخلافات ويناسب جميع الفئات العمرية، والمستويات العلمية. 2ـ سهولة عبارة المؤلف، وخاصة في المعنى الإجمالي. 3ـ قسم السور الطويلة إلى مقاطع؛ ليسهل دراستها واستيعابها. 4ـ فسر معاني الكلمات الصعبة كما وردت في السورة دون ردها إلى أصلها. 5ـ يذكر بعد كل مقطع الكلمات التي تختلف كتابتها العثمانية عن كتابتها الإملائية؛ لكي لا يلتبس على القارئ رسم الآية. 6ـ يورد بعد كل مقطع أسئلة عبارة عن تدريبات ومناقشات لما تم عرضه في المقطع.',
'Ndihmëtar për kuptimin e xhuzit të tridhjetë',
'Ndihmëtar në kuptimin e xhuzit të tridhjetë: Ky libër veçohet për: 1. Komentin e qartë të pjesës së fundi të Kuranin, larg paqartësive dhe mospajtimeve duke qenë kësisoj i përshtatshëm për të gjitha nivelet. 2. Të shprehurit e qartë të autorit sidomos në sqarimin e kuptimit të përgjithshëm. 3. I ka ndarë kaptinat e gjata në pjesë ashtu që të jetë më i lehtë studimi dhe kuptimi i tyre. 3. I ka sqaruar fjalët e nevojshme për sqarim ashtu siç janë përmendur në sure. 4. Pas çdo pjese sjell pyetje dhe ushtrime rreth asaj që është prezantuar në atë pjesë.',
'http://www.islamhouse.com/p/306582',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Kuptimi_i_xhuzit_30-te.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Kuptimi_i_xhuzit_30-te.doc',
'Zejd Umer Abdullah El Is',
'',
'',
''),

'40'=>array(
'40',
'Shqip',
'الرحيق المختوم [ بحث في السيرة النبوية ]',
'الرحيق المختوم : لقد حظيت سيرة صاحب الرسالة العظمى - صلى الله عليه وسلم - باهتمام العلماء والمحدثين والكتاب والمؤرخين، المتقدمين منهم والمتأخرين، وكل من هؤلاء الأعلام يغوص في ثبج هذا البحر الزاخر، ويستصفي منه يتيم الجوهر ونفيس الدرر. فمنهم من عني باستخلاص دلائل الإعجاز والخصائص النبوية، ومنهم من صمد إلى الإبانة عن أحداث الغزوات وتفاصيل المعارك، ومنهم من أفاض في ذكر فقهها واستخلاص أحكامها وعبرها، ومنهم من استجلى مواقف عظمة هذه النفس الزكية. ولا تزال وستبقى سيرة هذا النبي الكريم - صلى الله عليه وسلم - ملهمة لأولي الأقلام اللامعة والدراسات العميقة، للاستهداء بهديها والتأسي بصاحبها صلى الله عليه وسلم. وممن أسهم في هذا المضمار ونهل من هذا المعين الصافي الشيخ صفي الرحمن المباركفوري - رحمه الله - في كتابنا هذا؛ حيث كتب عن السيرة فصولاً مضيئة، وموازنات فريدة، وربط الأحداث ببعضها ربطاً متماسكاً بأسلوب بديع أخاذ، حيث استخلص من كتب الأقدمين فوائد بلورها في إيجاز غير مخل، وتطويل غير ممل، فجاء كافياً وافياً. وفي زماننا هذا الذي أضحى الناس فيه يلهثون وراء مناهج فاسدة ويسلكون سبلاً معوجة .. تبرز أهمية دراسة السيرة العطرة؛ لتوضح لنا معالم الطريق المستقيم، وعظمة هذا النبي الكريم، عسى أن يكون هذا باعثاً لنا على إصلاح ما أفسده بعدنا عن المنهج الإلهي، والتأسي بمنقذ البشرية من الضلال والتيه صلى الله عليه وسلم.',
'Nektari i vulosur i Xhenetit',
'Nevoja e umetit për njohjen e sires (jetëpërshkrimit) të Pejgamberit (paqja dhe mëshira e Allahut qofshin mbi të) si dhe përfitimi nga burimi i virtyteve të tij, është shumë e madhe dhe e domosdoshme. Sireja është dhe do të mbetet fondi historik, burimi kulturor dhe metodologjia shkencore e praktike nga e cila do të përfitojnë brezat njëri pas tjetrit. Çdokush që shpreson shpërblimin e Allahut dhe takimin me Të në botën tjetër e konsideron të Dërguarin e Tij (paqja dhe mëshira e Allahut qofshin mbi të) shëmbëlltyrë të tij. Allahu i lartësuar thotë: “Ju e kishit shembullin më të lartë në të dërguarin e Allahut, kuptohet, ai që shpreson në shpërblimin e Allahut në botën tjetër, ai që atë shpresë e shoqëron duke e përmendur shumë shpesh Allahun.” [El Ahzab: 21] Për shkak të rëndësisë së njohjes së Sires e kemi shtuar edhe këtë libër i cili veçohet me metodologjinë e tij të lehtë dhe të thjeshtë. Libri ka fituar çmimin e parë në garën për librin më të mirë të shkruar rreth Sires. Garë të cilën në vitin 1396 h. e ka organizuar Liga e Botës Islame.',
'http://www.islamhouse.com/p/289730',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Nektari_i_vulosur_i_Xhennetit.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Nektari_i_vulosur_i_Xhennetit.doc',
'Safijurr-Rrahman El Mubarekfuri',
'',
'',
''),

'41'=>array(
'41',
'Shqip',
'صور من حياة الصحابة',
'صور من حياة الصحابة : هذا الكتاب يعرض صوراً من حياة مجموعة من نجوم الهداية التى نشأت فى أحضان المدرسة المحمدية بأسلوب جمع بين البلاغة الأدبية والحقيقة التاريخية .. فيجد طالب الأسلوب الإنشائي فى هذا الكتاب بغيته، وناشد الفن القصصي طلبته، والساعي إلى التأسي بالكرام ما يرضيه ويغنيه، والباحث عن الحقيقه التاريخية ما يفي بغرضه.',
'Fragmente nga jeta e Sahabëve',
'Ky libër paraqet fragmente nga jeta e një numër të shokëve të Pejgamberit (paqja dhe mëshira e Allahut qofshin mbi të). Atyre të cilët ishin yje të udhëzimit dhe të cilët u edukuan në djepin e shkollës profetike. Lexuesi që hulumton bukurinë gjuhësore dhe artin e tregimit do ta gjen në këtë libër. Ai që mundohet që t’i merr shëmbëlltyrë këta burra fisnikë do ta arrin dëshirën e tij, sikur që edhe ai që e hulumton të vërtetën historike do ta percepton atë.',
'http://www.islamhouse.com/p/289724',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Fragmente_nga_jeta_e_Sahabeve.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Fragmente_nga_jeta_e_Sahabeve.doc',
'Abdurr-Rrahman Rafet Basha',
'',
'',
''),

'42'=>array(
'42',
'Shqip',
'وصايا نبوية',
'هذه الرسالة شرح فيها المؤلف - رحمه الله - خمسة أحاديث نبوية، والتي اشتملت على عدة وصايا مهمة.',
'Porosi Profetike',
'Libër të cilin e shkroi Shejhu i nderuar Abdul Kadër El Arnauti (Allahu e mëshiroftë) në të cilin përmblodhi pesë hadithe të cilat përmbajnë në vete porosi dhe këshilla gjithëpërfshirëse duke iu dhënë një koment të shkurtër por, tërheqës dhe të thuktë.',
'http://www.islamhouse.com/p/289720',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Porosi_profetike.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Porosi_profetike.doc',
'AbdulKadir El Arnaut',
'Rijad Misini',
'',
''),

'43'=>array(
'43',
'Shqip',
'رمضان شهر الله',
'مقالات كثيرة، وإرشادات مختلفة حول كثير من الموضوعات التي تتعلق بشهر رمضان وصيامه. هذا الكتاب المختار ييسر لكم معرفة عدد من الأحكام، والتدبر حول هذا الشهر المبارك.',
'Ramazani muaji i Allahut',
'Artikuj të shumtë, udhëzime të ndryshme, përfshirje e suksesshme e një sërë tematikash që lidhen me Ramazanin dhe agjërimin e tij. Ky libër i përzgjedhur ju mundëson të njiheni me një sërë dispozita, urtësi dhe meditime rreth këtij muaji të bekuar.',
'http://www.islamhouse.com/p/231890',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Ramazani_muaji_i_Allahut.zip',
'Një Grup Hoxhallarësh',
'',
'Driton Lekaj',
''),

'44'=>array(
'44',
'Shqip',
'التجويد الميسر للقرآن الكريم',
'رسالة مختصرة تبين أحكام تجويد القرآن الكريم.',
'Texhvid i preferuar Kuran per te lexuar',
'Kurani Fisnik është i veçantë edhe për metodologjinë e të lexuarit. Për ta lexuar atë drejtë dhe saktë patjetër duhet t’iu përmbahemi rregullave të leximit të tij. Kjo na mundëson neve ta zbatojmë urdhrin e Allahut dhe ta arrijmë shpërblimin e përgatitur për këtë. Libri rreth texhvidit i hoxhes Shefqet Krasniqi është libër praktik nëpërmes të cilit mund ta drejt lexojmë Librin e Allahut.',
'http://www.islamhouse.com/p/231877',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Texhvidi_i_preferuar_Kuran_per_te_lexuar.pdf',
'Dr. Shefqet Krasniqi',
'',
'Uthman Abbasi',
''),

'45'=>array(
'45',
'Shqip',
'فصول في الصيام والتراويح والزكاة',
'هذا الكتيب يحتوي على ثمانية فصول في الصيام والتراويح والزكاة وهي: الفصل الأول: في حكم الصيام. الفصل الثاني: في فوائد الصيام وحكمه. الفصل الثالث: في صيام المسافر والمريض. الفصل الرابع: في مفسدات الصيام. الفصل الخامس: في التراويح. الفصل السادس: في الزكاة وفوائدها. الفصل السابع: في أهل الزكاة. الفصل الثامن: في زكاة الفطر. ويليه ملحق في كيفية إخراج الزكاة.',
'Rregullat e Agjërimit, Teravive dhe Zekatul Fitrit',
'Ky libërth i shkruar nga dijetari Ibn El Uthejmin ngërthen në vete një mori rregullash të cilat lidhen me Agjërimin, Teravitë dhe Zekatul Fitrin. Me një metodë të lehtë dhe të kuptuar, dijetari i nderuar i përmend këto dispozita dhe rregulla të cilat janë të domosdoshme për ta kryer adhurimin e agjërimit dhe adhurimet e tjera që e pasojnë në mënyrën më të mirë.',
'http://www.islamhouse.com/p/231844',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_lessons_on_fasting_taraweeh_zakatat.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_lessons_on_fasting_taraweeh_zakatat.doc',
'Muhamed b. Salih El Uthejmin',
'Driton Lekaj',
'',
'Zyra e Bashkëpunimit për Dave dhe Vetëdijësim të Komuniteteve - Rebve - www.islamhouse.com'),

'46'=>array(
'46',
'Shqip',
'رياض الصالحين',
'كتاب رياض الصالحين للإمام المحدث الفقيه أبي زكريا يحيى بن شرف النووي المتوفى سنة 676هـ - رحمه الله - من الكتب المهمة، وهو من أكثر الكتب انتشاراً في العالم؛ وذلك لاشتماله على أهم ما يحتاجه المسلم في عباداته وحياته اليومية مع صحة أحاديثه - إلا نزراً يسيراً - واختصاره وسهولته وتذليل المصنف لمادته، وهو كتاب ينتفع به المبتديء والمنتهي.',
'Rijadus Salihin',
'Një ndër enciklopeditë më të njohura të Hadithit. Ky libër do të jetë udhërrëfyes për secilin që ndi¬hmohet me të dhe shërbehet në kërkimin dhe veprimin e veprave të mira, si dhe do të jetë ndalesë prej të këqijave dhe katas¬trofave të ndryshme. Me pak fjalë ky libër është një ndër librat pa të cilat nuk duhet të mbetet shtëpia e myslimanit.',
'http://www.islamhouse.com/p/231837',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_riyad_alsaliheen.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_riyad_alsaliheen.doc',
'Ebu Zekerija En Nevevi',
'',
'',
''),

'47'=>array(
'47',
'Shqip',
'من عقائد الشيعة',
'من عقائد الشيعة : هذه الرسالة تبين بعض معتقدات الشيعة على طريقة السؤال والجواب بصورة مختصرة.',
'Disa bindje te Shi’iteve',
'Shiitët janë një ndër grupet e devijuara më të përhapura në botën islame. Idetë dhe mendimet e tyre janë nuk përkojnë me burimet Islame. Ky libër flet rreth bindjeve dhe kundërshtimeve të tyre me Islamin. Megjithëse i shkurtër ky libër me fakte dhe argumente qartëson devijimin dhe rrezikshmërinë e tyre për Islamin dhe myslimanët.',
'http://www.islamhouse.com/p/231822',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_creed_the_shiites.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_creed_the_shiites.doc',
'Abdullah b. Muhamed Es Selefij',
'Bahri Curri',
'Rijad Misini - Arijan Kutelli',
''),

'48'=>array(
'48',
'Shqip',
'وصايا قرآنية',
'كتاب مفيد، يحتوي على بعض الوصايا المذكورة في القرآن الكريم، الكتاب مترجم من الإنجليزية، وهو من تأليف: محمد بكثال و فاتح محمد.',
'Porosi Kuranore',
'Ky libër është tërheqës dhe i veçantë në përpilimin e tij. Libri është i ndarë në tematika të ndryshme të cilat argumentohen me ajete të ndryshme Kuranore që kanë të bëjnë me këto tematika. Ky libër është i dobishëm edhe për të gjithë ata që përgatitin ndonjë ligjëratë dhe iu intereson ndarja tematikore e ajeteve. M.M. Pikthal & M. Fateh Muhammad',
'http://www.islamhouse.com/p/228778',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_quranic_commandments.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_quranic_commandments.doc',
'',
'Fehim Dragusha',
'Driton Lekaj',
''),

'49'=>array(
'49',
'Shqip',
'عثرات الطريق',
'عثرات الطريق : فإن الطريق إلى الدار الآخرة طويلة وشاقة.. لا تخلو من عثرة وغفلة.. ومن تأخر وزلة.. ولكل مسلم ومسلمة عثرة يعقبها استغفار وتوبة ورجوع وأوبة.. من عثرات الطريق إهمال الطاعات وإضاعة النوافل وإتيان المحرمات والمكروهات.. وعلم على ذلك.. إضاعة الأعمار والأوقات. والعثرات قلت أو كثرت تكون هاوية يصعب صعودها والخروج منها على من لم يتجهز ويستعد ويستنفد الوسع.. وربما تكون هذه العثرات فاتحة خير وطريق توبة.. وبداية انطلاقة للوصول إلى النهاية.. هناك حيث تغرب شمس الدنيا ويبدأ إشراق الآخرة.. في جنات عدن وروح وريحان. وفي هذه الرسالة بيان بعض العثرات مع كيفية علاجها.',
'Pengesat në rrugë',
'Rruga për në Ahiret është e gjatë dhe në të hasim pengesa të shumta. Autori në këtë libër flet rreth këtyre pengesave dhe paraqet metodën e largimit të tyre nën dritën e Kuranit dhe Synetit si dhe vë theksin se besimtari duhet të qëndrojë i paluhatur derisa të arrijë në fund të kësaj rruge.',
'http://www.islamhouse.com/p/228769',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_obstacles_in_the_way.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_obstacles_in_the_way.doc',
'AbdulMelik El Kasim',
'Driton Maxhuni',
'Bahri Curri',
''),

'50'=>array(
'50',
'Shqip',
'الدليل المصور الموجز لفهم الإسلام',
'كتاب الدليل المصور الموجز لفهم الإسلام باللغة الألبانية، والذي يتحدث بصفة خاصة عن الإعجاز العلمي في الإسلام، وأيضاً يُعنى بمفاهيم الإسلام وتصوره تجاه الفرد والمجتمع، والمكاسب التي تتحقق لك حالة كونك مسلماً ملتزماً بتعاليم الشريعة الإسلامية. هذا الكتاب تصدر قائمة الكتب الدعوية الموجهة لغير المسلمين في عظيم أثره، لذا يحرص المتخصصون في التعريف بالإسلام بالبدء بإهداء ترجمة معاني القرآن الكريم بلغة غير المسلم ثم يليه في قائمة الإهداء هذا الكتاب، ثم بقية الكتب الدعوية الأخرى.',
'Udhëzues i ilustruarmbi Islamin',
'Libri “Udhëzues i ilustruar mbi Islamin” flet veçanërisht për mrekullinë shkencore në Islam dhe gjithashtu vë theksin në konceptet e Islamit dhe perceptimin e tij për individin dhe shoqërinë si dhe përfitimet të cilat i realizohen atij që e pranon islamin dhe i përmbahet sinqerisht mësimeve të Islamit. Ky libër prinë para librave të tjera të cilat ju drejtohen jo muslimanëve pëe shkak të ndikimi të madh të tij. Për këtë, ekspertët në thirrjen e jomyslimanëve kujdesen që fillimisht t’ua dhurojnë Kuranin në gjuhën e këtij jomyslimani e pas tij në listën e librave që i dhurohen është ky libër.',
'http://www.islamhouse.com/p/193469',
'http://d1.islamhouse.com/data/sq/ih_books/sq_brief_illustrated_guide_to_understanding_islam.pdf',
'Ibrahim Ebu Harb',
'',
'',
''),

'51'=>array(
'51',
'Shqip',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة : التحليل العادل والجواب الشافي عن الأسئلة التالية: هل اليهودية والمسيحية والإسلام يشتركون في نفس العقائد الخاصة بالمرأة؟ هل حقاً اليهودية والمسيحية أكرموا المرأة أكثر من الإسلام؟ ما الحقيقة؟',
'Gratë në Islam kundrejt grave në traditën Judeo-Kristiane: Miti dhe realiteti',
'Titulli i librit: Gratë në Islam kundrejt grave në traditën Judeo-Kristiane: Miti dhe realiteti Autor: Dr. Sherif Abdel Azīm Përktheu: Edin Q. Lohja Botues: Conveying Islamic Message Society, Aleksandri 2008 Citimet e Biblës janë marrë nga Bibla – Diodati i Ri. Citimet e vargjeve nga librat deuterokanonikë janë marrë nga versioni në shqip DSF (Don Simon Filipaj). Citimet e Kur’anit janë marrë nga Kur’ani – përkthim me komentim nga Sherif Ahmetit. Ndalohet shumëzimi, kopjimi ose transmetimi i këtij libri pa lejen e botuesit.',
'http://www.islamhouse.com/p/191531',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_women_in_islam_and_women_in_the_jewish_and_christian_faith.pdf',
'Sherif AbdulAdhim',
'',
'',
'Uebfaqja e Shoqatës \'Kumtimi i Islamit\' - http://www.islamic-message.net'),

'52'=>array(
'52',
'Shqip',
'شرح ثلاثة الأصول',
'ثلاثة الأصول وأدلتها : رسالة مختصرة ونفيسة صنفها الإمام المجدد محمد بن عبد الوهاب - رحمه الله - تحتوي على الأصول الواجب على الإنسان معرفتها من معرفة العبد ربه, وأنواع العبادة التي أمر الله بها، ومعرفة العبد دينه، ومراتب الدين، وأركان كل مرتبة، ومعرفة النبي - صلى الله عليه وسلم - في نبذة من حياته، والحكمة من بعثته، والإيمان بالبعث والنشور، وركنا التوحيد وهما الكفر بالطاغوت,والإيمان بالله، وقد قام بشرحها فضيلة العلامة الشيخ محمد بن صالح العثيمين - رحمه الله -.',
'Shpjegimi i tre parimeve bazë të Islamit',
'-',
'http://www.islamhouse.com/p/156162',
'http://d1.islamhouse.com/data/sq/ih_books/sq_Explanation_of_the_Three_Fundamental_Principles_ibn_othaimeen.pdf',
'Muhamed b. Salih El Uthejmin',
'',
'',
'Uebfaqja Sajd El Fevaid - www.saaid.net'),

'53'=>array(
'53',
'Shqip',
'القرآن الكريم وترجمة معانيه إلى اللغة الألبانية',
'',
'Kurani Fisnik dhe përkthimi i domethënieve të tij në gjuhën shqipe',
'Ky është përkthimi më i njohur i domethënieve të Kuranit Fisnik në shqip. Ky botim ka pas fatin të botohet nga Kompleksi i Mbretit Fehd për botimin e Kuranit si dhe është i vetmi përkthim që është i shoqëruar me komentim.',
'http://www.islamhouse.com/p/232',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_translation_of_meaning_of_holy_quran_in_albanian.pdf',
'',
'',
'',
'Kompleksi i Mbretit Fehd për Botimin e Kuranit'),

'54'=>array(
'54',
'Shqip',
'ثلاثة الأصول وأدلتها',
'ثلاثة الأصول : رسالة مختصرة ونفيسة تحتوي على الأصول الواجب على الإنسان معرفتها من معرفة العبد ربه, وأنواع العبادة التي أمر الله بها، ومعرفة العبد دينه، ومراتب الدين، وأركان كل مرتبة، ومعرفة النبي - صلى الله عليه وسلم - في نبذة من حياته، والحكمة من بعثته، والإيمان بالبعث والنشور، وركنا التوحيد وهما الكفر بالطاغوت,والإيمان بالله.',
'Tre parimet',
'Si ta njohësh Allahun? Si ta njohësh fenë tënde? Si ta njohësh të dërguarin tonë Muhamedin (Paqja dhe bekimi i Allahut qofshin mbi të)? Këto janë tri parimet në të cilat përgjigjet autori në këtë libër të thjeshtë në volumin e tij por, të argumentuar në përmbajtjen e tij.',
'http://www.islamhouse.com/p/228',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_three_assets.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_three_assets.doc',
'Muhamed b. Abdul Vehab',
'',
'Enes Goga - Mehdi Goga',
'Uebfaqja e Universitetit Islamik në Medinën e Ndritshme'),

'55'=>array(
'55',
'Shqip',
'أركان الإيمان',
'أركان الإيمان: هذه الدراسة عن أركان الإيمان هي أحد برامج العمادة العلمية، حيث وجّهت بعض أعضاء هيئة التدريس بالجامعة للكتابة في الموضوع ثمّ كلّفت اللجنة العلمية بالعمادة بدراسة ما كتبوه واستكمال النقص وإخراجه بالصورة المناسبة، مع الحرص على ربط القضايا العلمية بأدلّتها من الكتاب والسنّة. وتحرص العمادة - من خلال هذه الدراسة - إلى تمكين أبناء العالم الإسلامي من الحصول على العلوم الدينية النافعة؛ لذلك قامت بترجمتها إلى اللغات العالمية ونشرها وتضمينها شبكة المعلومات الدولية - الإنترنت -.',
'Shtyllat e besimit',
'Ky është një libër që flet për kushtet e imanit – besimit duke argumentuar secilën nga ato me argumente të shumta. Libri është botim i Univeristetit Islamik të Medinës i cili mëton të prezantojë kushtet e imanit me një metodë të lehtë dhe sistematizuar mirë.',
'http://www.islamhouse.com/p/226',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_pillars_of_faith.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_pillars_of_faith.doc',
'Dekanati për Hulumtime Shkencore pranë Universitetit Islamik të Medinës',
'',
'Enes Goga',
'Uebfaqja e Universitetit Islamik në Medinën e Ndritshme'),

'56'=>array(
'56',
'Shqip',
'عقيدة أهل السنة والجماعة',
'عقيدة أهل السنة والجماعة: تشتمل هذه الرسالة على بيان عقيدة أهل السنة والجماعة في باب توحيد الله وأسمائه وصفاته، وفي أبواب الإِيمان بالملائكة، والكتب، والرسل، واليوم الآخر، والقدَر خيره وشره.',
'Besimi i Ehli Sunetit',
'Besimi i Ehli Sunetit: Ky libërth përmban sqarimin e akides së Ehli Synetit dhe Xhematit në kaptinën e njësimit të Allahut, emrave të atributeve të Tij si dhe në kapitujt e besimi në Melekë, Libra, Pejgamberë, Botës Tjetër dhe Caktimit të Allahut për të mirë dhe të keqe.',
'http://www.islamhouse.com/p/222',
'http://d1.islamhouse.com/data/sq/ih_books/single/sq_Besimi_i_Ehli_Sunetit.pdf,http://d1.islamhouse.com/data/sq/ih_books/single/sq_Besimi_i_Ehli_Sunetit.doc',
'Muhamed b. Salih El Uthejmin',
'Dr. Shefqet Krasniqi',
'',
'')

);
?>