<?php
$BOOKS = array(
'1'=>array(
'1',
'Swedish',
'هذا هو محمد صلى الله عليه وسلم',
'رسالة من إصدار موقع طريق الإسلام www.islamway.com تعرف برسول الإسلام سيدنا محمد صلى الله عليه وسلم.',
'Detta Är Er Mohammad (Frid vare med honom)',
'-',
'http://www.islamhouse.com/p/330859',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_Detta_ar_Er_Mohammad.pdf',
'',
'',
'',
''),

'2'=>array(
'2',
'Swedish',
'صفة الوضوء والصلاة بالصور',
'ملف باللغة السويدية يبين كيفية الوضوء والصلاة بالصور.',
'Tvagningens & bönens beskrivning',
'-',
'http://www.islamhouse.com/p/330857',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_Tvagningens_bonens_beskrivning.pdf',
'',
'',
'',
''),

'3'=>array(
'3',
'Swedish',
'الهدف من الحياة',
'محاضرة رائعة وممتعة ألقاها الشيخ خالد ياسين في المملكة العربية السعودية عام 1994 م، وأسفرت عن إسلام 43 شخصا في تلك الليلة، وقد تم تفريغها وترجمتها إلى اللغة السويدية.',
'Vad är meningen med livet?',
'Detta häfte är en översättning av ett tal som broder Khalid Yasin höll i Saudi-Arabien 1994. Föredraget har blivit mycket uppskattat bland såväl muslimer som icke- muslimer runtom i världen. Den tar upp viktiga fundament i Islam och ger en överblick om Islams största grund som är tron på en sann och Allsmäktig Gud. Broder Khalid Yasin tar upp Islams viktigaste grundpelare på ett sätt som ger läsaren (lyssnaren) ett nöje i att få ta del av denna information, och ger många exempel och paralleller som gör det enkelt för var och en att förstå vad meningen med livet innebär och vad Islam handlar om. Det är härmed ett sant nöje att få presentera denna föreläsning i skriven form och vi hoppas att var och en som läser den skall finna klarhet och vägledning i den.',
'http://www.islamhouse.com/p/330853',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_Vad_ar_meningen_med_livet.pdf',
'',
'',
'',
''),

'4'=>array(
'4',
'Swedish',
'أنت تسأل والقرآن يجيب',
'رسالة لطيفة باللغة السويدية تحتوي على 32 سؤال أجاب عنها الكاتب من خلال آيات القرآن الكريم. 1- من هو الخالق؟ 2- من هو الله؟ 3- هل تعتقد أن الله خلقنا عبثاً بدون أي هدف؟ 4- لماذا خلق الله الخلق؟ 5- ماذا أمرنا الله أن نفعل؟ 6- من أين نطلب الرشد؟ 7- لمن نلجأ في وقت المحن والمصائب؟ 8- هل حفظ الله القرآن من التحريف؟ 9- ماذا حصل للأمم السابقة عندما عصوا الله؟ 10- لمن تجب العبادة؟ 11- ماهو دين الله؟ 12- ماهو الدين الذي ارتضاه الله لنا وابتغاه؟ 13- من أين أتى (أنزل) القرآن؟ 14- لماذا أرسل الله الرسل؟ 15- هل يجب علينا الإيمان بالرسل؟ 16- ماذا حصل للكتب السابقة؟ 17- من هو آخر الرسل؟ 18- لمن أرسل الله آخر الرسل(محمد صلى الله عليه وسلم)؟ 19- ماذا أعد الله للمؤمنين من اليهود والنصارى؟ 20- ماهو مثل عيسى عند الله؟ 21- ماذا قال الله عن مريم؟ 22- هل صلب عيسى عليه السلام؟ 23- هل عيسى ابن الله؟ 24- كيف يتحقق لنا الأمن؟ 25- ماهي الحياة الدنيا؟ 26- هل النعم التي ننعم بها من الله؟ 27- ما الذي يزيد لنا النعمه من الله؟ 28- كيف تقي نفسك من العذاب الأليم؟ 29- ماهو جزاء من اتقى بالله؟ 30- ما هو مصير المكذبين؟ 31- ماهو مصير المؤمنين؟ 32- كيف تتحقق لنا السعادة؟.',
'Du frågar & Koranen besvarar',
'-',
'http://www.islamhouse.com/p/330851',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_Du_frgar_Koranen_besvarar.pdf',
'',
'',
'',
''),

'5'=>array(
'5',
'Swedish',
'الأربعون النووية',
'هذه الصفحة تحتوي على ترجمة الأربعين النووية إلى اللغة السويدية، وهو متن مشهور، اشتمل على اثنين وأربعين حديثاً محذوفة الإسناد في فنون مختلفة من العلم، كل حديث منها قاعدة عظيمة من قواعد الدين، وينبغي لكل راغب في الآخرة أن يعرف هذه الأحاديث؛ لما اشتملت عليه من المهمات، واحتوت عليه من التنبيه على جميع الطاعات؛ وقد سميت بالأربعين في مباني الإسلام وقواعد الأحكام.',
'40 Hadith av Imam an-Nawawi',
'-',
'http://www.islamhouse.com/p/330849',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_40_Hadith_av_Imam_Nawawi.pdf',
'',
'',
'',
''),

'6'=>array(
'6',
'Swedish',
'الدروس المهمة لعامة الأمة',
'الدروس المهمة لعامة الأمة: هذه الرسالة على صغر حجمها جمع المؤلف - رحمه الله - بين دفتيها سائر العلوم الشرعية من أحكام الفقه الأكبر والفقه الأصغر، وما ينبغي أن يكون عليه المسلم من الأخلاق الشرعية والآداب الإسلامية، وختم هذه الرسالة بالتحذير من الشرك وأنواع المعاصي، فأتت الرسالة بما ينبغي أن يكون عليه المسلم عقيدة وعبادةً، وسلوكا ومنهجا، فهذه الرسالة اسم على مسمى فهي بحق الدروس المهمة لعامة الأمة.',
'Viktiga Lektioner för den Muslimska Nationen',
'-',
'http://www.islamhouse.com/p/322547',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_Viktiga_Lektioner_for_den_Muslimska_Nationen.pdf',
'',
'',
'',
''),

'7'=>array(
'7',
'Swedish',
'مختصر القرآن الكريم والتوراة والإنجيل والعلم [ دراسة الكتب المقدسة في ضوء المعارف الحديثة ]',
'الرسالة التي بين بين أيدينا جاءت ردأً على طغيان المادية التي تزعم أن الدين والعلم لا يلتقيان وهي تهدف إلى تقديم دراسة مقارنة عن الكتب المقدسة في ضوء المعارف العلمية الحديثة.',
'Koranen och modern vetenskap',
'Koranen och modern vetenskap',
'http://www.islamhouse.com/p/308009',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_Bibel_Koran_und_Wissenschaft.pdf',
'',
'',
'',
''),

'8'=>array(
'8',
'Swedish',
'رسالة واحدة فقط!',
'رسالة واحدة فقط! : يتكلم هذا الكتاب عن رسالة التوحيد الواحدة التي حملها جميع الأنبياء والرسل من لدن آدم - عليه السلام - إلى نبينا محمد - صلى الله عليه وسلم -. ويمتاز .. بإثبات توحيد ( وحدانية ) الله من كتب اليهود والنصارى ( العهد القديم والعهد الجديد ) التي بين أيديهم في وقتنا المعاصر.',
'BARA ETT BUDSKAP!',
'BARA ETT BUDSKAP!',
'http://www.islamhouse.com/p/265470',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_just_one_message01.pdf,http://d1.islamhouse.com/data/sv/ih_books/single/sv_just_one_message02.pdf',
'',
'',
'',
''),

'9'=>array(
'9',
'Swedish',
'من عقائد الشيعة',
'من عقائد الشيعة : هذه الرسالة تبين بعض معتقدات الشيعة على طريقة السؤال والجواب بصورة مختصرة.',
'Några av Shî´ahs trosuppfattningar',
'Bland muslimer i allmänhet tillhör shî’ah bland de mest kända sekterna. I denna bok redogör författaren ’Abdullâh bin Muhammad as-Salafî för en mängd av deras vilseledande trosuppfattningar med bevis från bl.a. deras egna källor eftersom även många shî’iter själva inte är medvetna om dessa aspekter. Boken belyser frågor som: deras syn på Koranen, Profeten och Följeslagarna, Ahlus-Sunnah, ’Ashûra-dagen, Allâh Egenskaper m.m.',
'http://www.islamhouse.com/p/260289',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_creed_shiah.pdf',
'',
'',
'',
''),

'10'=>array(
'10',
'Swedish',
'شروط الصلاة',
'بيان أحكام الصلاة بصورة موجزة.',
'Shurut-us-Salah [Bönens villkor]',
'innehåll: Sheikh Muhammad bin ’Abdil-Wahhâb behandlar i denna bok de vilkor som krävs för att en individs bön skall vara giltig. Därefter går han vidare med att behandla bönens pelare och åläggningar.',
'http://www.islamhouse.com/p/204121',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_shurut_salah.pdf',
'',
'',
'',
''),

'11'=>array(
'11',
'Swedish',
'أحكام الطهارة',
'بيان أحكام الطهارة بصورة موجزة.',
'Ahkâm-ut-Tahârah [Reningens domar]',
'innehåll: Shaykh bin ´Uthaymîn går i denna bok punktvis igenom renlighetens domar och utföranden. Till detta ämne tillhör frågor som tvagning, bad och Tayammum. Dessutom finns en mängd fotnoter kring ämnet med rapporteringar från Profeten (sallâ Allâhu aleihi wa sallam), Sahâbah, Salaf, Sahîh al-Bukhari & al-Muslim etc.',
'http://www.islamhouse.com/p/204119',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_Reningens_domar.pdf',
'',
'',
'',
''),

'12'=>array(
'12',
'Swedish',
'مختصر كتاب الحوادث والبدع',
'مختصر كتاب الحوادث والبدع، اختصره زياد مصطفى.',
'Kitâb al-Hawâdith wal-Bid´a [Guldkorn om Bid`ah]',
'innehåll: Efter att ha läst ut Imâm Abû Bakr Muhammad bin al-Walîd at-Tartûshîs (530 H – rahimahullâh) fenomenala bok ”Kitâb-ul-Hawâdith wal-Bid´a”, fann vi oerhört många viktiga lektioner och skinande juveler rörande Bid´a och andra vardagliga frågor som vi tänkte dela med oss.',
'http://www.islamhouse.com/p/204115',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_tartushi_guldkorn_bidah.pdf',
'',
'',
'',
''),

'13'=>array(
'13',
'Swedish',
'جواهر الآجري',
'مختارات من كتاب الشريعة للإمام الآجري - رحمه الله -.',
'al-Âdjurrîs juveler',
'innehåll: Ibn ´Abbâs (radhiya Allâhu ´anhumâ) sade: ”Allâh (´azza wa djall) beordrade de troende att vara enade och Han förbjöd dem från splittring och uppdelning. Han talade om för dem att deras föregångare endast gick under på grund av att de tvistade och disputerade om Allâhs (´azza wa djall) religion.”',
'http://www.islamhouse.com/p/204112',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_alajeri_jewels.pdf',
'',
'',
'',
''),

'14'=>array(
'14',
'Swedish',
'مناسك الحج والعمرة في ضوء الكتاب والسنة وآثار السلف',
'في هذه الرسالة بيان مناسك الحج والعمرة في ضوء الكتاب والسنة وآثار السلف، وسرد ما ألحق الناس بها من البدع.',
'Manâsik-ul-Hadjdj wal-´Umrah fîl-Kitâb was-Sunnah wa Âthâr-is-Salaf [Vallfärdens och ´Umrahs ritualer baserade på Boken, Sunnah och Salafs rapporteringar]',
'innehåll: Jag ger dessa råd och gagnade uppgifter till våra vallfärdande bröder innan vallfärden: Vallfärdaren är ålagd att frukta sin Herre och kämpa hårt för att inte falla i det Allâh förbjudit. Han (ta´âlâ) sade: ”Vallfärden [skall fullgöras under] de kända månaderna. Den som då beger sig i väg skall så länge vallfärden varar avhålla sig från intim samvaro med kvinnor, grovt tal samt trätor och tvister.”',
'http://www.islamhouse.com/p/204103',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_manasik_of_hajj_and_umrah.pdf',
'',
'',
'',
''),

'15'=>array(
'15',
'Swedish',
'شرح القواعد الأربع',
'القواعد الأربع: رسالة مختصرة كتبها الإمام المجدد شيخ الإسلام محمد بن عبد الوهاب - رحمه الله - وقد اشتملت على تقرير ومعرفة قواعد التوحيد، وقواعد الشرك، ومسألة الحكم على أهل الشرك، والشفاعة المنفية والشفاعة المثبتة، وقد شرحها العلامة الشيخ صالح بن فوزان الفوزان - حفظه الله تعالى -.',
'Sharh al-Qawâ´id al-Arba´ah [Förklaring till de Fyra grunderna]',
'innehåll: Detta är förklaringen av ”al-Qawâ´id al-Arba´ah” [De fyra grunderna] som skrivits av Shaykh-ul-Islâm Muhammad bin ´Abdil-Wahhâb (rahimahullâh). Det är en enskild bok som brukar tryckas tillsammans med ”Thalâthat-ul-Usûl” pga. behovet av den, så att den finns inom studenternas räckhåll. ”Qawâ´id” är plural av ordet ”Qâ´idah”, som betyder: ”en grund från vilken det fördelas många frågor eller förgreningar”. Dessa fyra grunder som Shaykhen (rahimahullâh) nämnt består av kunskapen om Tawhîd [monoteismen] och Shirk [polyteismen och avguderi].',
'http://www.islamhouse.com/p/204101',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_sharh_qawaaid_arbah.pdf',
'',
'',
'',
''),

'16'=>array(
'16',
'Swedish',
'شرح نواقض الإسلام',
'اعلم أيها المسلم أن الله - سبحانه وتعالى - أوجب على جميع العباد الدخول في الإسلام والتمسك به والحذر مما يخالفه، وبعث نبيه محمدا - صلى الله عليه وسلم - للدعوة إلى ذلك، وأخبر - عز وجل - أن من اتبعه فقد اهتدى، ومن أعرض عنه فقد ضل، وحذر في آيات كثيرات من أسباب الردة، وسائر أنواع الشرك والكفر، وذكر العلماء رحمهم الله في باب حكم المرتد أن المسلم قد يرتد عن دينه بأنواع كثيرة من النواقض التي تحل دمه وماله، ويكون بها خارجا من الإسلام، وقد بين الشيخ - أثابه الله - بعض هذه النواقض.',
'Sharh Nawâqidh-il-Islâm [Förklaring till de faktorer som nollställer Islâm]',
'innehåll: Tio faktorer nollställer ens Islâm – Nollställande faktorer är upphävande faktorer. Exempel på det är faktorer som nollställer tvagningen. Ett annat namn är ”avfallsfaktorer” eller ”typer på avfall”. Kunskap om dessa faktorer är oerhört viktig för en Muslim så att han kan undvika dem och hålla sig borta från dem. Om en Muslim inte har kunskap om dem, finns det risk att han faller i någon av dem.',
'http://www.islamhouse.com/p/204099',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_sharh_nawaqidh_islam.pdf',
'',
'',
'',
''),

'17'=>array(
'17',
'Swedish',
'اعتقاد أئمة الحديث',
'اعتقاد أئمة الحديث : هذا أصل الدين والمذهب، اعتقاد أئمة أهل الحديث، الذين لم تشنهم بدعة، ولم تلبسهم فتنة، ولم يخفوا إلى مكروه في دين، ولا تفرقوا عنه.',
'aI´tiqâd A’immah Ahl-il-Hadîth [Hadîth-Imâmernas troslära]',
'innehåll: Håll fast vid er kännedom – må Allâh förbarma Sig över oss och er – att Ahl-ul-Hadîths, Ahl-us-Sunnah wal-Djamâ´ah, metodik är grundad på att tro på Allâh, Hans änglar, Skrifter, sändebud och acceptera det som Allâhs (ta´âlâ) Bok har sagt och det som autentiskt har rapporterats från Allâhs sändebud (sallâ Allâhu ´alayhi wa sallam).',
'http://www.islamhouse.com/p/204095',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_believing_hdeeth_imams.pdf',
'',
'',
'',
''),

'18'=>array(
'18',
'Swedish',
'الواسطة بين الحق والخلق',
'الواسطة بين الحق والخلق: هذه رسالة في رجلين تناظرا فقال أحدهما لا بد لنا من واسطة بيننا وبين الله فإنا لا نقدر أن نصل إليه بغير ذلك.',
'al-Wâsitah bayn al-Haqq wal-Khalq [Medlaren mellan Sanningen och skapelsen]',
'innehåll: Denna lilla bok handlar om två män som hade en debatt. En av dem sade att vi måste ha en medlare mellan oss själva och Allâh (subhânahu wa ta´âlâ), ty vi förmår inte komma fram till Honom utan honom…',
'http://www.islamhouse.com/p/204093',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_connection_between_god_and_the_created.pdf',
'',
'',
'',
''),

'19'=>array(
'19',
'Swedish',
'الرد على الأحباش',
'الأحباش هم تلاميذ عبد الله الحبشي، وهم من الفرق التي تأخذ عقيدتها من علم الكلام القائم على العقل، فهم لا يعتمدون على فهم السلف الصالح للكتاب والسنة وإنما يعتمدون على عقولهم. وقد قام الشيخ الألباني رحمه الله بالرد عليهم ودحض عقائدهم الباطلة في الله عز وجل بأدلة الكتاب والسنة.',
'ar-Radd ´alâ al-Ahbâsh [Avfärdandet av al-Ahbâsh]',
'innehåll: Innan jag börjar svara på denna fråga ska jag lugna alla muslimer, de närvarande och de frånvarande, männen och kvinnorna, att Allâh (tabâraka wa ta´âlâ) är fri från alla platser. När man nämner platsen avses det som inte existerade och därefter skapade Allâh (´azza wa djall) och skapade en plats till alla dessa skapelser av människor, djinner och änglar. Men ordet dessa människor nämner, och de är kända hos kunskapens folk för att uppväcka en dålig Sunnah, hämtad av retorikens kunskap som bygger på förståndet...',
'http://www.islamhouse.com/p/204091',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_rad_ahbash.pdf',
'',
'',
'',
''),

'20'=>array(
'20',
'Swedish',
'صلاة العيدين في المصلى هي السنة',
'في هذه الرسالة إثبات أن صلاة العيدين في المصلى هي السنة.',
'Salât-ul-’Îdayn',
'innehåll: Sheikh Nâsir-ud-Dîn al-Albânî har i denna bok samlat autentiska hadiser och athar gällande de två ’Îd-bönerna, och visar vikten i att följa denna sunnah.',
'http://www.islamhouse.com/p/204089',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_praying_eid_in_the_musallaa_is_the_sunnah.pdf',
'',
'',
'',
''),

'21'=>array(
'21',
'Swedish',
'قيام رمضان',
'رسالة قيام رمضان : فضله وكيفية أدائه، ومشروعية الجماعة فيه، ومعه بحث قيم عن الاعتكاف.',
'Qiyam Ramadhan',
'innehåll: Sheikh Nâsir-ud-Dîn al-Albânî har i denna bok samlat autentiska hadiser och athar gällande nattbönen och itikaf. Ett måste för de som är måna om att följa sunnahn.',
'http://www.islamhouse.com/p/204087',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_night_prayer_ramadan.pdf',
'',
'',
'',
''),

'22'=>array(
'22',
'Swedish',
'العبرة في شهر الصوم',
'العبرة في شهر الصوم : محاضرة ألقيت في مدرسة طيبة الثانوية ليلة الاثنين الموافق 16 شوال عام 1390هـ، وفيها بيان بعض العبر والعظات التي يخرج بها المسلم من شهر الصيام والتي هي الحصيلة الطيبة له في تلك الأيام المباركة.',
'al-´Ibrah fî Shahr-is-Sawm [Lärdomen i fastemånaden]',
'innehåll: Allâh har hedrat denna månad och låtit den vara en av det nästa livets årstid. Däri tävlar tjänarna om att dyrka Allâh för att uppnå segern och närheten till Allâh. De söker Allâhs närhet via daglig fasta och nattlig bön och läsning i Hans mäktiga Skrift.',
'http://www.islamhouse.com/p/204085',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_lesson_in_the_month_of_fasting.pdf',
'',
'',
'',
''),

'23'=>array(
'23',
'Swedish',
'هل المسلم ملزم باتباع مذهب معين من المذاهب الأربعة؟',
'هل المسلم ملزم باتباع مذهب معين من المذاهب الأربعة ؟: هذه الرسالة من أنفس ما كُتِبَ عن الإجتهاد والتقليد، وسبب تأليفها هو ما ذكره المؤلف ـ رحمه الله تعالى ـ في مقدّمتها قائلاً: إنه كان ورد علي ّ سؤال من مسلمي اليابان من بلدة ( طوكيو ) و ( أوزاكا ) في الشرق الأقصى؛ حاصله: ما حقيقة دين الإسلام؟ ثم ما معنى المذهب؟ وهل يلزم على من تشرف بدين الإسلام أن يتمذهب على أحد المذاهب الأربعة؟ أي أن يكون مالكيا أو حنفيا, أو شافعيا, أو حنبليا, أو غيرها أو لا يلزم؟ لأنه قد وقع اختلاف عظيم ونزاع وخيم حينما أراد عدة أنفار من متنوّري الأفكار من رجال اليابان أن يدخلوا في دين الإسلام ويتشرفوا بشرف الإيمان فعرضوا ذلك على جمعية المسلمين الكائنة في طوكيو فقال جمع من أهل الهند ينبغي أن يختاروا مذهب الإمام أبي حنيفة لأنه سراج الأمة، وقال جمع من أهل أندونيسيا يلزم ان يكون شافعيا. فلما سمع اليابانيون كلامهم تعجبوا وتحيروا فيما قصدوا وصارت مسألة المذاهب سدا في سبيل إسلامهم، كانت الرسالة هي الجواب.',
'Är en Muslim ålagd att följa en av de fyra rättskolorna?',
'innehåll: Vad beträffar rättskolorna, är de ingenting annat än de lärdas åsikter och uppfattningar inom vissa frågor och domar. Dessa åsikter, domar och uppfattningar har varken ålagts av Allâh (ta´âlâ) eller Hans sändebud (sallâ Allâhu ´alayhi wa sallam) att följas. De består av både rätt och fel och enbart det som bekräftats från Allâhs sändebud (sallâ Allâhu ´alayhi wa sallam) är ett fläckfritt rätt. Dessutom brukade Imâmerna ta avstånd från de åsikter de brukade hålla sig till efter att ha fått reda på sanningen.',
'http://www.islamhouse.com/p/204082',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_Ar_en_Muslim_alagd_att_folja_en_av_de_fyra_rattskolorna.pdf',
'',
'',
'',
''),

'24'=>array(
'24',
'Swedish',
'شرح السنة',
'شرح السنة : هذا الكتاب يظهر للقارئ من خلال قراءته أهميته وجودته فقد قرب مفاهيم العقيدة السلفية للناس بأسلوب سهل ميسر، وأظهر نصرة السنة ومحاربة البدعة، وشدد الإنكار على أهل الأهواء المضلة، وخلصه من دنس علم الكلام.',
'Sharh-us-Sunnah [Förklaringen av Sunnah]',
'innehåll: Boken förklarar Ahl-us-Sunnahs tro på Allâh, Änglarna, Skrifterna, Sändebuden, Domedagen, tron på Förutbestämmelsen samt beskriver denna trosläras frukter.',
'http://www.islamhouse.com/p/204077',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_explanation_of_sunnah_barbharri.pdf',
'',
'',
'',
''),

'25'=>array(
'25',
'Swedish',
'لمعة الاعتقاد الهادي إلى سبيل الرشاد',
'لمعة الاعتقاد الهادي إلى سبيل الرشاد : للعلامة ابن قدامة المقدسي - رحمه الله - رسالة مختصرة تحتوي على مجمل عقيدة أهل السنة والجماعة.',
'Lum´at-ul-I´tiqâd',
'nnehåll: Ibn Qudâmah al-Maqdisis bok som skänker glänsande klarhet i Ahlus-Sunnahs förhållande till grundläggande principer inom Islam. Med slående korthet och precision släcker Imamen ljuset för de innovatörer som på vilseledande och falska grunder följer en annan väg än den Salaf var på. De avslutande kapitlen tar upp ämnen som hur man skall förhålla sig till det som hände mellan Följeslagarna, makthavarnas rätt över medborgarna, förhållandet till innovatörer.',
'http://www.islamhouse.com/p/204074',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_lomat_alatakad.pdf',
'',
'',
'',
''),

'26'=>array(
'26',
'Swedish',
'كشف الشبهات في التوحيد',
'كشف الشبهات: رسالة نفيسة كتبها الإمام المجدد محمد بن عبد الوهاب - رحمه الله - وهي عبارة عن سلسلة شبهات للمشركين وتفنيدها وإبطالها، وفيها بيان توحيد العبادة وتوحيد الألوهية الذي هو حق الله على العباد، وفيها بيان الفرق بين توحيد الربوبية وتوحيد الإلهية والعبادة.',
'Klargörandet av Tvivlen (Kashf-ush-Shubuhât)',
'innehåll: Detta mästerverk inleds med att förklara syftet med att sända profeterna och sändebuden. Därefter bjuds läsaren på en underbar läsning om trosgrunder anknutna till Tawhîd och Dyrkan. En mängd tvivel avtäcks här och deras sanna natur exponeras. Med bokens etablerade bevisningar ur Qurân och Sunnah får läsaren en tydlig bild av hur denne bör skydda sin själ från Shirk och Kufr. Boken är skriven av Sheikh ibn ’Abdul-Wahhâb som under 1700-talet på den arabiska halvön. Han ägnade sitt liv åt spridandet av Allâhs Religion, Må Allah täcka honom väl i barmhärtighet och belöning för hans tjänst för Islâm och muslimerna.',
'http://www.islamhouse.com/p/204072',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_Klargorandet_av_Tvivlen.pdf',
'',
'',
'',
''),

'27'=>array(
'27',
'Swedish',
'صيام رمضان',
'صيام رمضان: مرجع مختصر يشمل جميع ما يتعلق بأحكام الصيام و شهر رمضان المبارك.',
'Fastan i månaden Ramadân',
'innehåll: En utmärkt bok som i korthet tar upp olika aspekter förpliktelser och fördelar kring fastemånaden. Bland annat förklaras de två kategorier som ogiltigör en persons fasta, likaså vad som inte ogiltiggör fastan Innehåller även andra ämnen som t.ex; I’tiqâf, frivillig fasta, månadens nattböner, Zakât-ul-Fitr.',
'http://www.islamhouse.com/p/204070',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_fasting_of_ramadan_zeenoo.pdf',
'',
'',
'',
''),

'28'=>array(
'28',
'Swedish',
'العقيدة الواسطية',
'العقيدة الواسطية: رسالة نفيسة لشيخ الإسلام ابن تيمية - رحمه الله - ذكر فيها جمهور مسائل أصول الدين، ومنهج أهل السنة والجماعة في مصادر التلقي التي يعتمدون عليها في العقائد؛ لذا احتلت مكانة كبيرة بين علماء أهل السنة وطلبة العلم، لما لها من مميزات عدة من حيث اختصار ألفاظها ودقة معانيها وسهولة أسلوبها، وأيضاً ما تميزت به من جمع أدلة أصول الدين العقلية والنقلية.',
'al-´Aqîdah al-Wâsitiyyah',
'innehåll: Den berömde Sheikh-ul-Islâm Ahmad bin Taymiyyah redogör i detta verk för ett flertal av Ahl-us-Sunnahs trosuppfattningar och ståndpunkter. Med bevis ur Boken och Sunnah visar han tydligt villfarelsen hos sekter som Jahmiyyah, Mushabbihah, Qadariyyah, Jabriyyah, Murji’ah, Wa’îdiyyah, Harûriyyah, Mu’tazilah, Rawâfidh och Khawârij. I bokens avslutande kapitel upplyser han om plikten att följa Allâhs Sändebud (sallâ Allâhu ’aleihi wa sallam) och föregångarnas väg.',
'http://www.islamhouse.com/p/196581',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_aquida_ wasitiah.pdf',
'',
'',
'',
''),

'29'=>array(
'29',
'Swedish',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة : التحليل العادل والجواب الشافي عن الأسئلة التالية: هل اليهودية والمسيحية والإسلام يشتركون في نفس العقائد الخاصة بالمرأة؟ هل حقاً اليهودية والمسيحية أكرموا المرأة أكثر من الإسلام؟ ما الحقيقة؟',
'Kvinnan i islam Kontra kvinnan i den Judisk-Kristna traditionen',
'-',
'http://www.islamhouse.com/p/191546',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_women_in_islam_and_women_in_the_jewish_and_christian_faith.pdf',
'',
'',
'',
''),

'30'=>array(
'30',
'Swedish',
'عقيدة أهل السنة والجماعة',
'عقيدة أهل السنة والجماعة: تشتمل هذه الرسالة على بيان عقيدة أهل السنة والجماعة في باب توحيد الله وأسمائه وصفاته، وفي أبواب الإِيمان بالملائكة، والكتب، والرسل، واليوم الآخر، والقدَر خيره وشره.',
'´Aqîdah Ahl-is-Sunnah wal-Djamâ´ah [Ahl-us-Sunnah wal-Djamâ´ahs troslära]',
'Boken förklarar Ahl-us-Sunnahs tro på Allâh, Änglarna, Skrifterna, Sändebuden, Domedagen, tron på Förutbestämmelsen samt beskriver denna trosläras frukter.',
'http://www.islamhouse.com/p/191249',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_Aqidah_Ahl_is_Sunnah_wal_Djamaah.pdf',
'',
'',
'',
''),

'31'=>array(
'31',
'Swedish',
'إقامة البراهين على حكم من استغاث بغير الله أو صدق الكهنة والعرافين',
'إقامة البراهين على حكم من استغاث بغير الله أو صدق الكهنة والعرافين : رسالةلطيفة عبارة عن ثلاث رسائل مجموعة: الأولى: في حكم الاستغاثة بالنبي - صلى الله عليه وسلم -، والثانية: في حكم الاستغاثة بالجن والشياطين والنذر لهم، والثالثة: في حكم التعبد بالأوراد البدعية والشركية.',
'Iqâmat-ul-Barâhîn [ Fastställandet av bevisen ]',
'Den numera bortgångne Sheikh ’Abdul-Azîz bin Bâz (rahimahu Allâh) besvarar i tre kapitel angelägenheter relaterade till Shirk, dyrkan, bid’ah etc. Med utgångspunkt från en specifik situation förklarar han grundläggande islamiska principer i förhållande varje kapitels ämne. Abû ’Abdullâh Sheikh ’Abdul-Azîz ibn ’Abdullâh ibn ’Abdur-Rahmân Aal-Bâz hade under senare delen av sitt liv positionen som stor Muftî i Saudiarabien. Han avled i Muharram 1420 H / 13 Maj 1999 e.Kr.',
'http://www.islamhouse.com/p/191247',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_Faststallan_det_av_bevisen.pdf',
'',
'',
'',
''),

'32'=>array(
'32',
'Swedish',
'الدليل المصور الموجز لفهم الإسلام',
'كتاب الدليل المصور الموجز لفهم الإسلام باللغة السويدية، والذي يتحدث بصفة خاصة عن الإعجاز العلمي في الإسلام، وأيضاً يُعنى بمفاهيم الإسلام وتصوره تجاه الفرد والمجتمع، والمكاسب التي تتحقق لك حالة كونك مسلماً ملتزماً بتعاليم الشريعة الإسلامية. هذا الكتاب تصدر قائمة الكتب الدعوية الموجهة لغير المسلمين في عظيم أثره، لذا يحرص المتخصصون في التعريف بالإسلام بالبدء بإهداء ترجمة معاني القرآن الكريم بلغة غير المسلم ثم يليه في قائمة الإهداء هذا الكتاب، ثم بقية الكتب الدعوية الأخرى.',
'En kort illustrerad guide för att förstå Islam',
'Denna bok är en kort guide för att förstå islam',
'http://www.islamhouse.com/p/172711',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_En_kort_illustrerad_guide_for_att_forsta_Islam.pdf',
'',
'',
'',
''),

'33'=>array(
'33',
'Swedish',
'ثلاثة الأصول وأدلتها',
'ثلاثة الأصول وأدلتها : رسالة مختصرة ونفيسة تحتوي على الأصول الواجب على الإنسان معرفتها من معرفة العبد ربه, وأنواع العبادة التي أمر الله بها، ومعرفة العبد دينه، ومراتب الدين، وأركان كل مرتبة، ومعرفة النبي - صلى الله عليه وسلم - في نبذة من حياته، والحكمة من بعثته، والإيمان بالبعث والنشور، وركنا التوحيد وهما الكفر بالطاغوت,والإيمان بالله.',
'Thalâthat-ul-Usûl [De Tre Grunderna]',
'-',
'http://www.islamhouse.com/p/61692',
'http://d1.islamhouse.com/data/sv/ih_books/parts/De_Tre_Grunderna/sv_01_De_Tre_Grunderna.pdf,http://d1.islamhouse.com/data/sv/ih_books/parts/De_Tre_Grunderna/sv_02_De_Tre_Grunderna.pdf',
'',
'',
'',
''),

'34'=>array(
'34',
'Swedish',
'الفاتحة وجزء عم وترجمة معانيهما إلى اللغة السويدية',
'',
'Al-Fâtihah och Djuz \'Amma tillsammans med översättningen av dess versers betydelser på svenska',
'-',
'http://www.islamhouse.com/p/439',
'http://d1.islamhouse.com/data/sv/ih_books/single/sv_AlFatihah_och_Djuz_Amma.pdf',
'',
'',
'',
'Kung Fahds Anläggning för Tryckning av den Ädla Koranen')

);
?>