<?php
$BOOKS = array(
'1'=>array(
'1',
'Swahili',
'رسالة الإسلام',
'هو الدين الوحيد الذي ارتضاه الله للبشرية جمعاء، ولن يقبل الله من أحد دينا سواه، وهو الدين الذي يقدم حلولاً لجميع المشاكل التي يعيشها عالمنا اليوم، وإن الأخذ به وتطبيقه كفيل للقضاء عليها، ورسالته شاملة كاملة لجميع مناحي الحياة وشعبها. وهذا الكتاب يحتوى على بيان رسالة الإسلام الخالدة من أصوله ومبادئه الأساسية متمثلة في أركان الإسلام والإيمان، وبيان خصائصه ومحاسنه متمثلة في أحكامه وشرائعه، كما يحتوي على بيان الأوضاع الاقتصادية والاجتماعية والسياسية والأخلاقية وحقوق الإنسان في الإسلام.',
'UJUMBE WA UISLAMU KWA ULIMWENGU MZIMA',
'-',
'http://www.islamhouse.com/p/385737',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_The_Message_of_Islam.pdf,http://d1.islamhouse.com/data/sw/ih_books/single/sw_The_Message_of_Islam.doc',
'',
'',
'',
''),

'2'=>array(
'2',
'Swahili',
'قساوسة اعتنقوا الإسلام',
'هذا الكتاب يجمع عدة مقالات تتكلم عن قصص بعض القساوسة الذين اعتنقوا الإسلام.',
'Makasisi Waingia Uislamu',
'-',
'http://www.islamhouse.com/p/380267',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_makasisi_waingida_uislam.pdf',
'',
'',
'',
''),

'3'=>array(
'3',
'Swahili',
'حوار بين مسلم ونصراني',
'حوار بين مسلم ونصراني: يشتمل هذا الكتاب على خلاصة حوارات متتالية دارت بين المؤلّف وعدد من رجال الدين المسيحي، اتسمت بالموضوعية والأدب الجم، والحرص على تجنب المساس بالمشاعر الدينية، والالتزام بالمنهج العلمي للحوار، على هيئة سؤال وجواب، ليعالج ثمانية قضايا أساسية هي: • هل كان أبراهيم يهوديا أو نصرانيا؟ • كلام الله أم كلام البشر؟ • توحيد أم تثليث؟ • هل المسيح بشر أم إله؟ • هل المسيح ابن الله؟ • هل صُلب المسيح ثم قام؟ • دعوى الخطيئة الأولى والفداء. • محمد صلى الله عليه وسلم رسول الله في الكتاب المقدس.',
'Mazungumzo ya Mwislamu na Mkristo',
'-',
'http://www.islamhouse.com/p/380265',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_mazungumzo_ya_mwislamu_na_Mkristo.pdf',
'',
'',
'',
''),

'4'=>array(
'4',
'Swahili',
'ستون سؤالاً في المسيحية',
'ستون سؤالاً في المسيحية: في هذه الرسالة المختصرة ستون سؤالاً مُوجَّهة لكل مسيحي مُنصِف؛ إذ فيه بيان أغلب مُعتقدات النصارى في هذه الستين سؤالاً.',
'MASWALI 60 KWA WAKRISTO',
'MASWALI 60 KWA WAKRISTO.',
'http://www.islamhouse.com/p/371266',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_Sixtieth_question_in_Christianity.pdf,http://d1.islamhouse.com/data/sw/ih_books/single/sw_Sixtieth_question_in_Christianity.doc',
'',
'',
'',
''),

'5'=>array(
'5',
'Swahili',
'رسالة عيسى عليه السلام الصحيحة',
'رسالة عيسى عليه السلام الصحيحة: حياة عيسى - عليه السلام - كان لها أكبر التأثير على الأديان الرئيسة في العالم، اليهودية، النصرانية، والإسلام، و لأهمية ذلك الوقت الذي كان فيه في هذه الأرض، كان لزامًا معرفة دوره الذي أثر في تغيير معالم التاريخ، ورسالته الصحيحة.',
'Ujumbe wa kweli wa Yesu Kristo',
'Ujumbe wa kweli wa Yesu Kristo.',
'http://www.islamhouse.com/p/371264',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_resalat_esa_saheha.pdf,http://d1.islamhouse.com/data/sw/ih_books/single/sw_resalat_esa_saheha.doc',
'',
'',
'',
''),

'6'=>array(
'6',
'Swahili',
'هل عقيدة التثليث وحي إلهي؟',
'هل عقيدة التثليث وحي إلهي؟: يقول المؤلف في مقدمته للكتاب: «لا شيء يؤذي النصارى أكثر من إثارة الشكوك حول عقيدة التثليث التي تعد صلب عقيدتهم. منذ أن نشأت في حجر النصرانية وأنا أعرف بالفطرة أنه سيؤذي أي نصراني متمسك بدينه أن يرتبك، ويشك في شيء يعلم صحته وقدسيته. لكن في القابل من الأيام عندما أعرف أكثر وأكثر سأكون بعيدًا كل البعد عن مفهوم التقوى في النصرانية لأنني سأكون مضطرًا إلى تنفيذ وصايا الرب لإرشاد الذين ضلوا بسبب هذه العقيدة الفاسدة. إنه لمن أبسط الحقوق لكل شخص أن يعرف الحق الذي يرشده ويهديه إلى الصراط المستقيم».',
'Je, IMANI YA UTATU Ni ya Ufunuo Mtakatifu?',
'Je, IMANI YA UTATU Ni ya Ufunuo Mtakatifu?.',
'http://www.islamhouse.com/p/371262',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_Is_Trinity_Doctrine_Divinely_Inspired.pdf,http://d1.islamhouse.com/data/sw/ih_books/single/sw_Is_Trinity_Doctrine_Divinely_Inspired.doc',
'',
'',
'',
''),

'7'=>array(
'7',
'Swahili',
'أسئلة قادت شباب الشيعة إلى الحق',
'أسئلة قادت شباب الشيعة إلى الحق: رسالة مختصرة تحتوي على بعض الأسئلة والإلزامات الموجهة إلى شباب طائفة الشيعة الاثني عشرية لعلها تساهم في رد العقلاء منهم إلى الحق؛ إذا ما تفكروا في هذه الأسئلة والإلزامات التي لا مجال لدفعها والتخلص منها إلا بلزوم دعوة الكتاب والسنة الخالية من مثل هذه التناقضات.',
'Maswali YaliyowaongozaVijana wa Kishia Kuingia Katika Haki',
'Maswali YaliyowaongozaVijana wa Kishia Kuingia Katika Haki.',
'http://www.islamhouse.com/p/369244',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_questions_led_young_shiat.pdf,http://d1.islamhouse.com/data/sw/ih_books/single/sw_questions_led_young_shiat.doc',
'',
'',
'',
''),

'8'=>array(
'8',
'Swahili',
'إقامة البراهين على حكم من استغاث بغير الله أو صدق الكهنة والعرافين',
'إقامة البراهين على حكم من استغاث بغير الله أو صدق الكهنة والعرافين: رسالةلطيفة عبارة عن ثلاث رسائل مجموعة: الأولى: في حكم الاستغاثة بالنبي - صلى الله عليه وسلم -. والثانية: في حكم الاستغاثة بالجن والشياطين والنذر لهم. والثالثة: في حكم التعبد بالأوراد البدعية والشركية.',
'HUJJA THABITI HUKMU YA MWENYE KUTAKA KUOKOLEWA NA ASIYEKUWA M&#039;NGU AU AKASADIKI WAGANGA NA WAPIGA BAO KIMETUNGWA NA MWANACHUONI MjUZI MTUKUFU',
'-',
'http://www.islamhouse.com/p/339838',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_hujja_thabiti.pdf',
'',
'',
'',
''),

'9'=>array(
'9',
'Swahili',
'محرمات استهان بها كثير من الناس',
'في هذه الرسالة يجد القارئ الكريم عدداً من المحرمات التي ثبت تحريمها في الشريعة مع بيان أدلة التحريم من الكتاب والسنة، وهذه المحظورات مما شاع فعلها وعم ارتكابها بين كثير من المسلمين، والله المستعان.',
'MAHARAMISHO YALIYODHARAULIWA NA WAISLAMU WENGI AMBAYO Nl WAJIBU KUJIHADHARI NAYO',
'-',
'http://www.islamhouse.com/p/339836',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_Prohibitions_that_are_taken_too_lightly.pdf',
'',
'',
'',
'لجنة الدعوة والتعليم بالمدينة المنورة'),

'10'=>array(
'10',
'Swahili',
'تطهير الاعتقاد من أدران الإلحاد',
'تطهير الاعتقاد من أدران الإلحاد: مؤَلَّفٌ فيه بيان ما يجب علمه من أصول قواعد الدين، وبيان لما يجب اجتنابه من اتخاذ الأنداد، والتحذير من الاعتقاد في القبور والأحياء.',
'KUSAFISHA KUW AAMINI UCHAFU WA KUTO AMINI',
'-',
'http://www.islamhouse.com/p/339834',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_Purifying_the_Creed_from_the_Filth_of_Atheism.pdf',
'',
'',
'',
''),

'11'=>array(
'11',
'Swahili',
'أبو هريرة رضي الله عنه صاحب رسول الله صلى الله عليه وآله وسلم دراسة حديثية تاريخية هادفة',
'أبو هريرة رضي الله عنه صاحب رسول الله صلى الله عليه وآله وسلم دراسة حديثية تاريخية هادفة: هو رجل تشرف بصحبة المصطفى صلوات الله وسلامه عليه فآزره ونصره وساهم مع إخوانه الصحابة في بناء حضارة هذه الأمة ومجدها وتاريخها الذي تفخر به وتباهي الأمم.',
'ABU HURAIRA SAHABA WA MTUME',
'-',
'http://www.islamhouse.com/p/336329',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_Abu_huraira.pdf,http://d1.islamhouse.com/data/sw/ih_books/single/sw_Abu_huraira.doc',
'',
'',
'',
''),

'12'=>array(
'12',
'Swahili',
'كيف نقرأ تاريخ الآل والأصحاب؟',
'كيف نقرأ تاريخ الآل والأصحاب: بحث وضح معالم مهمّة للتعامل السليم مع كتب التاريخ، خاصة فيما يتعلّق بتاريخ الخلفاء الراشدين وما يتعلق بسير وتراجم الصحابة - رضي الله عنهم أجمعين - وفضائل آل بيت رسول الله - صلى الله عليه وسلم -، و قد قدم لهذا الكتاب كل من الشيخ عائض القرني، والشيخ حاتم بن عارف العوني.',
'Vipi tusome Tarekhe ya Aal-Beit na Masahaba?',
'-',
'http://www.islamhouse.com/p/336327',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_how_to_read_history.pdf,http://d1.islamhouse.com/data/sw/ih_books/single/sw_how_to_read_history.doc',
'',
'',
'',
''),

'13'=>array(
'13',
'Swahili',
'ما قاله الثقلان في أولياء الرحمن',
'ما قاله الثقلان في أولياء الرحمن: هذه الورقات فيها بيان شافٍ - بإذن الله - و إظهار لمكانة أولئك النفر من الرجال والنساء من الصحابة، لأن من أحب إنساناً أحب أحبابه وتقبلهم بقبول حسن وأبغض أعداءهم ومبغضيهم، وهذه سنة ماضية في الخلق.',
'KAULI YA QURAN NA KAULI ZA AHLI BAIT WA MTUME SAW KUHUSIANA VIPENZI VYA ALLAH',
'-',
'http://www.islamhouse.com/p/336325',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_Ma_qalahu_saqalan.pdf,http://d1.islamhouse.com/data/sw/ih_books/single/sw_Ma_qalahu_saqalan.doc',
'',
'',
'',
''),

'14'=>array(
'14',
'Swahili',
'من عقائد الشيعة',
'من عقائد الشيعة : هذه الرسالة تبين بعض معتقدات الشيعة على طريقة السؤال والجواب بصورة مختصرة.',
'MIONGONI MWA ITIKADI ZA SHIA',
'-',
'http://www.islamhouse.com/p/322550',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_miongoni_mwa_itikadi_di_za_Shia.pdf',
'',
'',
'',
''),

'15'=>array(
'15',
'Swahili',
'معرفة الدين الحق',
'يهدف هذا الكتاب إلى تسهيل الطريق لمن يريد أن يعرف الدين الحق، مع بعض النصائح في كيفية محاورة غير المسلمين.',
'RISALA FUPI YA KUMUWEZESHA MTU KUPAMBANUA NI IPI DINI YA HAKI',
'Hiki ni kitabu kilichotayarishwa kwa lengo la kuwapatia wasomaji, suluhisho la matatizo wanayoyapata watu wengi wanapotaka kufahamu ni ipi Dini ya Haki.',
'http://www.islamhouse.com/p/309041',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_dini_ya_haki.pdf,http://d1.islamhouse.com/data/sw/ih_books/single/sw_dini_ya_haki.doc',
'',
'',
'',
''),

'16'=>array(
'16',
'Swahili',
'تفسير العشر الأخير من القرآن الكريم ويليه أحكام تهم المسلم',
'تفسير العشر الأخير من القرآن الكريم ويليه أحكام تهم المسلم : كتاب مختصر يحوي أهم ما يحتاجه المسلم في حياته من قرآن وتفسير وأحكام فقهية وعقدية وفضائل و غيرها، والكتاب ينقسم إلى جزئين: فأما الجزء الأول فيشتمل على الأجزاء الثلاثة الأخيرة من القرآن الكريم مع تفسيرها من كتاب زبدة التفسير للشيخ محمد الأشقر. وأما الجزء الثاني فيحتوي على أحكام تهم المسلم، وهي: أحكام التجويد، 62 سؤالا في العقيدة، حوار هادئ عن التوحيد، أحكام الاسلام [ الشهادتان، الطهارة، الصلاة، الزكاة، الحج ]، فوائد متفرقة، الرقية، الدعاء، الأذكار، 100 فضيلة و 70 منهيًا، صفة الوضوء والصلاة مصورة، رحلة الخلود.',
'TAFSIRI YA SHEMU YA KUMI YA MWISHO YA QUR\'ANI TUKUFU',
'-',
'http://www.islamhouse.com/p/250948',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_Tafsiri_ya_sehemu_ya_kumi_ya_mwisho_ya_Qurani_Tukufu.pdf',
'',
'',
'',
''),

'17'=>array(
'17',
'Swahili',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة',
'المرأة فى الإسلام والمرأة فى العقيدة اليهودية والمسيحية بين الأسطورة والحقيقة : التحليل العادل والجواب الشافي عن الأسئلة التالية: هل اليهودية والمسيحية والإسلام يشتركون في نفس العقائد الخاصة بالمرأة؟ هل حقاً اليهودية والمسيحية أكرموا المرأة أكثر من الإسلام؟ ما الحقيقة؟',
'Wanawake katika Uislamu Ukilinganisha na Wanawake katika Mafundisho ya Kiyahudi-Kikristo',
'-',
'http://www.islamhouse.com/p/191551',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_Wanawake_katika_Uislamu.pdf',
'',
'',
'',
''),

'18'=>array(
'18',
'Swahili',
'الدليل المصور الموجز لفهم الإسلام',
'كتاب الدليل المصور الموجز لفهم الإسلام باللغة السواحيلية، والذي يتحدث بصفة خاصة عن الإعجاز العلمي في الإسلام، وأيضاً يُعنى بمفاهيم الإسلام وتصوره تجاه الفرد والمجتمع، والمكاسب التي تتحقق لك حالة كونك مسلماً ملتزماً بتعاليم الشريعة الإسلامية. هذا الكتاب تصدر قائمة الكتب الدعوية الموجهة لغير المسلمين في عظيم أثره، لذا يحرص المتخصصون في التعريف بالإسلام بالبدء بإهداء ترجمة معاني القرآن الكريم بلغة غير المسلم ثم يليه في قائمة الإهداء هذا الكتاب، ثم بقية الكتب الدعوية الأخرى.',
'Muongozo Wa Kuufahamu Uislamu Kwa Ufupi Na Kwa Kutumia Vielelezo Vya Picha',
'-',
'http://www.islamhouse.com/p/172713',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_Muongozo_Wa_Kuufahamu.pdf',
'',
'',
'',
''),

'19'=>array(
'19',
'Swahili',
'الدين الصحيح',
'الدين الصحيح: كتابٌ قيمٌ للذين يبحثون عن الحق، فهو يهدي الباحثين للطريق الصحيح، يدعو للتفكُّر في حقائق الدين، ويبين العلاقة بين الخالق والمخلوق.',
'Dini Ya Kweli Ya Mwenyezi Mungu',
'Yaliyomo: • Dini Ya Kweli Ya Mwenyezi Mungu Ni Ipi? • Jina La Dini • Mwenyezi Mungu Na Uumbaji • Ujumbe Wa Dini Za Uwongo • Dini Ya Mwenyezi Mungu Ni Ya Ulimwengu Mzima • Kumtambua Mwenyezi Mungu. • Dalili Za Mwenyezi Mungu. • Hitimisho',
'http://www.islamhouse.com/p/161314',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_Dini_Ya_Kweli_Ya_Mwenyezi_Mungu.pdf,http://d1.islamhouse.com/data/sw/ih_books/single/sw_Dini_Ya_Kweli_Ya_Mwenyezi_Mungu.doc',
'',
'',
'',
''),

'20'=>array(
'20',
'Swahili',
'حصن المسلم من أذكار الكتاب والسنة',
'حصن المسلم : لمصنفه فضيلة الشيخ سعيد بن علي بن وهف القحطاني - حفظه الله - يعد من أنفس كتب أذكار عمل اليوم والليلة في حياة المسلم، وبفضل الله تمت ترجمة هذا الكتاب إلى العديد من اللغات، وحرصنا على جمعها في صفحة واحدة ومواصلة الجهود في ترجمة هذا الكتاب تحت إشراف المؤلف إلى بقية اللغات الأخرى.',
'Hisn Al-Muslim (Kinga Ya Muislamu katika Nyiradi Za Qur-ani Na Hadithi Za Mtume)',
'-',
'http://www.islamhouse.com/p/1590',
'http://d1.islamhouse.com/data/sw/ih_books/single/sw_Kinga_Ya_Muislamu.pdf',
'Said Ali ibn Wahf AI-Qahtaani',
'',
'',
'')

);
?>