<?php
//### from http://www.islamhouse.com ###//
$readers_sora = array(
	"1" => array(
		"name_ar" => "عبدالله بصفر",
		"name_en" => "Abdullah Basfar",
		"folder" => "http://server6.mp3quran.net/bsfr/",
		"description_ar" => "المصحف المرتل للقارئ عبد الله بصفر",
		"description_en" => ""),
	"2" => array(
		"name_ar" => "محمد عبدالكريم",
		"name_en" => "Shaikh Mohammed Abdul Kareem",
		"folder" => "http://server12.mp3quran.net/m_krm/",
		"description_ar" => "المصحف المرتل للقارئ محمد عبد الكريم: تم تسجيله في السودان عام 2007 م.",
		"description_en" => "Shaikh Mohammed Abdul Kareem's recitation of the Quran, which was recorded in Sudan in 2007. This version is characterized by a high quality [MP3: 128 Kbps]"),
	"3" => array(
		"name_ar" => "عبدالرشيد صوفي",
		"name_en" => "Abdul Rasheed Sufi",
		"folder" => "http://server9.mp3quran.net/soufi_klf/",
		"description_ar" => "المصحف المرتل بصوت القارئ عبد الرشيد صوفي برواية حفص عن عاصم، والذي يمتاز بجودة صوتية عالية بتقنية [Mp3 128 Kb].",
		"description_en" => "Reciter Abdul Rasheed Sufi's recitation of the Quran with rewayah Hafs from Asim This version is characterized by a high quality [MP3: 128 Kbps]."),
	"4" => array(
		"name_ar" => "أحمد نعينع",
		"name_en" => "Ahmad Ahmad Nuaina",
		"folder" => "http://server11.mp3quran.net/ahmad_nu/",
		"description_ar" => "المصحف المرتل للقارئ أحمد نعينع برواية حفص عن عاصم، والذي يمتاز بجودة صوتية عالية بتقنية [Mp3 128 Kb].",
		"description_en" => "Riciter Ahmad Ahmad Nuaina's recitation of the Quran with riwayah Hafs from Asim, This version is characterized by a high quality [MP3: 128 Kbps]."),
	"5" => array(
		"name_ar" => "محمود علي البنا",
		"name_en" => "Shaikh Mahmoud Ali al-Banna",
		"folder" => "http://server8.mp3quran.net/bna/",
		"description_ar" => "المصحف المرتل للقارئ محمود علي البنا، والذي يمتاز بجودة صوتية عالية بتقنية Mp3 128 Kb.",
		"description_en" => "Shaikh al-Banna (may Allah have mercy on him) is one of the proficient and skillful reciters. This version is characterized by a high quality [MP3 128 Kbps]"),
	"6" => array(
		"name_ar" => "ياسر الدوسري",
		"name_en" => "Shaikh Yaser Al-Dawsari",
		"folder" => "http://server11.mp3quran.net/yasser/",
		"description_ar" => "المصحف المرتل للقارئ ياسر الدوسري، والذي يمتاز بجودة صوتية عالية بتقنية [ Mp3 128 Kb ] وهذا المصحف هو المصحف الرسمي المعتمد",
		"description_en" => "Shaikh Yaser Al-Dawsari's recitation of the Quran. He is an imam of the Mosque, Riyadh. He is a distinguished reciter with beautiful voice. This version is characterized by a high quality [MP3: 128 Kbps]"),
	"7" => array(
		"name_ar" => "سعود الشريم",
		"name_en" => "Shaikh Saud Al-Shuraim",
		"folder" => "http://server7.mp3quran.net/shur/",
		"description_ar" => "المصحف المرتل للقارئ سعود الشريم، والذي يمتاز بجودة صوتية عالية بتقنية [ Mp3 128 Kb ]، وتم تسجيله من صلاة التروايح بالمسجد الحرام",
		"description_en" => "Complete Recited Mushaf for Reciter Imam and Khateeb Masjid Al-Haraam Shaikh Saud Al-Shuraim, [High Quality mp3 128 format]."),
	"8" => array(
		"name_ar" => "ماهر المعيقلي",
		"name_en" => "Maher Bin Hamd Al-Muayqili",
		"folder" => "http://server12.mp3quran.net/maher/",
		"description_ar" => "المصحف المرتل للقارئ ماهر المعيقلي والذي يمتاز بجودة صوتية عالية بتقنية Mp3 128 Kb",
		"description_en" => "Recited Mushaf for Reciter Maher Bin Hamd Al-Muayqili [High Quality mp3 128 format]."),
	"9" => array(
		"name_ar" => "خالد القحطاني",
		"name_en" => "Khalid Al-Qahtani",
		"folder" => "http://server10.mp3quran.net/qht/",
		"description_ar" => "المصحف المرتل للقارئ خالد القحطاني ، والذي يمتاز بجودة صوتية عالية بتقنية [Mp3 128 Kb].",
		"description_en" => "Recited Mushaf for Reciter Khalid Al-Qahtani [High Quality mp3 128 format]."),
	"10" => array(
		"name_ar" => "عبدالله خياط",
		"name_en" => "Abdullah Khayyat",
		"folder" => "http://server12.mp3quran.net/kyat/",
		"description_ar" => "المصحف المرتل للقارئ عبد الله خياط، والذي يمتاز بجودة صوتية عالية بتقنية mp3 128.",
		"description_en" => "Recited Mushaf for Reciter Abdullah Khayyat [High Quality mp3 128 format]."),
	"11" => array(
		"name_ar" => "صلاح الهاشم",
		"name_en" => "Shaikh Salah Alhashim",
		"folder" => "http://server12.mp3quran.net/salah_hashim_m/",
		"description_ar" => "المصحف المرتل للقارئ صلاح الهاشم والذي يمتاز بجودة صوتية عالية بتقنية [ Mp3 128 Kb ].",
		"description_en" => "Shaikh Salah Alhashim's recitation of the Quran. He is an imam of the Grand Mosque, Kuwait. He is a distinguished reciter with beautiful voice. This version is characterized by a high quality [MP3: 128 Kbps]"),
	"12" => array(
		"name_ar" => "عبدالودود حنيف",
		"name_en" => "Abdul Wadood Maqbool Haneef",
		"folder" => "http://server8.mp3quran.net/wdod/",
		"description_ar" => "المصحف المرتل للقارئ عبد الودود مقبول حنيف، والذي يمتاز بجودة صوتية عالية بتقنية [ Mp3 128 Kb ].",
		"description_en" => "Recited Mushaf for Reciter Abdul Wadood Maqbool Haneef [High Quality mp3 128 format]."),
	"13" => array(
		"name_ar" => "أحمد العجمي",
		"name_en" => "Ahmad Bin Ali Al-Ajmi",
		"folder" => "http://server10.mp3quran.net/ajm/128/",
		"description_ar" => "المصحف المرتل للقارئ أحمد بن علي العجمي، والذي يمتاز بجودة صوتية عالية بتقنية Mp3 128 Kb.",
		"description_en" => "Recited Mushaf for Reciter Ahmad Bin Ali Al-Ajmi [High Quality mp3 128 format]."),
	"14" => array(
		"name_ar" => "فارس عباد",
		"name_en" => "Fares Abbad",
		"folder" => "http://server8.mp3quran.net/frs_a/",
		"description_ar" => "المصحف المرتل للقارئ فارس عبّاد، والذي يمتاز بجودة صوتية عالية بتقنية Mp3 128 Kb.",
		"description_en" => "Recited Mushaf for Reciter Fares Abbad [High Quality mp3 128 format]."),
	"15" => array(
		"name_ar" => "هاني الرفاعي",
		"name_en" => "Hani Al-Rifai",
		"folder" => "http://server8.mp3quran.net/hani/",
		"description_ar" => "المصحف المرتل للقارئ هاني الرفاعي، والذي يمتاز بجودة صوتية عالية بتقنية mp3 128.",
		"description_en" => "Recited Mushaf for Reciter Hani Al-Rifai, and which has the advantage of high-quality audio technology mp3 128"),
	"16" => array(
		"name_ar" => "سهل بن زين ياسين",
		"name_en" => "Sahl Bin Zain Yaseen",
		"folder" => "http://server6.mp3quran.net/shl/",
		"description_ar" => "المصحف المرتل للقارئ سهل بن زين ياسين، والذي يمتاز بجودة صوتية عالية بتقنية [ Mp3 128 Kb ].",
		"description_en" => "Recited Mushaf for Reciter Sahl Bin Zain Yaseen [High Quality mp3 128 format]."),
	"17" => array(
		"name_ar" => "علي عبدالله جابر",
		"name_en" => "Ali Abdullah Jaber",
		"folder" => "http://server11.mp3quran.net/a_jbr/",
		"description_ar" => "المصحف المرتل للقارئ الشيخ علي بن عبد الله بن علي جابر - إمام المسجد الحرام سابقاً رحمه الله - والمسجل في أحد المعامل الصوتية في كندا عام 1403هـ ، وهذا التسجيل من النسخة الأصلية عالية النقاء وبجودة صوتية عالية بتقنية MP3 وبدقة 128 كيلوبت في الثانية ، وبفضل الله حصلنا على نسخة منه بالتعاون مع موقع الشيخ - رحمه الله - www.alijaber.net",
		"description_en" => "Recited Mushaf for Reciter Ali Abdullah Jaber and it has been recorded in one of the studios of Canada."),
	"18" => array(
		"name_ar" => "محمد أيوب",
		"name_en" => "Muhammad Ayyob",
		"folder" => "http://server8.mp3quran.net/ayyub/",
		"description_ar" => "المصحف المرتل للقارئ محمد أيوب، والذي يمتاز بجودة صوتية عالية بتقنية [ Mp3 128 Kb ].",
		"description_en" => "Recited Mushaf for Reciter Muhammad Ayyob [High Quality mp3 128 format]."),
	"19" => array(
		"name_ar" => "سعد الغامدي",
		"name_en" => "Saad Al-Gamdi",
		"folder" => "http://server7.mp3quran.net/s_gmd/",
		"description_ar" => "المصحف المرتل بصوت القارئ سعد الغامدي، والذي يمتاز بجودة صوتية عالية بتقنية Mp3 128 kb.",
		"description_en" => "Recited Mushaf for Reciter Saad Al-Gamdi [High Quality mp3 128 format]."),
	"20" => array(
		"name_ar" => "صلاح بو خاطر",
		"name_en" => "Salah Bu Khater",
		"folder" => "http://server8.mp3quran.net/bu_khtr/",
		"description_ar" => "المصحف المرتل للقارئ صلاح بو خاطر، والذي يمتاز بجودة صوتية عالية بتقنية mp3 128.",
		"description_en" => "Recited Mushaf for Reciter Salah Bu Khater [High Quality mp3 128 format]."),
	"21" => array(
		"name_ar" => "عبد الله بن عواد الجهني",
		"name_en" => "Abdullah bin Awwad Al-Juhany",
		"folder" => "http://server13.mp3quran.net/jhn/",
		"description_ar" => "المصحف المرتل للقارئ عبد الله بن عواد الجهني، والذي يمتاز بجودة صوتية عالية بتقنية mp3 128.",
		"description_en" => "Recited Mushaf for Reciter and the Imam of the Holy Mosque in Mekka Abdullah bin Awwad Al-Juhany [High Quality mp3 128 format]."),
	"22" => array(
		"name_ar" => "أبو بكر الشاطري",
		"name_en" => "Shaikh AbuBakr As-Shatery",
		"folder" => "http://server11.mp3quran.net/shatri/",
		"description_ar" => "المصحف المرتل للقارئ شيخ أبو بكر الشاطري والذي يمتاز بجودة صوتية عالية بتقنية Mp3 128 Kb.",
		"description_en" => "Recited Mushaf for Reciter Shaikh AbuBakr As-Shatery [High Quality mp3 128 format]."),
	"23" => array(
		"name_ar" => "محمد صديق المنشاوي",
		"name_en" => "Muhammad Siddiq Al-Manshawi",
		"folder" => "http://server10.mp3quran.net/minsh/",
		"description_ar" => "المصحف المجود للقارئ محمد صديق المنشاوي، والذي يمتاز بجودة صوتية عالية بتقنية Mp3 128 Kb.",
		"description_en" => "Recited Mushaf for Reciter Muhammad Siddiq Al-Manshawi, [High Quality mp3 128 format]."),
	"24" => array(
		"name_ar" => "محمود خليل الحصري",
		"name_en" => "Mahmood Khaleel Al-Husari",
		"folder" => "http://server13.mp3quran.net/husr/",
		"description_ar" => "المصحف المرتل للقارئ محمود خليل الحصري، والذي يمتاز بجودة صوتية عالية بتقنية Mp3 128 Kb.",
		"description_en" => "Recited Mushaf for Reciter Mahmood Khaleel Al-Husari, [High Quality mp3 128 format]."),
	"25" => array(
		"name_ar" => "عبدالباسط عبدالصمد",
		"name_en" => "Abdul Basit Abdus Samad",
		"folder" => "http://server13.mp3quran.net/basit_mjwd/",
		"description_ar" => "المصحف المرتل للقارئ عبد الباسط عبد الصمد، والذي يمتاز بجودة صوتية عالية بتقنية Mp3 128 Kb.",
		"description_en" => "Recited Mushaf for Reciter Abdul Basit Abdus Samad, [High Quality mp3 128 format]."),
	"26" => array(
		"name_ar" => "عبدالعزيز الأحمد",
		"name_en" => "AbdulAzeez al-Ahmad",
		"folder" => "http://download.quranicaudio.com/quran/abdulazeez_al-ahmad/",
		"description_ar" => "",
		"description_en" => ""),
	"27" => array(
		"name_ar" => "عبدالرحمن السديس",
		"name_en" => "Abdur-Rahman as-Sudais",
		"folder" => "http://download.quranicaudio.com/quran/abdurrahmaan_as-sudays/",
		"description_ar" => "",
		"description_en" => ""),
	"28" => array(
		"name_ar" => "علي الحذيفي",
		"name_en" => "Ali Abdur-Rahman al-Huthaify",
		"folder" => "http://download.quranicaudio.com/quran/huthayfi/",
		"description_ar" => "",
		"description_en" => ""),
	"29" => array(
		"name_ar" => "حمد سنان",
		"name_en" => "Hamad Sinan",
		"folder" => "http://download.quranicaudio.com/quran/hamad_sinan/",
		"description_ar" => "",
		"description_en" => ""),
	"30" => array(
		"name_ar" => "ابراهيم الجبرين",
		"name_en" => "Ibrahim Al-Jibrin",
		"folder" => "http://download.quranicaudio.com/quran/jibreen/",
		"description_ar" => "",
		"description_en" => ""),
	"31" => array(
		"name_ar" => "محمد المحيسني",
		"name_en" => "Muhammad al-Mehysni",
		"folder" => "http://download.quranicaudio.com/quran/mehysni/",
		"description_ar" => "",
		"description_en" => ""),
	"32" => array(
		"name_ar" => "صالح آل طالب",
		"name_en" => "Saleh al Taleb",
		"folder" => "http://download.quranicaudio.com/quran/saleh_al_taleb/",
		"description_ar" => "",
		"description_en" => ""),
	"33" => array(
		"name_ar" => "عبدالباري الثبيتي",
		"name_en" => "AbdulBari ath-Thubaity",
		"folder" => "http://download.quranicaudio.com/quran/thubaity/",
		"description_ar" => "",
		"description_en" => ""),
	"34" => array(
		"name_ar" => "عادل الكلباني",
		"name_en" => "Adel Kalbani",
		"folder" => "http://download.quranicaudio.com/quran/adel_kalbani/",
		"description_ar" => "",
		"description_en" => ""),
	"35" => array(
		"name_ar" => "محمد اللحيدان",
		"name_en" => "Muhammad al-Luhaidan",
		"folder" => "http://download.quranicaudio.com/quran/muhammad_alhaidan/",
		"description_ar" => "",
		"description_en" => ""),
	"36" => array(
		"name_ar" => "صلاح البدير",
		"name_en" => "Salah al-Budair",
		"folder" => "http://download.quranicaudio.com/quran/salahbudair/",
		"description_ar" => "",
		"description_en" => ""),
	"37" => array(
		"name_ar" => "مشاري العفاسي",
		"name_en" => "Mshari Alefasi",
		"folder" => "http://www.quran-for-all.com/sound/mushary_alafasy/",
		"description_ar" => "من موقع www.quran-for-all.com",
		"description_en" => "From www.quran-for-all.com")
);


$readers_ayat = array(
	"1" => array(
		"name_ar" => "عبدالباسط عبدالصمد",
		"name_en" => "Abdelbaset Abdulsama",
		"folder" => "http://www.everyayah.com/data/Abdul_Basit_Mujawwad_128kbps",
		"description" => "مصحف مجود"
	),
	"2" => array(
		"name_ar" => "عبدالله بصفر", 
		"name_en" => "Abdullah Basfer", 
		"folder" => "http://www.everyayah.com/data/Abdullah_Basfar_192kbps", 
		"description" => "جودة 192 كيلوبايت"
	),
	"3" => array(
		"name_ar" => "عبدالرحمن السديس", 
		"name_en" => "Abdelrahman Alsodis", 
		"folder" => "http://www.everyayah.com/data/Abdurrahmaan_As-Sudais_192kbps", 
		"description" => ""
	),
	"4" => array(
		"name_ar" => "ابوبكر الشاطري", 
		"name_en" => "Abobaker Alshatri", 
		"folder" => "http://www.everyayah.com/data/Abu%20Bakr%20Ash-Shaatree_128kbps", 
		"description" => ""
	),
	"5" => array(
		"name_ar" => "احمد العجمي", 
		"name_en" => "Ahmad Alajmi", 
		"folder" => "http://www.everyayah.com/data/Ahmed_ibn_Ali_al-Ajamy_128kbps_ketaballah.net", 
		"description" => "جوده 128 كيلوبايت"
	),
	"6" => array(
		"name_ar" => "سعد الغامدي", 
		"name_en" => "Saad Aljamedi", 
		"folder" => "http://www.everyayah.com/data/Ghamadi_40kbps", 
		"description" => ""
	),
	"7" => array(
		"name_ar" => "هاني الرفاعي", 
		"name_en" => "Hani Alrefae", 
		"folder" => "http://www.everyayah.com/data/Hani_Rifai_192kbps", 
		"description" => ""
	),
	"8" => array(
		"name_ar" => "محمود خليل الحصري", 
		"name_en" => "Mahmoud Khalil Alhosari", 
		"folder" => "http://www.everyayah.com/data/Husary_128kbps_Mujawwad", 
		"description" => "المصحف المجود"
	),
	"9" => array(
		"name_ar" => "علي الحذيفي", 
		"name_en" => "Ali Alhudifi", 
		"folder" => "http://www.everyayah.com/data/Hudhaify_128kbps", 
		"description" => "جودة 128 كيلوبايت"
	),
	"10" => array(
		"name_ar" => "ابراهيم الاخضر", 
		"name_en" => "Ibrahem Alakhdar", 
		"folder" => "http://www.everyayah.com/data/Ibrahim_Akhdar_32kbps", 
		"description" => ""
	),
	"11" => array(
		"name_ar" => "محمد صديق المشاوي", 
		"name_en" => "Mohammed seddeq Almenshawi", 
		"folder" => "http://www.everyayah.com/data/Minshawy_Murattal_128kbps", 
		"description" => "المصحف المرتل"
	),
	"12" => array(
		"name_ar" => "محمد الطبلاوي", 
		"name_en" => "Mohammed Altablawi", 
		"folder" => "http://www.everyayah.com/data/Mohammad_al_Tablaway_128kbps", 
		"description" => ""
	),
	"13" => array(
		"name_ar" => "محمد أيوب", 
		"name_en" => "Mohammed Ayoub", 
		"folder" => "http://www.everyayah.com/data/Muhammad_Ayyoub_128kbps", 
		"description" => ""
	),
	"14" => array(
		"name_ar" => "محمد جبريل", 
		"name_en" => "Mohammed Jebrel", 
		"folder" => "http://www.everyayah.com/data/Muhammad_Jibreel_128kbps", 
		"description" => ""
	),
	"15" => array(
		"name_ar" => "سعود الشريم", 
		"name_en" => "Saoud Alshorim", 
		"folder" => "http://www.everyayah.com/data/Saood%20bin%20Ibraaheem%20Ash-Shuraym_128kbps", 
		"description" => ""
	),	
	"16" => array(
		"name_ar" => "مشاري العفاسي",
		"name_en" => "Mshari Alefasi",
		"folder" => "http://www.quran-for-all.com/sound/versebyverse/alafasy/",
		"description" => "من الموقع www.quran-for-all.com"
	)
);
?>